Esri/arcgis-maps-sdk-swift-toolkit

Sources/ArcGISToolkit/Components/FloatingPanel/FloatingPanel.swift

Add bottom content padding to Floating Panel

---

Sources/ArcGISToolkit/Components/Authentication/NetworkChallengeContinuation.swift
Sources/ArcGISToolkit/Components/Popups/Attachments/AttachmentList.swift
Sources/ArcGISToolkit/Components/Popups/Attachments/AttachmentsPopupElementModel.swift
Sources/ArcGISToolkit/Components/Popups/AttachmentsPopupElementView.swift
Sources/ArcGISToolkit/Extensions/UtilityTraceFunction.FunctionType.swift

Closes #214 as reported by @zkline101 and @mhdostal

Resolve `@unknown default` warnings

---

Sources/ArcGISToolkit/Components/FloorFilter/SiteAndFacilitySelector.swift

Fix jumpy Floor Filter behavior

---

README.md

Fix forum link

---

AuthenticationExample/AuthenticationExample/AuthenticationApp.swift
AuthenticationExample/AuthenticationExample/SignInView.swift
Examples/Examples/UtilityNetworkTraceExampleView.swift
Sources/ArcGISToolkit/Components/Authentication/Authenticator.swift
Sources/ArcGISToolkit/Components/Authentication/TokenChallengeContinuation.swift
Tests/ArcGISToolkitTests/AuthenticatorTests.swift
Tests/ArcGISToolkitTests/Test Support/Extensions/XCTest/XCTestCase+ArcGISURLSession.swift
Tests/ArcGISToolkitTests/UtilityNetworkTraceViewModelTests.swift

This PR will be merged after beta release.

use changed authentication APIs from SDK

---

Sources/ArcGISToolkit/Components/UtilityNetworkTrace/UtilityNetworkTrace.swift

From the doc for `CustomStringConvertible.description`:
> ![image](https://user-images.githubusercontent.com/2257493/208513038-d523b2bb-8275-4f12-bfb1-00dd7cedd2a0.png)
Values displayed to the user should always be formatted. This PR replaces uses of `CustomStringConvertible.description` with a formatted value, which includes the correct grouping separator (when appropriate).

Remove uses of `CustomStringConvertible.description` from `UtilityNetworkTrace.swift`

---

Sources/ArcGISToolkit/Components/UtilityNetworkTrace/UtilityNetworkTraceViewModelTrace.swift

Reorganize `UtilityNetworkTraceViewModelTrace.Trace`

---

Sources/ArcGISToolkit/Components/Authentication/CertificatePickerViewModifier.swift

- Add security scoping to the url which seems to fix issues accessing iCloud Document url's 
- Switch to using a detached task to avoid deserializing the certificate on the main thread.

Adjust how certificates are imported

---

Package.swift
Sources/ArcGISToolkit/Components/Authentication/CertificatePickerViewModifier.swift
Sources/ArcGISToolkit/Resources/en.lproj/Localizable.strings
Tests/ArcGISToolkitTests/CertificatePickerViewModelTests.swift

Closes https://github.com/Esri/arcgis-maps-sdk-swift-toolkit/issues/241

added certificate errors

---

Sources/ArcGISToolkit/Components/BasemapGallery/BasemapGallery.swift
Sources/ArcGISToolkit/Components/FloorFilter/FloorFilterViewModel.swift
Sources/ArcGISToolkit/Components/Search/SearchResult.swift
Sources/ArcGISToolkit/Components/Search/SearchViewModel.swift
Sources/ArcGISToolkit/Components/UtilityNetworkTrace/UtilityNetworkTrace.swift
Sources/ArcGISToolkit/Components/UtilityNetworkTrace/UtilityNetworkTraceViewModel.swift

- `Viewpoint(targetExtent:)` -> `Viewpoint(boundingGeometry:)`
- Error handling changes

Fix build errors

---

Sources/ArcGISToolkit/Components/FloorFilter/FloorFilter.swift
Sources/ArcGISToolkit/Components/FloorFilter/FloorFilterViewModel.swift
Sources/ArcGISToolkit/Components/FloorFilter/SiteAndFacilitySelector.swift

Floor Filter Bug Fixes

---

Sources/ArcGISToolkit/Components/Popups/AttachmentsPopupElementView.swift

Fix build error

---

Tests/ArcGISToolkitTests/BookmarksTests.swift

Fix bookmark tests

---

Documentation/BasemapGallery/README.md
Examples/Examples/BasemapGalleryExampleView.swift
Sources/ArcGISToolkit/Components/BasemapGallery/BasemapGallery.swift
Sources/ArcGISToolkit/Components/BasemapGallery/BasemapGalleryViewModel.swift

Closes #265 
- This PR will make the number of grid columns dynamically computed based on the available width.

[Basemap Gallery] Make responsive to environment

---

AuthenticationExample/AuthenticationExample.xcodeproj/project.pbxproj
AuthenticationExample/AuthenticationExample/AuthenticationExample.entitlements
AuthenticationExample/AuthenticationExample/SignInView.swift
AuthenticationExample/AuthenticationExample/UserView.swift

fix warnings

---

Sources/ArcGISToolkit/Components/FloorFilter/SiteAndFacilitySelector.swift

Fix Mac Catalyst build

---

Sources/ArcGISToolkit/Components/BasemapGallery/BasemapGalleryViewModel.swift

Clone user-supplied basemap prior to setting

---

Sources/ArcGISToolkit/Components/Popups/PopupView.swift
Sources/ArcGISToolkit/Components/Search/SearchView.swift
Sources/ArcGISToolkit/Resources/en.lproj/Localizable.strings
Sources/ArcGISToolkit/Resources/es.lproj/Localizable.strings

This branch is based off of and to be merged following #332 
Closes #333 
Related #247 
Adds starter localization strings. See #333 for context.

Add starter english localizable strings

---

Examples/Examples/FloorFilterExampleView.swift
Examples/Examples/ScalebarExampleView.swift
Examples/Examples/SearchExampleView.swift

Use new attribution bar height change API

---

README.md

See also [Samples #196](https://github.com/Esri/arcgis-maps-sdk-swift-samples/pull/196#pullrequestreview-1468727287)

Bump Xcode req to 14.1

---

Sources/ArcGISToolkit/Components/Form/FormInputs/DateTimeEntry.swift
Sources/ArcGISToolkit/Components/Form/FormInputs/MultiLineTextEntry.swift
Sources/ArcGISToolkit/Components/Form/FormInputs/SingleLineTextEntry.swift
Sources/ArcGISToolkit/Components/Form/FormView.swift
Sources/ArcGISToolkit/Components/Form/FormViewModel.swift

- Adds date picker support to the Form View component
Finalized design pending

[FormView] Add date picker support

---

Tests/ArcGISToolkitTests/BookmarksTests.swift

https://github.com/Esri/arcgis-maps-sdk-swift-toolkit/issues/398

Fix compiler warning in BookmarksTest

---

Sources/ArcGISToolkit/Utility/CredentialInputView.swift

Currently this is the only change that I'm aware of in the feedback from field maps. More might come later as I get more feedback from apps team.

use full sheet because keyboard has to come up anyway

---

Sources/ArcGISToolkit/Components/Search/SearchView.swift
Sources/ArcGISToolkit/Resources/en.lproj/Localizable.strings

Resolves [this](https://github.com/Esri/arcgis-maps-sdk-swift-toolkit/pull/420#discussion_r1313466033) feedback

Adjust search repeat button title

---

Sources/ArcGISToolkit/Components/Form/FormInputs/MultiLineTextEntry.swift
Sources/ArcGISToolkit/Components/Form/FormInputs/SingleLineTextEntry.swift

The noted bug is no longer present as of iOS 17 Beta 7

`FormView` - Remove bug note

---

Sources/ArcGISToolkit/Components/Form/FormInputs/DateTimeEntry.swift
Sources/ArcGISToolkit/Components/Form/FormView.swift
Sources/ArcGISToolkit/Components/Form/TextEntryFooter.swift
UI Test Runner/UI Test Runner/TestViews/FormViewTestView.swift
UI Test Runner/UI Test Runner/Tests.swift
UI Test Runner/UITests/FormViewTests.swift

Apollo 94
- Adds UI tests for `FormView` DateTime fields
- Revises existing test case 1 tests

`FormView` - Add DateTime picker UI tests, revise test case 1

---

Sources/ArcGISToolkit/Components/AR/TableTopSceneView.swift

This PR improves plane visualization in TableTop AR by creating a plane with convex polygon geometry which is more accurate since it uses all enclosing points with [ARSCNPlaneGeometry](https://developer.apple.com/documentation/arkit/arscnplanegeometry). The previous implementation visualizes a plane with less accuracy since the plane geometry is estimated based on the plane anchor's extent and center.

AR: Improve TableTop AR plane visulaization

---

Sources/ArcGISToolkit/Components/AR/TableTopSceneView.swift

Adds documentation for:
- properties in TableTopSceneView
- SwiftUI preference bug workaround

AR: Add TableTop documentation

---

Sources/ArcGISToolkit/Components/AR/TableTopSceneView.swift

This PR observes the following property changes and applies them to TableTopSceneView:
-  anchorPoint
- translationFactor
- clippingDistance

AR: Observe TableTop property changes

---

Sources/ArcGISToolkit/Components/Form/FormInputs/SwitchInput.swift

#441 inadvertently removed the `SwitchInput` source

`FormView` - Revive `SwitchInput.swift`

---

Sources/ArcGISToolkit/Components/Form/FormInputStyle.swift
Sources/ArcGISToolkit/Components/Form/FormInputs/ComboBoxInput.swift
Sources/ArcGISToolkit/Components/Form/FormInputs/DateTimeInput.swift
Sources/ArcGISToolkit/Components/Form/FormInputs/MultiLineTextInput.swift
Sources/ArcGISToolkit/Components/Form/FormInputs/SingleLineTextInput.swift
Sources/ArcGISToolkit/Components/Form/FormInputs/SwitchInput.swift

Revises the common input styling.
|   | Before  | After  |
|---|---|---|
| Combo  | <img width="392" alt="cat-combo-before" src="https://github.com/Esri/arcgis-maps-sdk-swift-toolkit/assets/16397058/8e63800e-c7c1-4158-b4d2-fd5f36b0bdef"> | <img width="392" alt="cat-combo-after" src="https://github.com/Esri/arcgis-maps-sdk-swift-toolkit/assets/16397058/e8a2d0c6-adea-4997-9ead-3a469948ba95"> |
| Date  | <img width="392" alt="cat-date-before" src="https://github.com/Esri/arcgis-maps-sdk-swift-toolkit/assets/16397058/91b3ecec-2bca-45fd-bb82-036820499adb"> | <img width="392" alt="cat-date-after" src="https://github.com/Esri/arcgis-maps-sdk-swift-toolkit/assets/16397058/69813d05-b5e7-4aef-a6b3-262d44ce2f1d">  |
| Radio  | <img width="392" alt="cat-radio-before" …

`FormView` - Revise common input styling

---

UI Test Runner/UI Test Runner/TestViews/FormViewTestView.swift

Fixes a build error in the test view to accommodate expression eval functionality.

`FormView` - Fix build error in test view

---

Examples/Examples/FormViewExampleView.swift
Examples/ExamplesApp/Examples.swift

This work was already performed in #442 but was inadvertently undone in #441.

`FormView` - General refactoring (redo)

---

Examples/Examples.xcodeproj/project.pbxproj
Examples/Examples/FormViewExampleView.swift

- Updates the name of the sample view in the examples project manifest
- Re-adds a placeholder value for the sample view data

`FormView` - Minor example tweaks

---

Sources/ArcGISToolkit/Components/Form/TextInputFooter.swift

`FormView` - Fix text input footer validation string

---

Sources/ArcGISToolkit/Components/Form/FormInputs/ComboBoxInput.swift
Sources/ArcGISToolkit/Components/Form/FormInputs/DateTimeInput.swift
Sources/ArcGISToolkit/Components/Form/FormInputs/FormInputModel.swift
Sources/ArcGISToolkit/Components/Form/FormInputs/MultiLineTextInput.swift
Sources/ArcGISToolkit/Components/Form/FormInputs/RadioButtonsInput.swift
Sources/ArcGISToolkit/Components/Form/FormInputs/SingleLineTextInput.swift
Sources/ArcGISToolkit/Components/Form/FormInputs/SwitchInput.swift
Sources/ArcGISToolkit/Components/Form/FormView.swift
Sources/ArcGISToolkit/Components/Form/FormViewModel.swift
Sources/ArcGISToolkit/Components/Form/TextInputFooter.swift

Closes Apollo 116
Note this PR affected by some known issues:
Apollo 233
Apollo 240

`FormView` - Use new `updateValue`, `value` and `formattedValue` APIs

---

Examples/Examples/FloatingPanelExampleView.swift
Examples/Examples/FormViewExampleView.swift
Sources/ArcGISToolkit/Components/FloatingPanel/FloatingPanel.swift
Sources/ArcGISToolkit/Components/FloatingPanel/FloatingPanelDetent.swift
Sources/ArcGISToolkit/Components/FloatingPanel/FloatingPanelModifier.swift
Sources/ArcGISToolkit/Components/Form/FormInputs/DateTimeInput.swift
Sources/ArcGISToolkit/Components/Form/FormInputs/MultiLineTextInput.swift
Sources/ArcGISToolkit/Components/Form/FormInputs/SingleLineTextInput.swift
Sources/ArcGISToolkit/Components/Form/FormView.swift
Sources/ArcGISToolkit/Components/Form/FormViewModel.swift
Sources/ArcGISToolkit/Extensions/ArcGIS/FormElement.swift

`FloatingPanel` - Improve keyboard avoidance, `FormView` -  Scroll to focused form element

---

Examples/Examples/FloatingPanelExampleView.swift
Sources/ArcGISToolkit/Components/FloatingPanel/FloatingPanel.swift
Sources/ArcGISToolkit/Components/FloatingPanel/FloatingPanelDetent.swift
Sources/ArcGISToolkit/Components/FloatingPanel/FloatingPanelModifier.swift

These changes already reviewed in #483.
This PR simply applies new improvements that were made to the `FloatingPanel` to better support `FormView`.

`FloatingPanel` - Bring in updates for `FormView`

---

Examples/Examples/PopupExampleView.swift
Sources/ArcGISToolkit/Documentation.docc/Resources/PopupView/PopupViewStep5.swift
Sources/ArcGISToolkit/Documentation.docc/Resources/PopupView/PopupViewStep6.swift

I noticed the popup code is more complex than it needed to be. It was converting the result of an async throwing method into a Result unnecessarily.

Popup simplification

---

Sources/ArcGISToolkit/Components/Popups/PopupView.swift

Auto-refresh popup view for dynamic entities.
This is hard to test because the SDK doesn't allow you to create popups for dynamic entities because of 2 issues. I added a workaround in the SDK and I can provide that to the reviewers of this PR. 
Toolkit example code for this is in `ryan/dynamicEntityPopup` branch if you want to try test it out.

Auto-refresh popup view for dynamic entities

---

Sources/ArcGISToolkit/Components/Augmented Reality/FlyoverSceneView.swift
Sources/ArcGISToolkit/Components/Augmented Reality/TableTopSceneView.swift
Tests/ArcGISToolkitTests/ARTests.swift

Adds unit tests for FlyoverSceneView and TableTopSceneView.

AR: Add unit tests

---

Sources/ArcGISToolkit/Components/FormView/FormInputs/TextInput.swift

`FormView` - Enable non-editable text selection

---

Sources/ArcGISToolkit/Documentation.docc/AugmentedReality.md

Adds requirements section to Augmented Reality docC article.

AR: Add api reference documentation for camera access

---

README.md

I noticed the new AR components were missing from the list.
Adding a one liner for each

Adding AR components to the list

---

Sources/ArcGISToolkit/Components/FormView/FormView.swift

`FormView` - Fix autoscroll

---

AuthenticationExample/AuthenticationExample.xcodeproj/project.pbxproj
Examples/Examples.xcodeproj/project.pbxproj
JobManagerExample/JobManagerExample.xcodeproj/project.pbxproj
Package.swift
UI Test Runner/UI Test Runner.xcodeproj/project.pbxproj

Updates version numbers for 200.3 release. I will wait to merge this PR closer to the release date.

Update marketing version number to `200.3`

---

Examples/Examples/FormViewExampleView.swift
Sources/ArcGISToolkit/Components/FormView/ClearButton.swift
Sources/ArcGISToolkit/Components/FormView/FormElementPadding.swift
Sources/ArcGISToolkit/Components/FormView/FormHeader.swift
Sources/ArcGISToolkit/Components/FormView/FormInputStyle.swift
Sources/ArcGISToolkit/Components/FormView/FormInputs/DateTimeInput.swift
Sources/ArcGISToolkit/Components/FormView/FormInputs/FormInputModel.swift
Sources/ArcGISToolkit/Components/FormView/FormInputs/InputHeader.swift
Sources/ArcGISToolkit/Components/FormView/FormInputs/TextInput.swift
Sources/ArcGISToolkit/Components/FormView/FormView.swift
Sources/ArcGISToolkit/Components/FormView/FormViewModel.swift
Sources/ArcGISToolkit/Components/FormView/GroupView.swift
Sources/ArcGISToolkit/Components/FormView/LengthValidationScheme.swift
Sources/ArcGISToolkit/Components/FormView/TextInputFooter.swift
Sources/ArcGISToolkit/Components/FormView/TextValidationError.swift
Sources/ArcGISToolkit/Extensions/ArcGIS/FieldType.swift
Sources/ArcGISToolkit/Extensions/ArcGIS/FormElement.swift
UI Test Runner/UI Test Runner/TestViews/FormViewTestView.swift
UI Test Runner/UITests/FormViewTests.swift

`FormView` - Align preambles

---

Sources/ArcGISToolkit/Components/FormView/FormInputs/FormInputModel.swift
Sources/ArcGISToolkit/Components/FormView/FormView.swift
Sources/ArcGISToolkit/Components/FormView/FormViewModel.swift

Updates to Task creation and disposal for `isVisible`, `isRequired`, `isEditable`, and `value`.

Task updates to model classes.

---

Examples/Examples.xcodeproj/project.pbxproj
Examples/Examples/WorldScaleGeoTrackingExampleView.swift
Examples/ExamplesApp/Examples.swift
Sources/ArcGISToolkit/Components/Augmented Reality/WorldScaleGeoTrackingSceneView.swift

Refactors https://github.com/Esri/arcgis-maps-sdk-swift-toolkit/pull/466.

AR: Refactor world scale

---

Sources/ArcGISToolkit/Components/FormView/ClearButton.swift
Sources/ArcGISToolkit/Components/FormView/FormInputs/ComboBoxInput.swift
Sources/ArcGISToolkit/Components/FormView/FormInputs/DateTimeInput.swift
Sources/ArcGISToolkit/Components/FormView/FormInputs/TextInput.swift

`FormView` - Provide instantaneous focus on clear

---

Sources/ArcGISToolkit/Components/FormView/FormInputs/ComboBoxInput.swift
Sources/ArcGISToolkit/Components/FormView/FormInputs/RadioButtonsInput.swift
Sources/ArcGISToolkit/Extensions/ArcGIS/FieldFormElement.swift

`FormView` - Coded value fix

---

Examples/Examples/FeatureFormExampleView.swift
Sources/ArcGISToolkit/Components/FeatureFormView/FormInputs/ComboBoxInput.swift
Sources/ArcGISToolkit/Components/FeatureFormView/FormInputs/InputFooter.swift

Apollo 387
Resolves warnings accumulated over the course of forms work

`FeatureFormView` - Resolve warnings

---

Examples/Examples/UtilityNetworkTraceExampleView.swift
Sources/ArcGISToolkit/Components/FeatureFormView/GroupView.swift

Also fixes a SwiftLint warning in the UtilityNetworkTraceExampleView

Fixes the build for the GroupElement.elements change

---

Sources/ArcGISToolkit/Components/Augmented Reality/Joyslider.swift

Removes SwiftUI preview which causes build error when running a build script.

Remove SwiftUI preview

---

Tests/ArcGISToolkitTests/APIKey.swift
Tests/ArcGISToolkitTests/BasemapGalleryItemTests.swift
Tests/ArcGISToolkitTests/BasemapGalleryViewModelTests.swift
Tests/ArcGISToolkitTests/UtilityNetworkTraceViewModelTests.swift

Centralize API key location for automated unit test runs

---

Sources/ArcGISToolkit/Components/FeatureFormView/FormInputs/InputFooter.swift
Sources/ArcGISToolkit/Components/FeatureFormView/FormViewModel.swift
Test Runner/UI Tests/FormViewTests.swift

`FeatureFormView` - Improve redraw

---

Examples/Examples/FeatureFormExampleView.swift
Test Runner/Test Runner/TestViews/FeatureFormTestView.swift

Adds simple behavior to the view model to select the feature when the form appears and deselect it once the form is closed.

`FeatureFormView` - Select the feature being edited

---

Sources/ArcGISToolkit/Components/Augmented Reality/Utilities/GeoTrackingSceneView.swift
Sources/ArcGISToolkit/Components/Augmented Reality/Utilities/WorldTrackingSceneView.swift
Sources/ArcGISToolkit/Components/Augmented Reality/WorldScaleSceneView.swift
Tests/ArcGISToolkitTests/ARTests.swift

AR: Add unit tests for world scale AR

---

Sources/ArcGISToolkit/Components/Scalebar/Scalebar.swift

Adds additional logic around show/hide to prevent constant animation scheduling.

`Scalebar` - Revise auto-hide behavior

---

Sources/ArcGISToolkit/Components/Augmented Reality/Utilities/ARSwiftUIView.swift
Sources/ArcGISToolkit/Components/Augmented Reality/Utilities/GeoTrackingSceneView.swift
Sources/ArcGISToolkit/Components/Augmented Reality/Utilities/WorldTrackingSceneView.swift
Sources/ArcGISToolkit/Components/Augmented Reality/WorldScaleSceneView.swift

AR: Add status view modifiers

---

Tests/ArcGISToolkitTests/AuthenticationManagerTests.swift

Authentication Manager Catalyst patch

---

Sources/ArcGISToolkit/Components/FeatureFormView/FeatureFormView.swift
Sources/ArcGISToolkit/Components/FeatureFormView/FormInputs/ComboBoxInput.swift
Sources/ArcGISToolkit/Components/FeatureFormView/FormInputs/DateTimeInput.swift
Sources/ArcGISToolkit/Components/FeatureFormView/FormInputs/EditableStateInputWrapper.swift
Sources/ArcGISToolkit/Components/FeatureFormView/FormInputs/RadioButtonsInput.swift
Sources/ArcGISToolkit/Components/FeatureFormView/FormInputs/ReadOnlyInput.swift
Sources/ArcGISToolkit/Components/FeatureFormView/FormInputs/SwitchInput.swift
Sources/ArcGISToolkit/Components/FeatureFormView/FormInputs/TextInput.swift
Sources/ArcGISToolkit/Extensions/ArcGIS/FieldFormElement.swift
Test Runner/Test Runner/TestViews/FeatureFormTestView.swift
Test Runner/Test Runner/Tests.swift
Test Runner/UI Tests/FormViewTests.swift

`FeatureFormView` - Revise read only inputs

---

Sources/ArcGISToolkit/Documentation.docc/AugmentedReality.md

AR: World Scale documentation

---

README.md

Adds `WorldScaleSceneView` component to the README.

AR: Update README.md

---

Sources/ArcGISToolkit/Components/Augmented Reality/WorldScaleSceneView.swift

world-scale: animate the scene view in

world-scale: animate the scene view in

---

Sources/ArcGISToolkit/Components/Augmented Reality/Utilities/CalibrationView.swift
Sources/ArcGISToolkit/Components/Augmented Reality/Utilities/GeoTrackingSceneView.swift
Sources/ArcGISToolkit/Components/Augmented Reality/Utilities/WorldTrackingSceneView.swift
Sources/ArcGISToolkit/Components/Augmented Reality/WorldScaleSceneView.swift

AR: Refactor calibration view

---

Sources/ArcGISToolkit/Components/FeatureFormView/FeatureFormView.swift

`FeatureFormView` - Remove barcode check

---

Sources/ArcGISToolkit/Components/FeatureFormView/ClearButton.swift
Sources/ArcGISToolkit/Resources/en.lproj/Localizable.strings

Fix accessibility label of clear button

---

Sources/ArcGISToolkit/Components/FloorFilter/FloorFilter.swift

Verified scene functionality using Calypso test data.

`FloorFilter` - Doc update

---

Sources/ArcGISToolkit/Components/Augmented Reality/WorldScaleSceneView.swift

Related to https://github.com/Esri/arcgis-maps-sdk-swift-toolkit/pull/646.

AR: Update modifier parameter name

---

Sources/ArcGISToolkit/Components/FeatureFormView/Subviews/Inputs/DateTimeInput.swift

`FeatureFormView` - Document issue

---

Tests/ArcGISToolkitTests/CertificatePickerViewModelTests.swift

Closes/Related #245 
This test has 5 logged failures at line 34 since we began running Toolkit dailies.
Ran 100 times without failure with these changes applied.

Repair `CertificatePickerViewModelTests` - `testViewModel`

---

Examples/Examples/FeatureFormExampleView.swift
Sources/ArcGISToolkit/Components/FeatureFormView/FeatureFormView.swift
Sources/ArcGISToolkit/Documentation.docc/Resources/FeatureFormView/FeatureFormViewStep2.swift
Sources/ArcGISToolkit/Documentation.docc/Resources/FeatureFormView/FeatureFormViewStep3.swift
Sources/ArcGISToolkit/Documentation.docc/Resources/FeatureFormView/FeatureFormViewStep4.swift
Sources/ArcGISToolkit/Documentation.docc/Resources/FeatureFormView/FeatureFormViewStep5.swift
Sources/ArcGISToolkit/Documentation.docc/Resources/FeatureFormView/FeatureFormViewStep6.swift
Sources/ArcGISToolkit/Documentation.docc/Resources/FeatureFormView/FeatureFormViewStep7.swift

`FeatureFormView` - Add form submission errors to example, tutorial

---

JobManagerExample/JobManagerExample/JobManagerExampleView.swift
Sources/ArcGISToolkit/Components/FloorFilter/SiteAndFacilitySelector.swift
Sources/ArcGISToolkit/Components/Scalebar/Scalebar.swift

Addresses a few new warnings after bumping to iOS 16.
There's another warning within the Floor Filter that I'll address separately as it's looking to be more involved.

Address new warnings

---

AuthenticationExample/AuthenticationExample/HomeView.swift
Examples/ExamplesApp/Examples.swift
Test Runner/Test Runner/Tests.swift

Removes the three remaining deprecated `NavigationView`s in favor of `NavigationStack`s.

Remove remaining `NavigationView`s

---

Sources/ArcGISToolkit/Common/AttachmentPreview.swift
Sources/ArcGISToolkit/Common/AttachmentsFeatureElementView.swift

Ref Apollo 408
Deleted attachments are now reflected in the preview display.

`FeatureFormView` - Revise attachment deletion

---

Sources/ArcGISToolkit/Common/AttachmentPreview.swift
Sources/ArcGISToolkit/Components/FeatureFormView/AttachmentHelpers/AttachmentImportMenu.swift
Sources/ArcGISToolkit/Resources/en.lproj/Localizable.strings

`FeatureFormView` - Localize latest strings

---

Sources/ArcGISToolkit/Common/AttachmentsFeatureElementView.swift

`FeatureFormView` - Evaluate expressions on attachment add/delete

---

Sources/ArcGISToolkit/Common/AttachmentModel.swift
Sources/ArcGISToolkit/Common/AttachmentPreview.swift

`FeatureFormView` - Remove `fileURL` workaround

---

Test Runner/UI Tests/FormViewTests.swift

`FeatureFormView` - Mark test crashes as expected

---

Sources/ArcGISToolkit/Common/ThumbnailView.swift
Test Runner/Test Runner/TestViews/FeatureFormTestView.swift
Test Runner/UI Tests/FormViewTests.swift

`FeatureFormView` - Add test case 8.1 implementation

---

Sources/ArcGISToolkit/Components/FeatureFormView/AttachmentHelpers/AttachmentImportMenu.swift
Sources/ArcGISToolkit/Resources/en.lproj/Localizable.strings

Updates the titles of the attachment import menus.
Apollo 656

Update Attachment import menu titles

---

Sources/ArcGISToolkit/Components/FeatureFormView/AttachmentHelpers/AttachmentImportMenu.swift

`FeatureFormView` - Add issue ref to `AttachmentImportMenu`

---

Sources/ArcGISToolkit/Documentation.docc/Resources/WorldScaleSceneView/WorldScaleSceneViewStep1.swift
Sources/ArcGISToolkit/Documentation.docc/Resources/WorldScaleSceneView/WorldScaleSceneViewStep2.swift
Sources/ArcGISToolkit/Documentation.docc/Resources/WorldScaleSceneView/WorldScaleSceneViewStep3.swift
Sources/ArcGISToolkit/Documentation.docc/Resources/WorldScaleSceneView/WorldScaleSceneViewStep5.swift
Sources/ArcGISToolkit/Documentation.docc/Resources/WorldScaleSceneView/WorldScaleSceneViewStep6.swift
Sources/ArcGISToolkit/Documentation.docc/Resources/WorldScaleSceneView/WorldScaleSceneViewStep7.swift
Sources/ArcGISToolkit/Documentation.docc/Tutorials/WorldScaleSceneViewTutorial.tutorial

Adds missing import and variable declarations to the `WorldScaleSceneView` tutorial.

AR: Update `WorldScaleSceneView` tutorial

---

Examples/ExamplesApp/Info.plist
Sources/ArcGISToolkit/Components/FeatureFormView/AttachmentHelpers/AttachmentCameraController.swift
Sources/ArcGISToolkit/Components/FeatureFormView/AttachmentHelpers/AttachmentImportMenu.swift
Sources/ArcGISToolkit/Components/FeatureFormView/AttachmentHelpers/AttachmentPhotoPicker.swift
Sources/ArcGISToolkit/Components/FeatureFormView/FeatureFormView.swift

`FeatureFormView` - Add video attachment support

---

Sources/ArcGISToolkit/Components/FeatureFormView/AttachmentHelpers/AttachmentImportData.swift
Sources/ArcGISToolkit/Components/FeatureFormView/AttachmentHelpers/AttachmentImportMenu.swift
Sources/ArcGISToolkit/Components/FeatureFormView/AttachmentHelpers/AttachmentPhotoPicker.swift

`FeatureFormView` - Use preferred filename extension for imported gallery items

---

Sources/ArcGISToolkit/Common/AttachmentModel.swift

Adds support for the `audio` type of `FormAttachment`.

Support Audio Thumbnail in FeatureForm attachments

---

Examples/Examples.xcodeproj/project.pbxproj
Examples/Examples/OfflineMapAreasExampleView.swift
Examples/ExamplesApp/Examples.swift
Sources/ArcGISToolkit/Components/OfflineMapAreasView/OfflineMapAreasView.swift
Sources/ArcGISToolkit/Components/OfflineMapAreasView/PreplannedListItemView.swift
Sources/ArcGISToolkit/Components/OfflineMapAreasView/PreplannedMapModel.swift
Sources/ArcGISToolkit/Components/OfflineMapAreasView/Utilities/LoadableImageView.swift

List preplanned map areas

---

Examples/Examples/FeatureFormExampleView.swift
Sources/ArcGISToolkit/Documentation.docc/Resources/FeatureFormView/FeatureFormViewStep1.swift
Sources/ArcGISToolkit/Documentation.docc/Resources/FeatureFormView/FeatureFormViewStep10.swift
Sources/ArcGISToolkit/Documentation.docc/Resources/FeatureFormView/FeatureFormViewStep11.swift
Sources/ArcGISToolkit/Documentation.docc/Resources/FeatureFormView/FeatureFormViewStep12.swift
Sources/ArcGISToolkit/Documentation.docc/Resources/FeatureFormView/FeatureFormViewStep13.swift
Sources/ArcGISToolkit/Documentation.docc/Resources/FeatureFormView/FeatureFormViewStep14.swift
Sources/ArcGISToolkit/Documentation.docc/Resources/FeatureFormView/FeatureFormViewStep15.swift
Sources/ArcGISToolkit/Documentation.docc/Resources/FeatureFormView/FeatureFormViewStep16.swift
Sources/ArcGISToolkit/Documentation.docc/Resources/FeatureFormView/FeatureFormViewStep17.swift
Sources/ArcGISToolkit/Documentation.docc/Resources/FeatureFormView/FeatureFormViewStep18.swift
Sources/ArcGISToolkit/Documentation.docc/Resources/FeatureFormView/FeatureFormViewStep2.swift
Sources/ArcGISToolkit/Documentation.docc/Resources/FeatureFormView/FeatureFormViewStep3.swift
Sources/ArcGISToolkit/Documentation.docc/Resources/FeatureFormView/FeatureFormViewStep4.swift
Sources/ArcGISToolkit/Documentation.docc/Resources/FeatureFormView/FeatureFormViewStep5.swift
Sources/ArcGISToolkit/Documentation.docc/Resources/FeatureFormView/FeatureFormViewStep8.swift
Sources/ArcGISToolkit/Documentation.docc/Resources/FeatureFormView/FeatureFormViewStep9.swift
Sources/ArcGISToolkit/Documentation.docc/Tutorials/FeatureFormViewTutorial.tutorial

`FeatureFormView` - Revise example level error handling for attachments

---

Sources/ArcGISToolkit/Components/FeatureFormView/AttachmentHelpers/AttachmentCameraController.swift
Sources/ArcGISToolkit/Components/FeatureFormView/AttachmentHelpers/AttachmentImportError.swift
Sources/ArcGISToolkit/Components/FeatureFormView/AttachmentHelpers/AttachmentImportMenu.swift
Sources/ArcGISToolkit/Components/FeatureFormView/AttachmentHelpers/AttachmentImportState.swift
Sources/ArcGISToolkit/Components/FeatureFormView/AttachmentHelpers/AttachmentPhotoPicker.swift
Sources/ArcGISToolkit/Resources/en.lproj/Localizable.strings

`FeatureFormView` - Revise internal error handling during attachment import

---

Sources/ArcGISToolkit/Components/FeatureFormView/AttachmentHelpers/AttachmentImportMenu.swift

This simply refactors `AttachmentImportMenu` such that all of the localized strings are together.

`FeatureFormView` - Centralize `AttachmentImportMenu` localized resources

---

Sources/ArcGISToolkit/Documentation.docc/Tutorials/FeatureFormViewTutorial.tutorial

`FeatureFormView` - Fix tutorial code highlighting

---

Sources/ArcGISToolkit/Components/FeatureFormView/Subviews/Inputs/Other/InputFooter.swift
Sources/ArcGISToolkit/Resources/en.lproj/Localizable.strings
Test Runner/Test Runner/TestViews/FeatureFormTestView.swift
Test Runner/UI Tests/FormViewTests.swift

`FeatureFormView` - Consume `FieldFormElement.hasValueExpression`

---

OfflineMapAreasExample/OfflineMapAreasExample/OfflineMapAreasExampleView.swift
Sources/ArcGISToolkit/Components/OfflineMapAreasView/OfflineMapAreasView.MapViewModel.swift
Sources/ArcGISToolkit/Components/OfflineMapAreasView/OfflineMapAreasView.swift
Sources/ArcGISToolkit/Components/OfflineMapAreasView/PreplannedListItemView.swift
Sources/ArcGISToolkit/Components/OfflineMapAreasView/PreplannedMapModel.swift
Tests/ArcGISToolkitTests/PreplannedMapModelStatusTests.swift
Tests/ArcGISToolkitTests/PreplannedMapModelTests.swift

Feedback for [Download Preplanned Map Areas PR](https://github.com/Esri/arcgis-maps-sdk-swift-toolkit/pull/745).
Please merge when you approve @des12437.

Feedback for Download Preplanned Map Areas PR

---

Test Runner/UI Tests/FormViewTests.swift

`FeatureFormView` - Re-enable crashing tests

---

Sources/ArcGISToolkit/Components/FeatureFormView/AttachmentHelpers/AttachmentImportError.swift
Sources/ArcGISToolkit/Components/FeatureFormView/AttachmentHelpers/AttachmentImportMenu.swift
Sources/ArcGISToolkit/Resources/en.lproj/Localizable.strings

`FeatureFormView` - Cap new attachments at 50 MB

---

Sources/ArcGISToolkit/Extensions/ArcGIS/AttachmentHelpers/AttachmentsFormElement.swift

https://github.com/Esri/arcgis-maps-sdk-swift-toolkit/pull/758/files#r1649264601

Remove unneeded cast

---

Sources/ArcGISToolkit/Common/AttachmentPreview.swift

`AttachmentPreview` - Show partial cell

---

Sources/ArcGISToolkit/Utility/Carousel.swift

`FeatureFormView` - Repair attachment rename

---

Sources/ArcGISToolkit/Components/FeatureFormView/FeatureFormView.swift

`FeatureFormView` - Ignore `AttachmentsFormElement`

---

Sources/ArcGISToolkit/Components/FeatureFormView/AttachmentHelpers/AttachmentCameraController.swift
Sources/ArcGISToolkit/Components/FeatureFormView/AttachmentHelpers/AttachmentImportData.swift
Sources/ArcGISToolkit/Components/FeatureFormView/AttachmentHelpers/AttachmentImportMenu.swift
Sources/ArcGISToolkit/Components/FeatureFormView/AttachmentHelpers/AttachmentPhotoPicker.swift

`FeatureFormView` - Standardize scheme for new attachment filenames

---

Sources/ArcGISToolkit/Common/AttachmentModel.swift
Sources/ArcGISToolkit/Common/AttachmentPreview.swift
Sources/ArcGISToolkit/Common/AttachmentsFeatureElementView.swift

`AttachmentsFeatureElementView` - Animate attachment add/delete

---

Examples/Examples/FeatureFormExampleView.swift
Sources/ArcGISToolkit/Common/AttachmentModel.swift
Sources/ArcGISToolkit/Common/AttachmentPreview.swift
Sources/ArcGISToolkit/Common/AttachmentsFeatureElementView.swift
Sources/ArcGISToolkit/Components/FeatureFormView/AttachmentHelpers/AttachmentImportMenu.swift
Sources/ArcGISToolkit/Extensions/ArcGIS/AttachmentHelpers/AttachmentsFeatureElement.swift
Sources/ArcGISToolkit/Extensions/ArcGIS/AttachmentHelpers/FeatureAttachment.swift
Tests/ArcGISToolkitTests/AttachmentsFeatureElementDisplayTypeTests.swift
Tests/ArcGISToolkitTests/FeatureAttachmentKindTests.swift

Addresses the following warnings:

Address build warnings

---

Sources/ArcGISToolkit/Components/FeatureFormView/AttachmentHelpers/AttachmentCameraController.swift

Re: https://github.com/Esri/arcgis-maps-sdk-swift-toolkit/pull/801#discussion_r1674378809

Resolve newly introduced warnings

---

Test Runner/Test Runner/TestViews/AttachmentCameraControllerTestView.swift

Fix build error in test

---

Sources/ArcGISToolkit/Components/FeatureFormView/AttachmentHelpers/AttachmentImportError.swift
Sources/ArcGISToolkit/Components/FeatureFormView/AttachmentHelpers/AttachmentImportMenu.swift

`AttachmentsFeatureElementView` - Use updated `addAttachment` API

---

Sources/ArcGISToolkit/Components/FeatureFormView/FeatureFormView.swift

`FeatureFormView` - Vertically center initial progress indicator

---

Sources/ArcGISToolkit/Components/FeatureFormView/AttachmentHelpers/AttachmentCameraController.swift

`AttachmentsFeatureElementView` - Capture new photos in JPEG

---

Test Runner/UI Tests/AttachmentCameraControllerTests.swift

Fix `AttachmentCameraControllerTests.testOnCameraCaptureModeChanged()`

---

Sources/ArcGISToolkit/Components/Scalebar/ScalebarViewModel.swift

`Scalebar` - Guard against NaN `unitsPerPoint`

---

Sources/ArcGISToolkit/Components/Authentication/CertificatePickerViewModifier.swift
Sources/ArcGISToolkit/Components/FeatureFormView/Subviews/Inputs/ComboBoxInput.swift
Sources/ArcGISToolkit/Components/Popups/MediaPopupElementView.swift
Sources/ArcGISToolkit/Extensions/ArcGIS/FloorFacility.swift
Sources/ArcGISToolkit/Extensions/ArcGIS/FloorLevel.swift
Sources/ArcGISToolkit/Extensions/ArcGIS/FloorSite.swift
Sources/ArcGISToolkit/Extensions/ArcGIS/PopupElement.swift

Reference #777 
If any of these conformances are ever added in the SDK we should still get a new warning about it.

Resolve extended conformance warnings

---

Sources/ArcGISToolkit/Common/AttachmentsFeatureElementView.swift
Sources/ArcGISToolkit/Components/Popups/FieldsPopupElementView.swift
Sources/ArcGISToolkit/Components/Popups/MediaPopupElementView.swift
Sources/ArcGISToolkit/Extensions/SwiftUI/DisclosureGroup.swift

Fix `DisclosureGroup` arrow padding for iOS

---

Sources/ArcGISToolkit/Components/Offline/OfflineMapAreasView.MapViewModel.swift
Sources/ArcGISToolkit/Components/Offline/OfflineMapAreasView.swift
Sources/ArcGISToolkit/Components/Offline/PreplannedListItemView.swift
Sources/ArcGISToolkit/Components/Offline/PreplannedMapModel.swift
Sources/ArcGISToolkit/Components/Offline/Utilities/LoadableImageView.swift
Tests/ArcGISToolkitTests/PreplannedMapModelTests.swift

Resolves concurrency warnings after merging `v.next` into this branch.

Offline: Resolve concurrency warnings

---

Sources/ArcGISToolkit/Components/FeatureFormView/FeatureFormView.swift
Sources/ArcGISToolkit/Components/FeatureFormView/Subviews/TextFormElementView.swift
Sources/ArcGISToolkit/Utility/MarkdownView.swift

`FeatureFormView` - Support `TextFormElement`

---

Test Runner/Test Runner/TestViews/FeatureFormTestView.swift
Test Runner/UI Tests/FormViewTests.swift

Apollo 808
- Adds FeatureFormView test cases 10.1 - 10.2
- Test case 10.3 needs to be implemented as an IC test at a later time (Apollo 872)

`FeatureFormview` - `TextFormElement` UI tests

---

Test Runner/UI Tests/FormViewTests.swift

Test data was fixed, updating tests accordingly.

Fix `FeatureFormViewTests.testCase_10_1()`

---

Test Runner/UI Tests/FormViewTests.swift

Stabilize `FeatureFormViewTests.testCase_8_1`

---

Examples/Examples/FeatureFormExampleView.swift
Sources/ArcGISToolkit/Components/FeatureFormView/FeatureFormView.swift
Sources/ArcGISToolkit/Documentation.docc/Resources/FeatureFormView/FeatureFormViewStep11.swift
Sources/ArcGISToolkit/Documentation.docc/Resources/FeatureFormView/FeatureFormViewStep12.swift
Sources/ArcGISToolkit/Documentation.docc/Resources/FeatureFormView/FeatureFormViewStep13.swift
Sources/ArcGISToolkit/Documentation.docc/Resources/FeatureFormView/FeatureFormViewStep14.swift
Sources/ArcGISToolkit/Documentation.docc/Resources/FeatureFormView/FeatureFormViewStep15.swift
Sources/ArcGISToolkit/Documentation.docc/Resources/FeatureFormView/FeatureFormViewStep16.swift
Sources/ArcGISToolkit/Documentation.docc/Resources/FeatureFormView/FeatureFormViewStep17.swift
Sources/ArcGISToolkit/Documentation.docc/Resources/FeatureFormView/FeatureFormViewStep18.swift

Update feature form definition access

---

Sources/ArcGISToolkit/Components/Popups/PopupView.swift

`PopupView.init(popup:isPresented:)` doc fix

---

Sources/ArcGISToolkit/Components/Offline/OfflineMapAreasView.swift

`swift/issues/5977`
Use b95fe18073bc4f7788f0375af2bb445e for testing an Offline disabled web map

Offline: Add logic to handle offline disabled

---

Examples/Examples/FeatureFormExampleView.swift
Sources/ArcGISToolkit/Documentation.docc/Resources/FeatureFormView/FeatureFormViewStep12.swift
Sources/ArcGISToolkit/Documentation.docc/Resources/FeatureFormView/FeatureFormViewStep13.swift
Sources/ArcGISToolkit/Documentation.docc/Resources/FeatureFormView/FeatureFormViewStep14.swift
Sources/ArcGISToolkit/Documentation.docc/Resources/FeatureFormView/FeatureFormViewStep15.swift
Sources/ArcGISToolkit/Documentation.docc/Resources/FeatureFormView/FeatureFormViewStep16.swift
Sources/ArcGISToolkit/Documentation.docc/Resources/FeatureFormView/FeatureFormViewStep17.swift
Sources/ArcGISToolkit/Documentation.docc/Resources/FeatureFormView/FeatureFormViewStep18.swift
Test Runner/Test Runner/TestViews/FeatureFormTestView.swift

`FeatureFormView` - Update example usage

---

OfflineMapAreasExample/OfflineMapAreasExample/OfflineMapAreasExampleView.swift
Sources/ArcGISToolkit/Components/Offline/OfflineMapAreasView.MapViewModel.swift
Sources/ArcGISToolkit/Components/Offline/OfflineMapAreasView.swift

- Moves user notification authorization logic from the offline component and places it at the app level

Offline: Move user notification authorization to app level

---

Test Runner/UI Tests/FormViewTests.swift

Temporarily disable `FeatureFormViewTests`

---

Sources/ArcGISToolkit/Common/CodeScanner.swift
Sources/ArcGISToolkit/Common/FlashlightButton.swift

After rebasing the visionOS branch with v.next I got some errors or warnings related to visionOS so I fixed those.

Fix build errors or warnings in visionOS branch

---

Tests/ArcGISToolkitTests/LocatorSearchSourceTests.swift
Tests/ArcGISToolkitTests/SmartLocatorSearchSourceTests.swift

Fixes today's test build failures after migrating to Swift 6
Followup to #883

Mark search source tests `@MainActor`

---

Sources/ArcGISToolkit/Common/CodeScanner.swift

`CodeScanner` - Revise device rotation handling

---

Sources/ArcGISToolkit/Common/CodeScanner.swift

`CodeScanner` - Rotation handling revision

---

Sources/ArcGISToolkit/Common/CodeScanner.swift

Fix visionOS build

---

Test Runner/UI Tests/FormViewTests.swift

Re-enable `FeatureFormViewTests/testCase_7_1`

---

Test Runner/UI Tests/FormViewTests.swift

Re-enable `FeatureFormViewTests/testCase_3_6`

---

Sources/ArcGISToolkit/Components/FeatureFormView/Subviews/Inputs/ComboBoxInput.swift
Sources/ArcGISToolkit/Resources/en.lproj/Localizable.strings
Test Runner/Test Runner/TestViews/FeatureFormTestView.swift
Test Runner/UI Tests/FormViewTests.swift

Apollo 839
https://github.com/user-attachments/assets/4ed991a6-e349-4c54-8a0b-96118b10880f

`FeatureFormView` / `ComboBoxInput` - Show unsupported values

---

Sources/ArcGISToolkit/Components/FeatureFormView/Subviews/Inputs/Other/InputFooter.swift

`FeatureFormView`/`InputFooter` - Handle all possible numeric domain field types

---

Sources/ArcGISToolkit/Components/FeatureFormView/FeatureFormView.swift

`FeatureFormView` - 200.6 doc updates

---

Sources/ArcGISToolkit/Utility/MarkdownView.swift

`MarkdownView` - Add soft break support, stop unsupported element crashes

---

Examples/Examples/FlyoverExampleView.swift
Examples/Examples/TableTopExampleView.swift
Examples/Examples/WorldScaleExampleView.swift
Examples/ExamplesApp/Examples.swift
Sources/ArcGISToolkit/Components/Augmented Reality/FlyoverSceneView.swift
Sources/ArcGISToolkit/Components/Augmented Reality/TableTopSceneView.swift
Sources/ArcGISToolkit/Components/Augmented Reality/Utilities/CalibrationView.swift
Sources/ArcGISToolkit/Components/Augmented Reality/WorldScaleSceneView.swift

Drop AR components from Catalyst

---

Sources/ArcGISToolkit/Components/Compass/Compass.swift
Sources/ArcGISToolkit/Components/Compass/Needle.swift

`Compass` - Fix right-to-left rendering

---

Sources/ArcGISToolkit/Components/UtilityNetworkTrace/UtilityNetworkTrace.swift

Closes #947 
Aligns the component with the following design spec:
> By default, the control will zoom to the trace result area. This feature can be disabled by setting the AutoZoomToTraceResults property of the control to false.
Behavioral changes:
- When a trace completes, the viewpoint is automatically set to the extent of the trace's results.
- This can still be disabled by the user under the "Advanced Options" when creating a trace. 
- While browsing the list of completed traces, the viewpoint now changes to reflect the extent of the currently selected trace.
https://github.com/user-attachments/assets/577a0aa1-59d6-441c-bd2b-28111196dba4

`UtilityNetworkTrace` - Auto zoom to trace extent

---

Sources/ArcGISToolkit/Components/FeatureFormView/Subviews/Inputs/ComboBoxInput.swift

Replaces the List icon with a Chevron, per the UI design review recommendations.
For Apollo 964

Combo box UI improvements

---

Sources/ArcGISToolkit/Components/FeatureFormView/Subviews/Inputs/TextInput.swift

Set line limit to 5 and the minimum height to 100 for multi-line text inputs.
For Apollo 961

Text UI improvements

---

Examples/Examples/FloatingPanelExampleView.swift

`FloatingPanelExampleView` - Tweak initial viewpoint creation

---

Examples/Examples.xcodeproj/project.pbxproj
Examples/ExamplesApp/Examples.swift
Sources/ArcGISToolkit/Components/Compass/Compass.swift
Sources/ArcGISToolkit/Components/Compass/Needle.swift
Tests/ArcGISToolkitTests/CompassTests.swift

Add visionOS support to `Compass`

---

Examples/Examples.xcodeproj/project.pbxproj
Examples/ExamplesApp/Examples.swift
Sources/ArcGISToolkit/Components/FloorFilter/FloorFilter.swift
Sources/ArcGISToolkit/Components/FloorFilter/FloorFilterAutomaticSelectionMode.swift
Sources/ArcGISToolkit/Components/FloorFilter/FloorFilterSelection.swift
Sources/ArcGISToolkit/Components/FloorFilter/FloorFilterViewModel.swift
Sources/ArcGISToolkit/Components/FloorFilter/LevelSelector.swift
Sources/ArcGISToolkit/Components/FloorFilter/SiteAndFacilitySelector.swift
Sources/ArcGISToolkit/Utility/EsriBorderViewModifier.swift
Tests/ArcGISToolkitTests/FloorFilterViewModelTests.swift

Swift #6156
Here is a picture of it but I highly recommend testing it out in the examples app:

Add visionOS support to `FloorFilter`

---

Examples/Examples/FeatureFormExampleView.swift
Sources/ArcGISToolkit/Components/FeatureFormView/FeatureFormView.swift
Sources/ArcGISToolkit/Components/FeatureFormView/Subviews/UtilityNetworkAssociationFormElementView.swift
Sources/ArcGISToolkit/Extensions/ArcGIS/ArcGISFeature.swift

Prototype `UtilityNetworkAssociationFormElementView`

---

OfflineMapAreasExample/OfflineMapAreasExample/OfflineMapAreasExampleView.swift
Sources/ArcGISToolkit/Components/Offline/OfflineMapAreasView.MapViewModel.swift
Sources/ArcGISToolkit/Components/Offline/OfflineMapAreasView.swift

cleanup, move more into the model

---

Sources/ArcGISToolkit/Components/FeatureFormView/FeatureFormView.swift
Sources/ArcGISToolkit/Components/FeatureFormView/Subviews/UtilityNetworkAssociationFormElementView.swift

| Before | After |
|---|---|
| <img src="https://github.com/user-attachments/assets/0308d9a4-c02c-418a-b63d-8da5fd3fca78"> | <img src="https://github.com/user-attachments/assets/0557aa10-28b9-43cf-abdd-4d06dfe0bb9f"> |

UtilityNetworkAssociationsFormElementView - Sync base prototype with high level design

---

Sources/ArcGISToolkit/Documentation.docc/Resources/FeatureFormView/FeatureFormViewStep10.swift
Sources/ArcGISToolkit/Documentation.docc/Resources/FeatureFormView/FeatureFormViewStep11.swift
Sources/ArcGISToolkit/Documentation.docc/Resources/FeatureFormView/FeatureFormViewStep12.swift
Sources/ArcGISToolkit/Documentation.docc/Resources/FeatureFormView/FeatureFormViewStep13.swift
Sources/ArcGISToolkit/Documentation.docc/Resources/FeatureFormView/FeatureFormViewStep14.swift
Sources/ArcGISToolkit/Documentation.docc/Resources/FeatureFormView/FeatureFormViewStep15.swift
Sources/ArcGISToolkit/Documentation.docc/Resources/FeatureFormView/FeatureFormViewStep16.swift
Sources/ArcGISToolkit/Documentation.docc/Resources/FeatureFormView/FeatureFormViewStep17.swift
Sources/ArcGISToolkit/Documentation.docc/Resources/FeatureFormView/FeatureFormViewStep18.swift
Sources/ArcGISToolkit/Documentation.docc/Resources/FeatureFormView/FeatureFormViewStep2.swift
Sources/ArcGISToolkit/Documentation.docc/Resources/FeatureFormView/FeatureFormViewStep3.swift
Sources/ArcGISToolkit/Documentation.docc/Resources/FeatureFormView/FeatureFormViewStep4.swift
Sources/ArcGISToolkit/Documentation.docc/Resources/FeatureFormView/FeatureFormViewStep5.swift
Sources/ArcGISToolkit/Documentation.docc/Resources/FeatureFormView/FeatureFormViewStep6.swift
Sources/ArcGISToolkit/Documentation.docc/Resources/FeatureFormView/FeatureFormViewStep7.swift
Sources/ArcGISToolkit/Documentation.docc/Resources/FeatureFormView/FeatureFormViewStep8.swift
Sources/ArcGISToolkit/Documentation.docc/Resources/FeatureFormView/FeatureFormViewStep9.swift

Apply FeatureFormExampleView changes to tutorial

---

Test Runner/UI Tests/FeatureFormViewTests.swift

Temporarily disable `FeatureFormViewTests` case 8.1

---

Sources/ArcGISToolkit/Components/Offline/OnDemand/OnDemandListItemView.swift
Sources/ArcGISToolkit/Components/Offline/OnDemand/OnDemandMapModel.swift

- cancel jobs
- show corrupted jobs in the list so they can be deleted

OfflineMapAreasView - OnDemand Cleanup

---

Sources/ArcGISToolkit/Components/Offline/OfflineManager.swift
Sources/ArcGISToolkit/Components/Offline/OfflineMapAreasView.swift
Sources/ArcGISToolkit/Components/Offline/OnDemand/OnDemandConfigurationView.swift
Sources/ArcGISToolkit/Components/Offline/OnDemand/OnDemandListItemView.swift
Sources/ArcGISToolkit/Components/Offline/OnDemand/OnDemandMapModel.swift
Sources/ArcGISToolkit/Components/Offline/OnDemand/OnDemandMetadataView.swift
Sources/ArcGISToolkit/Components/Offline/Preplanned/PreplannedListItemView.swift
Sources/ArcGISToolkit/Components/Offline/Preplanned/PreplannedMetadataView.swift
Sources/ArcGISToolkit/Components/Offline/Utilities/LoadableImageView.swift
Sources/ArcGISToolkit/Components/Offline/Utilities/URL+Offline.swift

On-Demand: Thumbnails

---

Sources/ArcGISToolkit/Components/Offline/OnDemand/OnDemandListItemView.swift
Sources/ArcGISToolkit/Components/Offline/Utilities/GaugeProgressViewStyle.swift

part of the work for UI design feedback

OfflineMapAreas: Consolidate code for gauge progress view

---

Sources/ArcGISToolkit/Components/Offline/OnDemand/OnDemandConfigurationView.swift

This seems to help with the pinching problem.

Offline: Try to prevent sheet from moving when interacting with the MapView.

---

Sources/ArcGISToolkit/Common/AttachmentsFeatureElementView.swift
Sources/ArcGISToolkit/Components/FeatureFormView/Subviews/Inputs/SwitchInput.swift

Makes some small improvements found during #1034 review.

Small `FeatureFormView` tweaks

---

Sources/ArcGISToolkit/Common/AttachmentPreview.swift
Sources/ArcGISToolkit/Components/FeatureFormView/AttachmentHelpers/AttachmentImportMenu.swift

Updates the attachment limit to 999MB

Update attachment limit to 999MB

---

Sources/ArcGISToolkit/Common/AttachmentPreview.swift
Sources/ArcGISToolkit/Components/Authentication/CertificatePickerViewModifier.swift
Sources/ArcGISToolkit/Components/Offline/OfflineMapAreaListItemView.swift
Sources/ArcGISToolkit/Components/Offline/OfflineMapAreaMetadataView.swift
Sources/ArcGISToolkit/Components/Offline/OfflineMapAreasView.swift
Sources/ArcGISToolkit/Components/Offline/OfflineMapViewModel.swift
Sources/ArcGISToolkit/Components/Offline/OnDemand/OnDemandConfigurationView.swift
Sources/ArcGISToolkit/Components/Offline/OnDemand/OnDemandListItemView.swift
Sources/ArcGISToolkit/Components/Offline/OnDemand/OnDemandMapModel.swift
Sources/ArcGISToolkit/Components/Offline/Preplanned/PreplannedListItemView.swift
Sources/ArcGISToolkit/Components/Offline/Utilities/CacheScale.swift
Sources/ArcGISToolkit/Extensions/Swift/LocalizedStringResource.swift
Sources/ArcGISToolkit/Extensions/Swift/String.swift
Sources/ArcGISToolkit/Extensions/SwiftUI/Button.swift
Sources/ArcGISToolkit/Extensions/SwiftUI/Text.swift
Sources/ArcGISToolkit/Resources/en.lproj/Localizable.strings

Localizes strings for the `OfflineMapAreasView` component.

Offline: localize strings

---

Sources/ArcGISToolkit/Components/Offline/OfflineManager.swift

Imports Combine in `OfflineManager.swift`.

Offline: Add import

---

Sources/ArcGISToolkit/Components/Offline/OfflineMapAreasView.swift

fix described here: https://stackoverflow.com/a/78947971

fix issue with state being reset when backgrounding

---

Sources/ArcGISToolkit/Components/Offline/OnDemand/OnDemandConfigurationView.swift

Remove one nested vstack, break instructions view out.

simplify on demand config view

---

Sources/ArcGISToolkit/Components/Offline/OfflineManager.swift
Sources/ArcGISToolkit/Components/Offline/OfflineMapAreaListItemView.swift
Sources/ArcGISToolkit/Components/Offline/OfflineMapAreaMetadataView.swift
Sources/ArcGISToolkit/Components/Offline/OfflineMapAreasView.swift
Sources/ArcGISToolkit/Components/Offline/OfflineMapInfo.swift
Sources/ArcGISToolkit/Components/Offline/OfflineMapViewModel.swift
Sources/ArcGISToolkit/Components/Offline/OnDemand/OnDemandConfigurationView.swift
Sources/ArcGISToolkit/Components/Offline/OnDemand/OnDemandListItemView.swift
Sources/ArcGISToolkit/Components/Offline/OnDemand/OnDemandMapModel.swift
Sources/ArcGISToolkit/Components/Offline/Preplanned/PreplannedListItemView.swift
Sources/ArcGISToolkit/Components/Offline/Utilities/LoadableImageView.swift
Sources/ArcGISToolkit/Extensions/Foundation/Error.swift
Sources/ArcGISToolkit/Extensions/SwiftUI/Button.swift

Fix various doc and formatting issues. For indentation change review, check "hide whitespace" box.
More comments below.

Offline: fix minor issues

---

Sources/ArcGISToolkit/Extensions/ArcGIS/AttachmentHelpers/AttachmentsFeatureElement.swift
Sources/ArcGISToolkit/Extensions/ArcGIS/AttachmentHelpers/AttachmentsFormElement.swift
Sources/ArcGISToolkit/Extensions/ArcGIS/AttachmentHelpers/AttachmentsPopupElement.swift
Sources/ArcGISToolkit/Extensions/ArcGIS/AttachmentHelpers/FeatureAttachment.swift
Sources/ArcGISToolkit/Extensions/ArcGIS/AttachmentHelpers/FormAttachment.swift
Sources/ArcGISToolkit/Extensions/ArcGIS/AttachmentHelpers/PopupAttachment.swift

The included types do not have a need to be public.

Make some types internal

---

OfflineMapAreasExample/OfflineMapAreasExample/OfflineMapAreasExampleApp.swift

Offline: Add doc for scene modifier

---

Sources/ArcGISToolkit/Components/Offline/OnDemand/OnDemandConfigurationView.swift

Unless you resize the selector view right before you hit the download button, the offline toolkit component was not creating the correct map area.

Offline: Configuration view not taking correct extent offline

---

Sources/ArcGISToolkit/Components/FeatureFormView/FeatureFormView.swift
Sources/ArcGISToolkit/Components/FeatureFormView/Subviews/FormFooter.swift

`FeatureFormView` - Catch and display `FeatureForm.finishEditing()` errors

---

Sources/ArcGISToolkit/Common/AttachmentsFeatureElementView.swift
Sources/ArcGISToolkit/Components/FeatureFormView/FormViewModel.swift
Sources/ArcGISToolkit/Components/FeatureFormView/InternalFeatureFormView.swift
Sources/ArcGISToolkit/Components/FeatureFormView/Subviews/Inputs/ComboBoxInput.swift
Sources/ArcGISToolkit/Components/FeatureFormView/Subviews/Inputs/DateTimeInput.swift
Sources/ArcGISToolkit/Components/FeatureFormView/Subviews/Inputs/Other/InputFooter.swift
Sources/ArcGISToolkit/Components/FeatureFormView/Subviews/Inputs/RadioButtonsInput.swift
Sources/ArcGISToolkit/Components/FeatureFormView/Subviews/Inputs/SwitchInput.swift
Sources/ArcGISToolkit/Components/FeatureFormView/Subviews/Inputs/TextInput.swift
Sources/ArcGISToolkit/Components/FeatureFormView/Subviews/UtilityAssociationsFormElementView.swift

`FeatureFormView` - Upgrade FormViewModel to the Observable macro

---

Sources/ArcGISToolkit/Components/JobManager/JobManager.swift

Fix-up json deprecation warnings related to `pull/6959`, `issue/6960`

Fix json deprecation warnings

---

Sources/ArcGISToolkit/Components/FeatureFormView/Subviews/FormElements/UtilityAssociationsFormElementView.swift
Test Runner/UI Tests/FeatureFormViewTests.swift

`FeatureFormView` - Use common `UtilityAssociationResultButton`

---

Sources/ArcGISToolkit/Components/FeatureFormView/FeatureFormView.swift

`FeatureFormView` - Refresh feature when opened via navigation

---

Sources/ArcGISToolkit/Utility/CredentialInputView.swift

Closes https://github.com/Esri/arcgis-maps-sdk-swift-toolkit/issues/1181

reset username and password while re-prompting

---

Sources/ArcGISToolkit/Components/FeatureFormView/Subviews/FormElements/GroupFormElementView.swift

Apollo 1278
See issue for current and proposed screenshots.

`FeatureFormView` - Revise `GroupFormElementView.Header` appearance

---

Test Runner/UI Tests/FeatureFormViewTests.swift

In response to failures in 7/8, 7/19 daily runs.

Add wait to FeatureFormViewTests.testCase_12_1

---

Sources/ArcGISToolkit/Common/AttachmentList.swift
Sources/ArcGISToolkit/Common/AttachmentModel.swift
Sources/ArcGISToolkit/Common/AttachmentPreview.swift
Sources/ArcGISToolkit/Common/AttachmentsFeatureElementView.swift
Sources/ArcGISToolkit/Extensions/ArcGIS/AttachmentHelpers/FeatureAttachment.swift

`FeatureFormView` - Cancel attachment load on form dismissal 

---

Sources/ArcGISToolkit/Common/CameraRequester.swift
Sources/ArcGISToolkit/Common/CodeScanner.swift
Sources/ArcGISToolkit/Components/FeatureFormView/AttachmentHelpers/AttachmentCameraController.swift
Sources/ArcGISToolkit/Components/FeatureFormView/AttachmentHelpers/AttachmentImportMenu.swift
Sources/ArcGISToolkit/Components/FeatureFormView/Subviews/Inputs/TextInput.swift
Test Runner/Test Runner/TestViews/AttachmentCameraControllerTestView.swift

Refactor CameraRequester to use Observation

---

Sources/ArcGISToolkit/Components/FeatureFormView/EmbeddedFeatureFormView.swift
Sources/ArcGISToolkit/Components/FeatureFormView/EmbeddedFeatureFormViewModel.swift
Sources/ArcGISToolkit/Components/FeatureFormView/FeatureFormView.swift
Sources/ArcGISToolkit/Components/FeatureFormView/Subviews/FormElements/GroupFormElementView.swift

- Closes #1284 
- Makes a few other optimizations

`FeatureFormView` - Refresh when root `FeatureForm` changes

---

Sources/ArcGISToolkit/Components/Offline/OfflineMapAreaListItemView.swift
Sources/ArcGISToolkit/Components/Offline/OfflineMapAreaMetadataView.swift
Sources/ArcGISToolkit/Components/Offline/OnDemand/OnDemandListItemView.swift
Sources/ArcGISToolkit/Components/Offline/OnDemand/OnDemandMapModel.swift
Sources/ArcGISToolkit/Components/Offline/Preplanned/PreplannedListItemView.swift
Sources/ArcGISToolkit/Components/Offline/Preplanned/PreplannedMapModel.swift
Tests/ArcGISToolkitTests/OnDemandMapModelTests.swift
Tests/ArcGISToolkitTests/PreplannedMapModelTests.swift

This came up in a meeting with a customer as something that was important.
<details>
<summary>Screenshots</summary> 
</details>
cc @dg0yal

Show size of preplanned map area

---

Examples/ExamplesApp/Examples.swift

Related to https://github.com/Esri/arcgis-maps-sdk-swift-toolkit/pull/1305.
Adds comment for changes in https://github.com/Esri/arcgis-maps-sdk-swift-toolkit/pull/1267.

Add navigation stack workaround comment
