Esri/arcgis-maps-sdk-swift-toolkit

- Examples/Examples.xcodeproj/project.pbxproj
I removed the Developer Team from the Examples project and modified the following values:
Version: "200.0.0-beta"
Bundle: "com.esri.arcgis-swift-sdk-toolkit-examples"
Is the bundle name OK?  For comparison, the Samples bundle is "com.esri.arcgis-swift-sdk-samples".
> Update version number, bundle, dev team

- README.md
Updates the link to the community forums which was still pointing at the iOS board.
> Beta - Fix forum link

- Sources/ArcGISToolkit/Components/UtilityNetworkTrace/UtilityNetworkTrace.swift
The initializer does not take a parameter named `activeDetent`.
> Removed orphaned doc

- Sources/ArcGISToolkit/Components/FloorFilter/SiteAndFacilitySelector.swift
Closes #229 
Leaving `userBackedOutOfSelectedSite` set `true` caused the computed binding above on line 121 to return `nil` when it shouldn't have. It was being left `true` because the `.onChange` modifier below at line 148 wasn't firing if the same site was selected as before.
> Floor Filter - Fix ability to reselect same site

- Documentation/OverviewMap/README.md
- Examples/Examples/OverviewMapExampleView.swift
- Sources/ArcGISToolkit/Components/OverviewMap.swift
Closes https://github.com/Esri/arcgis-maps-sdk-swift-toolkit/issues/225
This removes the `.map` modifier on `OverviewMap` and replaces it with a `map` argument on both `OverviewMap.forSceneView` and `OverviewMap.forMapView`. The argument defaults to `nil`, in which case the existing default map is used.
It also removes the unnecessary distinction between `customOverviewMapForMapView` and `customOverviewMapForSceneView` and replaces them with just one custom map: `customOverviewMap`.
> Fix OverviewMap warning

- Tests/ArcGISToolkitTests/SearchViewModelTests.swift
Some of the references to `Polygon` were not qualified when they needed to be, so they were resolving to the `Polygon` type in the Application Services framework. While I was at it, I made the geometries computed so that they don't stick around longer than necessary. We've also seen problems with re-using geometries.
> Fix build errors in `SearchViewModelTests.swift`

- Documentation/Search/README.md
- Package.swift
- Sources/ArcGISToolkit/Components/Popups/PopupMedia/Charts/ChartData.swift
- Sources/ArcGISToolkit/Components/Search/LocatorSearchSource.swift
- Sources/ArcGISToolkit/Components/Search/SearchSource.swift
- Sources/ArcGISToolkit/Components/Search/SmartLocatorSearchSource.swift
Use `Int` instead of `Int32` in the `SearchSource` related types.
> Latest API changes

- Sources/ArcGISToolkit/Components/Bookmarks/Bookmarks.swift
When building `v.next` with the latest daily binaries, a build error arises in `Bookmarks.swift` that isn't present with building with source.
This area hasn't changed since beta and so I presume the compiler has become more strict in this area.
This can be tested by switching the SDK dependency to the Swift daily repo.
> Build fix for `Bookmarks`

- AuthenticationExample/AuthenticationExample/ProfileView.swift
- AuthenticationExample/AuthenticationExample/SignInView.swift
- Sources/ArcGISToolkit/Components/Authentication/AuthenticationManager.swift
- Made `AuthenticationManager .handleChallenges` function to take optional so reset challenge handlers
- Two views were not using the `@EnvironmentObject authenticator` so removed.
cc: @yo1995
> updated authentication example and auth manager extension

- Sources/ArcGISToolkit/Components/UtilityNetworkTrace/UtilityNetworkTrace.swift
- Sources/ArcGISToolkit/Components/UtilityNetworkTrace/UtilityNetworkTraceViewModel.swift
Closes #269 
- Refactors `UtilityNetworkTraceViewModel.addStartingPoint(at:mapPoint:with:)` into a new func `addStartingPoints(at:mapPoint:with:)` where we only run an identify operation on the layers within the utility network.
- The method is renamed to a plural form because it has the potential to add multiple starting points.
> Utility Network Trace - Improve identification

- Sources/ArcGISToolkit/Components/Scalebar/Scalebar.swift
@yo1995 noticed this build error when building with the latest daily and I was able to reproduce it using `3830.14`.
> Fix build error

- Documentation/Bookmarks/README.md
- Examples/Examples/BookmarksExampleView.swift
- Sources/ArcGISToolkit/Components/Bookmarks/Bookmarks.swift
> [Bookmarks] Rename init parameter, update example usage

- Examples/ExamplesApp/Info.plist
Thanks to @yo1995 and [samples #149](https://github.com/Esri/arcgis-maps-sdk-swift-samples/pull/149) I realized we we're experiencing the same warning in the toolkit's examples app.
This PR simply adds the one entry to resolve that warning
> Fix warning - "Info.plist contained no UIScene configuration dictionary"

- Documentation/Compass/README.md
- Sources/ArcGISToolkit/Components/Compass/Compass.swift
- Tests/ArcGISToolkitTests/CompassTests.swift
[See also](https://github.com/Esri/arcgis-maps-sdk-swift-toolkit/pull/286#discussion_r1156207860)
[Named after](https://developer.apple.com/documentation/swiftui/view/autocorrectiondisabled(_:))
> `Compass.automaticallyHides(_:)`-> `autoHideDisabled(_:)`

- Sources/ArcGISToolkit/Components/Popups/Attachments/AttachmentList.swift
- Sources/ArcGISToolkit/Extensions/Viewpoint.swift
I'm using the most recent 200.1 build. 
Fixes these warnings:
This enum needs to check for other cases.
The `LoadStatus` enum is now frozen so we don't need to check for new cases.
> Fix warnings

- Tests/ArcGISToolkitTests/AuthenticatorTests.swift
The toolkit is released with the closed-source SDK so we cannot use the `@testable` attribute.
> Fix `AuthenticatorTests` compile failure

- Examples/Examples/FloatingPanelExampleView.swift
- Sources/ArcGISToolkit/Components/FloatingPanel/FloatingPanel.swift
Related: Swift #3931
Presently, there is no animation when a floating panel is shown/hidden via its `$isPresented` parameter. This PR addresses that.
> [Floating Panel] Animate showing and hiding

- Documentation/Search/README.md
- Examples/Examples/SearchExampleView.swift
- Sources/ArcGISToolkit/Components/Search/SearchView.swift
- Sources/ArcGISToolkit/Components/Search/SearchViewModel.swift
Related #260 
- Adds a new `geoViewProxy` parameter to the search module. This is used to perform animated viewpoints now.
- In the example, a map view proxy is added to demonstrate usage of the new parameter.
> [Search] Add `geoViewProxy` parameter, support viewpoint animation

- Sources/ArcGISToolkit/Components/UtilityNetworkTrace/UtilityNetworkTraceViewModelTrace.swift
- Viewing feature results on a trace is broken as reported by @mhdostal 
- Introduced in https://github.com/Esri/arcgis-maps-sdk-swift-toolkit/pull/234/commits/c37d8e0c45dd828a88af2e32f026e25504138ceb
https://user-images.githubusercontent.com/16397058/231575415-7b9a5af9-9fe1-4cd9-a408-d4276ffd4612.mp4
> [Utility Network] Fix feature results view

- Documentation/UtilityNetworkTrace/README.md
- Examples/Examples/UtilityNetworkTraceExampleView.swift
- Sources/ArcGISToolkit/Components/UtilityNetworkTrace/UtilityNetworkTrace.swift
- Sources/ArcGISToolkit/Components/UtilityNetworkTrace/UtilityNetworkTraceViewModel.swift
Related #260 
- The `viewPoint` parameter is renamed to `screenPoint` to match the new default names provided when adding the `onSingleTapGesture` to a geo view.
- The proxy is no longer a binding property. There was no need for it be a binding and it simplifies the usage.
- In the sample, the map is now simple a `@State` property rather than a `MapDataModel`
- Tapping "Zoom To" either on a completed trace name or starting point will perform an animated zoom to the proper extent.
> [UN Trace] - Rename `viewPoint` to `screenPoint`, support viewpoint animation, make proxy a non-binding property

- Documentation/Compass/README.md
- Examples/Examples/CompassExampleView.swift
- Sources/ArcGISToolkit/Components/Compass/Compass.swift
- Tests/ArcGISToolkitTests/CompassTests.swift
Given a mixture of feedback from Phil R. and Mark on #298 I propose the following Compass API:
Public initializer:
```swift
Compass(rotation: Double?, mapViewProxy: MapViewProxy)
```
Internal initializer:
```swift
Compass(heading: Double, mapViewProxy: MapViewProxy? = nil)
```
- In the public initializer the proxy isn't nullable as the majority of users will want animation. In the internal initializer, the proxy is nullable to keep the compass testable.
Thoughts appreciated from @rolson, @philium 
Additional note:
- Because heading is no longer a binding, when `shouldHide` was accessed from `.onChange(of: heading)` and the change was triggered by snap-to-north, `heading` would still have the pre-snap value causing `shouldHide` to compute incorrectly. For this reason, `shouldHide` became …
> [Compass] Re-think API

- Documentation/Compass/README.md
- Examples/Examples/CompassExampleView.swift
- Sources/ArcGISToolkit/Components/Compass/Compass.swift
- Tests/ArcGISToolkitTests/CompassTests.swift
- Closes #295 
- In Swift 3882, a conclusion was reached that toolkit components should take proxy parameters where needed.
- In the case of the Compass, a map view proxy is used to animate the map view's heading to zero.
- SceneView compass animations will not be supported.
- See also #260
> [Compass] Remove `action` parameter, add `mapViewProxy` parameter, support rotation animation

- Sources/ArcGISToolkit/Components/FloorFilter/FloorFilter.swift
- Closes #307 
- Viewpoint changes should always be reported to the model, despite whether the site and facility selector is open or not.
> [Floor Filter] Fix automatic selection in compact width

- Documentation/Bookmarks/README.md
- Examples/Examples/BookmarksExampleView.swift
- Fixes behavior where the animation would either sometimes not start or get cutoff. I believe the `Task` may have been getting canceled mid animation.
- The solution is to move the animation to a task modifier on the map view.
> [Bookmarks] Fix animation in example

- Sources/ArcGISToolkit/Components/Authentication/TrustHostViewModifier.swift
While recently reviewing nearby code @philium suggested this should use `onAppear` as no asynchronous work is performed within.
This change can be tested on branch "ryan2" by opening the regular toolkit sample app, GeoView -> Authentication -> Multiple token secured resources
> [Authenticator] Replace `task` with `onAppear`

- Sources/ArcGISToolkit/Components/Authentication/TrustHostViewModifier.swift
While recently reviewing nearby code @philium suggested we might consider changing the language of the trust host modifier:
> "Dangerous: Allow Connection" is a really odd name for a button. It seems like the button should just be named "Allow" and the part about it being dangerous should be in the alert's message.
"Continue" is another possibility for the button that I would consider.
> [Authenticator] Update language in the trust host modifier

- Documentation/Compass/README.md
- Sources/ArcGISToolkit/Components/Compass/Compass.swift
- Tests/ArcGISToolkitTests/CompassTests.swift
Closes #326 
This PR adds back SceneView support for Compass. Because there is the ability to use `Viewpoint`s or the the different CameraController types to control  SceneView, a custom _action_ is provided via a view modifier. This allows clients to do whatever is best for their implementation of SceneView instead of relying on a default implementation in the Compass.  ~The `mapViewProxy` argument for the initializer is now optional (and defaults to `nil).~
In order to prevent the confusion with behavior if the proxy is nil, there are now two initializers:
```swift
init(rotation: Double?, mapViewProxy: MapViewProxy)
init(rotation: Double?, action: @escaping () -> Void)
```
The usage in a SceneView would be as follows (using the 2nd initializer, the one that takes an `action`):
```swift …
```
> SceneView support for Compass

- Documentation/BasemapGallery/README.md
A map property can no longer use the `@StateObject` property wrapper b/c `Map` no longer conforms to `ObservableObject`.
This PR can go into `main` because it applies to the current toolkit code.
> Update basemap gallery code snippet

- Documentation/BasemapGallery/README.md
- Examples/Examples/BasemapGalleryExampleView.swift
The existing demo usage doesn't provide the best results.
|   | Before | After |
|---|---|---|
| iPhone | ![iosBefore](https://github.com/Esri/arcgis-maps-sdk-swift-toolkit/assets/16397058/5d8e60d5-4cc7-4b5d-ab15-944fff94157c) | ![iosAfter](https://github.com/Esri/arcgis-maps-sdk-swift-toolkit/assets/16397058/3485fdd2-acc3-4641-9574-0faff555a7fd) |
| macOS | <img width="987" alt="catBefore" src="https://github.com/Esri/arcgis-maps-sdk-swift-toolkit/assets/16397058/1323b737-3b8d-4ba0-bbf3-f8a8248fa102"> | <img width="987" alt="catAfter" src="https://github.com/Esri/arcgis-maps-sdk-swift-toolkit/assets/16397058/8e54236d-f4e2-4040-bacf-58a0c6773143"> |
| iPad | ![iPadBefore](https://github.com/Esri/arcgis-maps-sdk-swift-toolkit/assets/16397058/d721ce2f-446c-4e96-9d8e-e1a73b8b736d) | …
> Updates Basemap Gallery sample usage

- Sources/ArcGISToolkit/Components/Search/SearchView.swift
- Sources/ArcGISToolkit/Utility/SearchField.swift
Related #7 
When a search suggestion or result is tapped, the keyboard remains focused, leaving less room for the map with pin(s) and signaling to the user more text entry is expected.
A common pattern pattern seems to be that the keyboard is hidden once a result or suggestion is tapped.
This PR changes the search component to follow that latter common pattern.
> [Search] Improve keyboard focus handling

- Sources/ArcGISToolkit/Components/Popups/PopupView.swift
- Sources/ArcGISToolkit/Resources/en.lproj/Localizable.strings
The ellipsis character (…) should be used instead of three dots (...) in localized strings.
> Use ellipsis character in localized strings

- Sources/ArcGISToolkit/Components/Authentication/CertificatePickerViewModifier.swift
- Sources/ArcGISToolkit/Components/Authentication/Login.swift
- Sources/ArcGISToolkit/Components/Authentication/TrustHostViewModifier.swift
- Sources/ArcGISToolkit/Components/BasemapGallery/BasemapGallery.swift
- Sources/ArcGISToolkit/Components/BasemapGallery/BasemapGalleryItem.swift
- Sources/ArcGISToolkit/Components/Bookmarks/BookmarksHeader.swift
- Sources/ArcGISToolkit/Components/Bookmarks/BookmarksList.swift
- Sources/ArcGISToolkit/Components/Compass/Compass.swift
- Sources/ArcGISToolkit/Components/FloorFilter/SiteAndFacilitySelector.swift
- Sources/ArcGISToolkit/Components/Popups/AttachmentsPopupElementView.swift
- Sources/ArcGISToolkit/Components/Popups/FieldsPopupElementView.swift
- Sources/ArcGISToolkit/Components/Popups/MediaPopupElementView.swift
- Sources/ArcGISToolkit/Components/Popups/PopupMedia/Images/AsyncImageView.swift
- Sources/ArcGISToolkit/Components/Popups/PopupMedia/Images/AsyncImageViewModel.swift
- Sources/ArcGISToolkit/Components/Popups/PopupMedia/MediaDetailView.swift
- Sources/ArcGISToolkit/Components/Popups/PopupView.swift
- Sources/ArcGISToolkit/Components/Search/SearchView.swift
- Sources/ArcGISToolkit/Components/Search/SearchViewModel.swift
- Sources/ArcGISToolkit/Components/UtilityNetworkTrace/UtilityNetworkTrace.swift
- Sources/ArcGISToolkit/Components/UtilityNetworkTrace/UtilityNetworkTraceUserAlert.swift
- Sources/ArcGISToolkit/Extensions/Bundle.swift
- Sources/ArcGISToolkit/Utility/CredentialInputView.swift
This property first looks for a bundle with the toolkit's identifier. This prevents a crash on accessing a resource when the toolkit has been built into a binary framework.
> Add custom module property

- Sources/ArcGISToolkit/Components/Popups/PopupMedia/Images/AsyncImageViewModel.swift
@njarecha discovered that using `NSLocalizedString` here was breaking `xcodebuild -exportLocalizations` and causing that string to be the only one exported.
> Fix toolkit localization export

- Documentation/FloatingPanel/README.md
- Documentation/Popup/README.md
- Examples/Examples/PopupExampleView.swift
- Sources/ArcGISToolkit/Components/FloatingPanel/FloatingPanelModifier.swift
Doing so simplifies caller code in some cases. Also, remove the `escaping` attribute since the closure doesn't actually escape.
> Make `content` parameter view builder

- Examples/Examples/FormExampleView.swift
- Sources/ArcGISToolkit/Components/Form/FormInputs/MultiLineTextEntry.swift
- Sources/ArcGISToolkit/Components/Form/FormInputs/SingleLineTextEntry.swift
- Sources/ArcGISToolkit/Components/Form/FormView.swift
- Sources/ArcGISToolkit/Components/Form/LengthValidationScheme.swift
- Sources/ArcGISToolkit/Components/Form/TextEntryFooter.swift
This PR is based off of and to be reviewed/merged following #363.
Changes:
- Switch to parsing data from the feature layer's unsupported JSON 
- `formInfo` may or may not be saved to a web map, depending on which tool was used to author the form. Over the past week we've found that a feature layer's unsupported JSON is a common place for form editors to save the form definition to. This PR simply switches the current implementation to read the form definition from the feature layer's unsupported JSON rather than the map's JSON. As a result, one can simply now initialize a `FormView` with an `ArcGISFeature` only. A map is no longer needed.
- Fixes a few `@State` initialization anti-patterns as discussed [here](https://github.com/Esri/arcgis-maps-sdk-swift-toolkit/pull/360#discussion_r124819 …
> [Form] Various improvements

- Examples/Examples/FormExampleView.swift
- Sources/ArcGISToolkit/Components/Form/FormInputs/MultiLineTextEntry.swift
- Sources/ArcGISToolkit/Components/Form/FormInputs/SingleLineTextEntry.swift
- Sources/ArcGISToolkit/Components/Form/FormView.swift
- Sources/ArcGISToolkit/Components/Form/FormViewModel.swift
- Adds a form view model to provide communication between a `FormView` and its host; adapts the implementation to use the model.
- Adds support to undo and submit local changes via the new model.
- Modifies the example view to make use of the new cancel and submit functionality.
> [FormView] Add form view model and support for persisting text field edits

- Sources/ArcGISToolkit/Components/Form/FormInputs/MultiLineTextEntry.swift
- Sources/ArcGISToolkit/Components/Form/FormView.swift
When a user has a multiline text entry field focused, the keyboard's main action button adds a new line, making it a bit more difficult for a user to complete their entry once finished. 
This PR adds a "Done" button to the  keyboard's toolbar.
</p>
> [FormView] Add "Done" button to keyboard toolbar 

- Sources/ArcGISToolkit/Utility/CredentialInputView.swift
This makes the Continue button more prominent, whereas before the Cancel button was more prominent.
Before | After
------ | -----
> Make Default the preferred action

- Sources/ArcGISToolkit/Components/Form/FormInputs/MultiLineTextEntry.swift
This button should only be present when the field is focused.
> [FormView] Multiline text entry done button adjustment

- AuthenticationExample/AuthenticationExample/SignInView.swift
- Sources/ArcGISToolkit/Components/Authentication/Authenticator.swift
Cancelling the challenge will give user a new `ArcGISChallengeCancellationError` with underlying error.
> cancel the challenge if OAuth user credential creation is cancelled

- Examples/Examples/FormExampleView.swift
- Slightly tweaks where the cancel and submit buttons are placed in the Forms example.
- On iPhone the buttons will be in the navigation bar unless in landscape which they'll then be in the full screen cover sheet.
- On iPad the buttons will always been in the sheet despite the split screen state. Leaving the buttons in the navigation bar would cause them to become dimmed but still tappable which was visually confusing.
- On macCatalyst the buttons will also always be in the sheet.
- Hides the navigation bar's back button when the form is displayed.
https://github.com/Esri/arcgis-maps-sdk-swift-toolkit/assets/16397058/705d4c31-97e4-4121-bbdc-6f1dd28854e6
https://github.com/Esri/arcgis-maps-sdk-swift-toolkit/assets/16397058/b1695229-5443-4a3a-835f-24c51064bb32
> Form View - Tweak form controls location in example

- .swiftlint.yml
The rule [has been deprecated](https://github.com/realm/SwiftLint/releases/tag/0.50.0) and now produces a warning:
> Remove `anyobject_protocol` rule

- Sources/ArcGISToolkit/Components/FloatingPanel/FloatingPanel.swift
This replaces a line that was erroneously removed in #380. Without it, content towards the bottom of the FloatingPanel can collide with the Home Bar or the panel's handle divider.
First reported by @des12437 during release testing
|   | HomeBar  | Panel Handle Divider |
|---|---|---|
| Padding  |  <img width="50%" alt="homebar" src="https://github.com/Esri/arcgis-maps-sdk-swift-toolkit/assets/16397058/ecc3ddae-d048-45ac-b319-a9f02f8efc1b">  | <img width="50%" alt="divider" src="https://github.com/Esri/arcgis-maps-sdk-swift-toolkit/assets/16397058/530c773b-34fd-4468-9b5e-285f73c47d00"> |
| No Padding  |  <img width="50%" alt="Screenshot 2023-08-14 at 09 07 03" src="https://github.com/Esri/arcgis-maps-sdk-swift-toolkit/assets/16397058/db332bd9-ac8d-4d0c-9f66-251081c91f6d">  |  <img …
> Repair `FloatingPanel` bottom content padding

- Tests/ArcGISToolkitTests/BasemapGalleryViewModelTests.swift
Fixes the "init" test in response to changes in #328
> BasemapGallery test fix

- Examples/Examples/FloatingPanelExampleView.swift
- Examples/Examples/PopupExampleView.swift
- Sources/ArcGISToolkit/Components/FloatingPanel/FloatingPanel.swift
- Sources/ArcGISToolkit/Components/FloatingPanel/FloatingPanelModifier.swift
Closes Apollo # 103
- Changes the Floating Panel to lazily evaluate the content only upon presentation. Currently the content will be evaluated as soon as the view containing the Floating Panel is loaded, meaning users have to do odd things like this to prevent content from being evaluated too early:
https://github.com/Esri/arcgis-maps-sdk-swift-toolkit/blob/f75f901995fc3efc74671c896286571df55b980a/Examples/Examples/PopupExampleView.swift#L75-L78
- Simple content such as `Text` that doesn't greedily fill its container width-wise would cause the panel to shrink horizontally when the panel is hiding away. This is also fixed and new demo content has been added to demonstrate the fix.
> Floating Panel - Presentation/usability improvements

- Sources/ArcGISToolkit/Components/FloatingPanel/FloatingPanel.swift
Changes binding properties to use `Binding` as an attribute, eliminating the need to go through the `wrappedValue` property. That also allows us to use the compiler-generated memberwise initializer, so the handwritten one has been removed. Lastly, removes erroneous `public` attribute from the `body` property.
> Cleanup `FloatingPanel`

- Examples/Utility/MapDataModel.swift
- Examples/Utility/SceneDataModel.swift
- Sources/ArcGISToolkit/Components/Authentication/Authenticator.swift
- Sources/ArcGISToolkit/Components/Authentication/CertificatePickerViewModifier.swift
- Sources/ArcGISToolkit/Components/BasemapGallery/BasemapGalleryItem.swift
- Sources/ArcGISToolkit/Components/BasemapGallery/BasemapGalleryViewModel.swift
- Sources/ArcGISToolkit/Components/Popups/Attachments/AttachmentModel.swift
- Sources/ArcGISToolkit/Components/Popups/PopupMedia/Images/AsyncImageViewModel.swift
- Sources/ArcGISToolkit/Components/Scalebar/ScalebarViewModel.swift
- Sources/ArcGISToolkit/Components/Search/SearchViewModel.swift
- Sources/ArcGISToolkit/Components/UtilityNetworkTrace/UtilityNetworkTraceViewModel.swift
Imports `Combine` wherever `Published` is used and removes `SwiftUI` imports where not necessary. Addresses the following warning seen with command line builds:
```
warning: 'Published' aliases 'Combine.Published' and cannot be used as property wrapper here because 'Combine' was not imported by this file; this is an error in Swift 6
```
> Import only what is needed

- Examples/Examples/PopupExampleView.swift
- Sources/ArcGISToolkit/Documentation.docc/Resources/PopupView/PopupViewStep3.swift
- Sources/ArcGISToolkit/Documentation.docc/Resources/PopupView/PopupViewStep4.swift
- Sources/ArcGISToolkit/Documentation.docc/Resources/PopupView/PopupViewStep5.swift
- Sources/ArcGISToolkit/Documentation.docc/Resources/PopupView/PopupViewStep6.swift
- Updates the `PopupView` example code to `defer` the task's id reset.
- This work is [also being changed](https://github.com/Esri/arcgis-maps-sdk-swift-samples/pull/247) in samples so this will keep all of our popup sample code in sync.
- Updates the `PopupView` tutorial to reflect all of the latest usage changes
> Update `PopupView` example code and tutorial

- Sources/ArcGISToolkit/Components/Authentication/CertificatePickerViewModifier.swift
- Sources/ArcGISToolkit/Components/Authentication/LoginViewModifier.swift
- Sources/ArcGISToolkit/Components/Authentication/TrustHostViewModifier.swift
- Sources/ArcGISToolkit/Components/BasemapGallery/BasemapGallery.swift
- Sources/ArcGISToolkit/Components/Bookmarks/BookmarksHeader.swift
- Sources/ArcGISToolkit/Components/Bookmarks/BookmarksList.swift
- Sources/ArcGISToolkit/Components/FloorFilter/SiteAndFacilitySelector.swift
- Sources/ArcGISToolkit/Components/Popups/AttachmentsPopupElementView.swift
- Sources/ArcGISToolkit/Components/Popups/FieldsPopupElementView.swift
- Sources/ArcGISToolkit/Components/Popups/MediaPopupElementView.swift
- Sources/ArcGISToolkit/Components/Popups/PopupMedia/Charts/BarChart.swift
- Sources/ArcGISToolkit/Components/Popups/PopupMedia/Charts/LineChart.swift
- Sources/ArcGISToolkit/Components/Popups/PopupMedia/Images/AsyncImageView.swift
- Sources/ArcGISToolkit/Components/Popups/PopupMedia/Images/AsyncImageViewModel.swift
- Sources/ArcGISToolkit/Components/Popups/PopupMedia/MediaDetailView.swift
- Sources/ArcGISToolkit/Components/Popups/PopupView.swift
- Sources/ArcGISToolkit/Components/Search/SearchView.swift
- Sources/ArcGISToolkit/Components/UtilityNetworkTrace/UtilityNetworkTrace.swift
- Sources/ArcGISToolkit/Components/UtilityNetworkTrace/UtilityNetworkTraceUserAlert.swift
- Sources/ArcGISToolkit/Extensions/String.swift
- Sources/ArcGISToolkit/Resources/en.lproj/Localizable.strings
- Sources/ArcGISToolkit/Utility/CredentialInputView.swift
- Sources/ArcGISToolkit/Utility/SearchField.swift
Related Apollo 119
- Adds comments for the remaining localized string keys missing "engineer comments" resolving ambiguites highlighted by the translations team.
cc @dg0yal
> Localized string key improvements

- AuthenticationExample/AuthenticationExample.xcodeproj/project.pbxproj
- AuthenticationExample/AuthenticationExample/AuthenticationExample.entitlements
- AuthenticationExample/AuthenticationExample/HomeView.swift
- AuthenticationExample/AuthenticationExample/SignInView.swift
- AuthenticationExample/AuthenticationExample/WebMapsView.swift
- Sources/ArcGISToolkit/Components/Authentication/Authenticator.swift
Changes in this pr,
- Updated authenticator to use the connected smart card when client certificate challenge is issued.
- Added `keychain-access-groups` with value `com.apple.token` which is required for smart card to work.
- Updated authenticator example code to find web maps from portal if featured items not available.
> updated authenticator to use smart card

- Examples/Examples/FormExampleView.swift
- Sources/ArcGISToolkit/Components/Form/FormView.swift
Simplifies the `FormView` example to only demonstrate hosting it with a Floating Panel.
~Leaving in draft at the moment as there're current issues with the core forms implementation.~
> Simplify `FormView` example

- Sources/ArcGISToolkit/Components/Form/FormInputs/DateTimeEntry.swift
- Sources/ArcGISToolkit/Components/Form/FormInputs/MultiLineTextEntry.swift
- Sources/ArcGISToolkit/Components/Form/FormInputs/SingleLineTextEntry.swift
- UI Test Runner/UITests/FormViewTests.swift
- Switches the date/time single and multi line form input fields to get their value from `FieldFormElement.value`
- Adds guards in `onAppear` bodies to prevent unnecessarily calling `setAttributeValue` with the value that's already stored.
> `FormView` - Switch to `FieldFormElement.value` from feature attributes + other minor fixes

- Sources/ArcGISToolkit/Components/AR/ARSwiftUIView.swift
- Sources/ArcGISToolkit/Components/AR/TableTopSceneView.swift
- Sources/ArcGISToolkit/Resources/en.lproj/Localizable.strings
This PR adds help text to `TableTopSceneView` to guide the user through an AR experience. The help text follows Apple's human interface [guidelines](https://developer.apple.com/design/human-interface-guidelines/augmented-reality#Communicating-with-people) for communicating with people in AR.
> AR: Add tracking state and help text to TableTop AR

- Examples/Examples/FlyoverExampleView.swift
- Sources/ArcGISToolkit/Components/AR/FlyoverSceneView.swift
- The pitch must be 90 and the roll must be 0 for flyover to work correctly. As such we shouldn't let the user specify those parameters.
- The initial camera needs to respond to changes, this fixes that and allows the initial camera and translation factor to be updated
> Flyover AR: Do not allow user to specify pitch or roll

- Sources/ArcGISToolkit/Components/AR/ARSwiftUIView.swift
- Sources/ArcGISToolkit/Components/AR/TableTopSceneView.swift
- Sources/ArcGISToolkit/Resources/en.lproj/Localizable.strings
This PR adds a coaching overlay which replaces most help text prompts. The coaching overlay and single help text prompt "Tap a surface to place the scene" can be hidden with a view modifier.
> TableTop AR: Add coaching overlay

- Examples/Examples/FlyoverExampleView.swift
- Sources/ArcGISToolkit/Components/AR/FlyoverSceneView.swift
The initial heading isn't required if we use world alignment of gravity and heading. This simplifies the API.
> AR Flyover: Do not require initial heading

- Sources/ArcGISToolkit/Components/FloatingPanel/FloatingPanel.swift
Cherry picks pre-approved changes to `FloatingPanel` from #435
> `FloatingPanel` - Cherry pick changes for `FormView` support

- Sources/ArcGISToolkit/Components/AR/FlyoverSceneView.swift
This PR adds an `initialHeading` parameter to the `FlyoverSceneView` initializers to allow the user to initialize the scene view looking a specific point/object just as they could with a `SceneView`. Passing a value of `nil` as the initial heading sets the heading of the scene to compass heading. This parameter is being re-added as it was removed in #468.
- `swift/issues/4625`
- **Note**: As of creation, this PR requires `swift-daily` to compile.
> AR Flyover: Add initial heading parameter

- Sources/ArcGISToolkit/Components/AR/ARCoachingOverlay.swift
Addresses feedback from AR tutorials PR.
> Fix typo in `ARCoachingOverlay`

- Examples/Examples/FormViewExampleView.swift
This is just a small QOL enhancement so that the example identifies features on any layers. 
The identify code no longer needs to be adjusted depending on which operational layer the target feature is on.
Good maps to test this with are "Wind Turbines" ID ending `...2dba` and Redland's water hydrants `...abe4`
> `FormView` - Example: Identify features from all layers

- Sources/ArcGISToolkit/Components/Form/FormViewModel.swift
This resets the form view model's visible elements array when startingEditing, so it doesn't contain remnants from the last invocation of FormView.
> Reset VisibleElements in model

- Examples/Examples/FormViewExampleView.swift
Simplify the forms example identify code based on the recent Popup identify simplification [here](https://github.com/Esri/arcgis-maps-sdk-swift-toolkit/pull/488).
> Simplify identify operation for form view example

- Sources/ArcGISToolkit/Extensions/Swift/Result.swift
- Tests/ArcGISToolkitTests/ResultTests.swift
it's no longer used in our examples so deprecating it.
> Deprecate cancellationToNil

- Sources/ArcGISToolkit/Components/Form/FormView.swift
Closes Apollo 270
Test map: `Form All Elements_extraLayers` (presently initial expression evaluation needs to be disabled (Apollo 268))
> `FormView` Hide dividers for unsupported form inputs

- Sources/ArcGISToolkit/Components/Search/SearchViewModel.swift
Change nullability of the center diff value. With the recent changes in ~~`swift/pull/4674`~~ `swift/pull/4433` and others to handle the GeometryEngine exception & nullability, the `distance` method no longer return optional value.
> Update `SearchViewModel`, fix nullability

- Sources/ArcGISToolkit/Components/Form/FormView.swift
This allows the form display to continue even if there are initial expression evaluation errors.
Apollo 268
> Initial expression evaluation code

- Sources/ArcGISToolkit/Components/FloorFilter/FloorFilter.swift
Fixes a warning raised during the toolkit daily build using `arcgisbuild`.
First reported by @zkline101
> Fix build warning

- Package.swift
- Sources/ArcGISToolkit/PrivacyInfo.xcprivacy
Swift issue: #4177
These are the things that need to be declared in the privacy manifest if we collect any of this info:
* [Describing data use](https://developer.apple.com/documentation/bundleresources/privacy_manifest_files/describing_data_use_in_privacy_manifests)
- [Required Use APIs](https://developer.apple.com/documentation/bundleresources/privacy_manifest_files/describing_use_of_required_reason_api)
I only listed in the privacy manifest that we use user defaults for a qualified reason. I didn't see any other items we need to list, please confirm this as a part of reviewing this PR.
> Add Privacy Manifest

- Sources/ArcGISToolkit/Components/Augmented Reality/TableTopSceneView.swift
Fixes the tap gesture bug in iOS 15 for TableTop AR by setting the minimum drag distance to zero.
> AR: Fix Issue with tapping a surface to place a scene in Tabletop Mode on iOS 15

- Sources/ArcGISToolkit/Components/FloatingPanel/FloatingPanel.swift
- Sources/ArcGISToolkit/Components/FloatingPanel/FloatingPanelModifier.swift
- Sources/ArcGISToolkit/Extensions/SwiftUI/View.swift
- Sources/ArcGISToolkit/Utility/KeyboardState.swift
Closes Apollo 278
Improves handling of keyboard closure. 
Will open a 2nd PR once this has merged to get these changes into `v.next`.
---
This essentially switches the FloatingPanel over from automatic to manual keyboard avoidance. This allows us to maintain a constant height while the keyboard is closing to rid us of the rubber band effect exhibited in Apollo 278.
---
Note: This should be tested on a physical device with rounded corners if possible. Simulators still show a little jump with the predictive text bar but I tested a bit on a physical device with rounded corners and couldn't reproduce it there.
https://github.com/Esri/arcgis-maps-sdk-swift-toolkit/assets/16397058/1eba8ad4-5de3-47a8-9ba1-3d7f40eec2ca
> `FloatingPanel` - Improve handling of keyboard closure

- Sources/ArcGISToolkit/Components/FloatingPanel/FloatingPanel.swift
- Sources/ArcGISToolkit/Components/FloatingPanel/FloatingPanelModifier.swift
- Sources/ArcGISToolkit/Extensions/SwiftUI/View.swift
- Sources/ArcGISToolkit/Utility/KeyboardState.swift
This PR simply applies the changes made to the `FloatingPanel` in #509 for `FormView` support onto `v.next`.
> Cherry pick latest `FloatingPanel` changes

- Examples/Examples/FormViewExampleView.swift
This slightly adjusts the behavior of the `FormView` example to confirm and close the form when there is a map tap before opening the next form. This takes care of a condition where a new form isn't displayed properly when another form was already open.
| Before  | After  |
|---|---|
| <video src="https://github.com/Esri/arcgis-maps-sdk-swift-toolkit/assets/16397058/1e5ff073-0369-4417-a6d0-1344803eb99e">  | <video src="https://github.com/Esri/arcgis-maps-sdk-swift-toolkit/assets/16397058/60a45da3-386f-44d1-9e04-41d957c03858">  |
> `FormView` - Example: Add interface to confirm cancel

- Sources/ArcGISToolkit/Components/FormView/GroupView.swift
- UI Test Runner/UITests/FormViewTests.swift
Closes Apollo 305
Adds descriptions to group elements and modifies UI test cases to check for them
> `FormView` - Add group element descriptions

- Sources/ArcGISToolkit/Components/Augmented Reality/TableTopSceneView.swift
The workaround will be in the Swift Maps SDK, not necessary here in the toolkit.
> Removes workaround that is no longer necessary

- Tests/ArcGISToolkitTests/BasemapGalleryItemTests.swift
Closes https://github.com/Esri/arcgis-maps-sdk-swift-toolkit/issues/522.
> Fix `BasemapGalleryItemTests.testInit()` failure

- Sources/ArcGISToolkit/Components/Popups/AttachmentsPopupElementView.swift
- Sources/ArcGISToolkit/Components/Popups/FieldsPopupElementView.swift
- Sources/ArcGISToolkit/Components/Popups/MediaPopupElementView.swift
- Sources/ArcGISToolkit/Components/UtilityNetworkTrace/UtilityNetworkTrace.swift
- Sources/ArcGISToolkit/Extensions/Swift/MacCatalyst.swift
- Sources/ArcGISToolkit/Extensions/SwiftUI/View.swift
Closes #521 
As of 17.0, disclosure triangles in Catalyst appear white whereas they used to be much darker, making this issue more visible:
---
|   | Before | After |
|---|---|---|
| iOS (No change) | <img width="320" alt="iPad-before" src="https://github.com/Esri/arcgis-maps-sdk-swift-toolkit/assets/16397058/ff57992b-c8b7-4ef9-8eab-7136d91eacc4"> | <img width="320" alt="iPad-after" src="https://github.com/Esri/arcgis-maps-sdk-swift-toolkit/assets/16397058/24249560-cd67-4e50-9088-1230b970f31a"> |
| Catalyst | <img width="400" alt="cat-before" src="https://github.com/Esri/arcgis-maps-sdk-swift-toolkit/assets/16397058/62457ca0-db12-4f80-a54c-ab195bd6bd8d"> | <img width="400" alt="cat-after" src="https://github.com/Esri/arcgis-maps-sdk-swift-toolkit/assets/16397058/b7368533-1d7c-400a-a9e0-d43 …
> Update `Menu` & `DisclosureGroup` usage for Mac Catalyst 17.0

- Sources/ArcGISToolkit/Components/Bookmarks/Bookmarks.swift
Related #533 
This repairs a build error introduced in #525 when using a binary of the Swift SDK.
> `Bookmarks` - Initializer patch

- Examples/Examples/FormViewExampleView.swift
- Sources/ArcGISToolkit/Components/FormView/FormInputs/ComboBoxInput.swift
- Sources/ArcGISToolkit/Components/FormView/FormInputs/FormInputModel.swift
- Sources/ArcGISToolkit/Components/FormView/FormInputs/RadioButtonsInput.swift
- Sources/ArcGISToolkit/Components/FormView/FormInputs/TextInput.swift
- Sources/ArcGISToolkit/Components/FormView/FormView.swift
- Sources/ArcGISToolkit/Components/FormView/FormViewModel.swift
- Sources/ArcGISToolkit/Extensions/ArcGIS/FormElement.swift
- UI Test Runner/UI Test Runner/TestViews/FormViewTestView.swift
This splits the original `FormViewModel` used by both the `FormViewExampleView` and `FormView` into two models, so the `FormView` has its own internal model. The `FormViewModel` now has all of the expression evaluation code.
It also simplifies both the example and the form view. 
This will be merged into the `mhd/NewValidationAPI` branch, which will remain until the new Validation API and implementation is complete.
> Form View model and validation updates.

- Sources/ArcGISToolkit/Components/FloatingPanel/FloatingPanelModifier.swift
I noticed that if no detent binding is provided to the floating panel modifier, the panel will just snap back to half size when the handle is released. This is because we're using a constant binding as the fallback.
</p>
> `FloatingPanel` - Fix locked detent

- Examples/Examples/FormViewExampleView.swift
- Sources/ArcGISToolkit/Components/FormView/FormInputs/ComboBoxInput.swift
- Sources/ArcGISToolkit/Components/FormView/FormInputs/DateTimeInput.swift
- Sources/ArcGISToolkit/Components/FormView/FormInputs/RadioButtonsInput.swift
- Sources/ArcGISToolkit/Components/FormView/FormInputs/SwitchInput.swift
- Sources/ArcGISToolkit/Components/FormView/FormInputs/TextInput.swift
This updates how @State variables are used in the input types, based on [this](https://github.com/Esri/arcgis-maps-sdk-swift-toolkit/pull/548#pullrequestreview-1791819063) discussion.
I've also removed some of that @State properties that weren't needed.
> State variable updates for events

- UI Test Runner/UITests/FormViewTests.swift
The footer label seems to have changed at some point in the test data
> Repair 1 FormView UI test

- Sources/ArcGISToolkit/Components/FormView/FormInputs/TextInput.swift
The current logic doesn't allow nullable numeric fields to be cleared by the user.
> `FormView` - Fix for clearing nullable numeric fields

- Sources/ArcGISToolkit/Utility/AsyncImageView.swift
Displaying the error text for an image load error clogs of the view; don't show the error text.
> Don't show error text for thumbnail errors

- Sources/ArcGISToolkit/Components/FeatureFormView/FormInputs/InputFooter.swift
- Sources/ArcGISToolkit/Components/FeatureFormView/FormInputs/TextInput.swift
- UI Test Runner/UI Test Runner.xcodeproj/project.pbxproj
- UI Test Runner/UITests/FormViewTests.swift
Apollo 384
- Mark B reported:
- Character indicators are showing in radio fields. This fixes that.
- Read-only `TextArea`s with long values are wrapping onto multiple lines. This changes them to be a horizontally scrollable single-line.
- UI test repairs
> `FeatureFormView` - Character indicator and test repair

- Sources/ArcGISToolkit/Components/Augmented Reality/ARSwiftUIView.swift
- Sources/ArcGISToolkit/Components/Augmented Reality/WorldScaleGeoTrackingSceneView.swift
Add modifier to receive geo tracking status changed events. ref doc: https://developer.apple.com/documentation/arkit/arsessionobserver/3580878-session
After this PR is merged, follow up PRs will…
- Adjust the coaching overlay dismiss condition
- Incorporate a few condition checks in `swift/issues/4875`
- Switch between `ARGeoTrackingConfiguration` based on the geo tracking [accuracy](https://developer.apple.com/documentation/arkit/argeotrackingstatus/accuracy)
- Let user optionally pass in the configuration object when creating the view.
> Add did change status action to `ARSwiftUIView`

- Sources/ArcGISToolkit/Components/Augmented Reality/ARCoachingOverlay.swift
- Sources/ArcGISToolkit/Components/Augmented Reality/WorldScaleGeoTrackingSceneView.swift
This PR adjusts the coaching overlay show/dismiss conditions for the world scale AR view. See comments in the code.
The table top AR view also uses the coaching overlay. However, it is manually controlled by inactivating the overlay when the plane anchor is added. Thus, changes in this PR won't affect the behavior of the overlay in the table top AR view.
https://github.com/Esri/arcgis-maps-sdk-swift-toolkit/blob/67228cfadc9b6f0af0c8e52ee3a597f91b04118e/Sources/ArcGISToolkit/Components/Augmented%20Reality/TableTopSceneView.swift#L171-L173
See more details in `swift/issues/4909`
> AR: Adjust coaching overlay display conditions

- Examples/Examples/WorldScaleGeoTrackingExampleView.swift
- Sources/ArcGISToolkit/Components/Augmented Reality/CalibrationView.swift
- Sources/ArcGISToolkit/Components/Augmented Reality/WorldScaleGeoTrackingSceneView.swift
- fix safe area
- fix calibration button, calibration view alignment issues
- remove opacity slider (because it now conflicts with the safe area fix)
The coaching overlay was causing the alignment issues. It had to be moved to the final overlay.
> fix overlay alignment issue, safe area fixes

- Examples/Examples/WorldScaleGeoTrackingExampleView.swift
- Sources/ArcGISToolkit/Components/Augmented Reality/CalibrationView.swift
- Sources/ArcGISToolkit/Components/Augmented Reality/WorldScaleGeoTrackingSceneView.swift
- Sources/ArcGISToolkit/Extensions/SwiftUI/View.swift
Closes `swift/4516`
Screenshots:
iPhone:
Calibrate button:
Calibration view:
iPad:
Calibrate button:
Calibration view:
> AR: Add calibration view

- Sources/ArcGISToolkit/Components/Augmented Reality/CalibrationView.swift
- Sources/ArcGISToolkit/Components/Augmented Reality/Joyslider.swift
- Sources/ArcGISToolkit/Extensions/Foundation/FloatingPoint.swift
The current slider doesn't work for me. There are 2 problems I see with it:
- it looks exactly like the system slider (because it is), but the behavior is different. If the behavior is different, it should probably look different.
-  left side of the slider is blue, which seems to indicate that the value is half, but the value is never half. The concept of "half" doesn't exist for what we are doing.
This PR introduces a custom joystick slider that looks very close to the system slider, but has slightly different colors applied.
Also this PR fixes a bug where you can see "-0" in the text in certain situations.
This is what the custom slider looks like as you are dragging it:
This is what it looks like at rest:
> Add custom joystick style slider

- Sources/ArcGISToolkit/Components/Augmented Reality/CalibrationView.swift
- Sources/ArcGISToolkit/Components/Augmented Reality/WorldScaleGeoTrackingSceneView.swift
The heading, elevation and initial elevation state variables seemed to add complication. The calibration view can just have a stream (publisher) of corrections and the corrections can be applied in real-time. Then when the total correction is needed (when a new location is received), the total correction can be applied at that time. All this can be tracked in a view model.
> Cleanup calibration related state variables 

- Sources/ArcGISToolkit/Components/Augmented Reality/CalibrationView.swift
- Sources/ArcGISToolkit/Components/Augmented Reality/WorldScaleGeoTrackingSceneView.swift
- Sources/ArcGISToolkit/Resources/en.lproj/Localizable.strings
Closes `swift/4951`.
Localizes the labels for the calibration view and the units for heading and elevation. Once these changes are merged I will update the `l10n-staging` branch.
> AR: Localize calibration view

- Sources/ArcGISToolkit/Components/FeatureFormView/FeatureFormView.swift
This simply removes the divider if the input type is `nil`, as nothing but an empty view will be shown.
> Don't show divider if input type is `nil`

- Sources/ArcGISToolkit/Components/Augmented Reality/WorldScaleSceneView.swift
Closes `swift/5014`.
Fixes bug where tap gestures on stepper controls in the calibration view were recognized on `WorldScaleSceneView`.
> AR: Fix calibration view tap gesture conflict

- Sources/ArcGISToolkit/Components/FeatureFormView/FeatureFormView.swift
- Sources/ArcGISToolkit/Components/FeatureFormView/FormInputs/ComboBoxInput.swift
- Sources/ArcGISToolkit/Components/FeatureFormView/FormInputs/DateTimeInput.swift
- Sources/ArcGISToolkit/Components/FeatureFormView/FormInputs/InputFooter.swift
- Sources/ArcGISToolkit/Components/FeatureFormView/FormInputs/RadioButtonsInput.swift
- Sources/ArcGISToolkit/Components/FeatureFormView/FormInputs/SwitchInput.swift
- Sources/ArcGISToolkit/Components/FeatureFormView/FormInputs/TextInput.swift
- Sources/ArcGISToolkit/Extensions/SwiftUI/View+FeatureForm.swift
- Sources/ArcGISToolkit/Extensions/SwiftUI/View+FormInput.swift
Apollo # 488
Add `. onChangeOfTitle` modifier to `View` and use it to handle changes to `FeatureForm.title`.
Also fix compile warning with `element.input != nil` as now `input` is non-nullable`.
~Should be merged AFTER https://github.com/Esri/arcgis-maps-sdk-swift-toolkit/pull/593, as this is based on that work.~ #593 has been merged.
> Handle Feature Form title changed event

- Sources/ArcGISToolkit/Components/FeatureFormView/FormInputs/ComboBoxInput.swift
- Test Runner/UI Tests/FormViewTests.swift
Apollo # 501
Only show the Clear button in the combo box input if the field is not required AND there is an existing value.
> Combo Box Clear button should only show if the field is not required

- Sources/ArcGISToolkit/Components/FeatureFormView/FeatureFormView.swift
- Sources/ArcGISToolkit/Components/FeatureFormView/FormInputs/ComboBoxInput.swift
Apollo # 502 - Swift - Toolkit - Combo box "Done" button blends in
Also, Apollo # 492 - UnsupportedElement/Input toolkit implementation -- Swift
> Change combo box picker Done button color to .accentColor

- Sources/ArcGISToolkit/Components/FeatureFormView/FormInputs/DateTimeInput.swift
Finalizes the Clear button updates based on the latest design [here](https://devtopia.esri.com/runtime/common-toolkit/blob/main/designs/Forms/InputValidationDesign.md#clear-button-usage).
> Only show clear button in DateIinput if date is not required

- Sources/ArcGISToolkit/Components/Augmented Reality/WorldScaleSceneView.swift
Closes `swift/5022`.
Changes enumeration case name from `automatic` to `preferGeoTracking`.
> AR: Change TrackingMode enumeration case name

- Sources/ArcGISToolkit/Components/FeatureFormView/FormInputs/InputHeader.swift
- Sources/ArcGISToolkit/Components/FeatureFormView/GroupView.swift
- Test Runner/UI Tests/FormViewTests.swift
Apollo # 307 - Group element title & caret coloring
Apollo # 293 - Group view on Mac Catalyst is ugly
This also fixes field element label alignment on Catalyst, which was displaying the labels as "centered".
> Catalyst Updates.

- Sources/ArcGISToolkit/Components/FeatureFormView/FormInputs/ComboBoxInput.swift
- Sources/ArcGISToolkit/Components/FeatureFormView/FormInputs/DateTimeInput.swift
- Sources/ArcGISToolkit/Components/FeatureFormView/FormInputs/InputFooter.swift
- Sources/ArcGISToolkit/Components/FeatureFormView/FormViewModel.swift
Related Apollo 511
- Removes doc comment on `CodedValue` `Equatable` and `Hashable` conformance. Will not proceed with change in SDK change at this time.
- Updates usage of `evaluateExpressions()`
- `includeTime` -> `includesTime`
> `FeatureFormView` - Audit updates

- Sources/ArcGISToolkit/Components/Augmented Reality/Utilities/GeoTrackingSceneView.swift
- Sources/ArcGISToolkit/Components/Augmented Reality/Utilities/WorldTrackingSceneView.swift
See `swift/issues/4991` and https://github.com/Esri/arcgis-maps-sdk-swift-toolkit/pull/581#discussion_r1496354549
I tried a few ideas, but couldn't get it work, so I used the detached task here to force the boolean to be set on the next runloop cycle (source [here](https://www.hackingwithswift.com/quick-start/concurrency/how-to-use-mainactor-to-run-code-on-the-main-queue)).
Other ideas I tried…
1. Mark `onDidUpdateFrame(perform:)` as MainActor. Because the crash happens on this modifier, my thinking was that putting it on the main serial queue will ensure:
- this modifier is strictly executed **after**, not the same time, as `sceneViewBuilder` view being instantiated, so the core scene view exists when the FOV intrinsics are set
- by running the modifier on main thread, other potential …
> AR: Fix timing crash for `initialCameraIsSet`

- Sources/ArcGISToolkit/Components/FeatureFormView/FeatureFormView.swift
- Sources/ArcGISToolkit/Components/FeatureFormView/FormInputStyle.swift
- Sources/ArcGISToolkit/Components/FeatureFormView/FormInputs/ComboBoxInput.swift
- Sources/ArcGISToolkit/Components/FeatureFormView/FormInputs/DateTimeInput.swift
- Sources/ArcGISToolkit/Components/FeatureFormView/FormInputs/InputFooter.swift
- Sources/ArcGISToolkit/Components/FeatureFormView/FormInputs/InputHeader.swift
- Sources/ArcGISToolkit/Components/FeatureFormView/FormInputs/RadioButtonsInput.swift
- Sources/ArcGISToolkit/Components/FeatureFormView/FormInputs/ReadOnlyInput.swift
- Sources/ArcGISToolkit/Components/FeatureFormView/FormInputs/SwitchInput.swift
- Sources/ArcGISToolkit/Components/FeatureFormView/FormInputs/TextInput.swift
- Sources/ArcGISToolkit/Components/FeatureFormView/FormViewModel.swift
- Sources/ArcGISToolkit/Extensions/SwiftUI/View+FormInput.swift
- Sources/ArcGISToolkit/Extensions/SwiftUI/View.swift
- Test Runner/UI Tests/FormViewTests.swift
- Makes `FormViewModel` non-public
- Removes an unneeded `Combine` import
- Fixes a `@State` property that should’ve been marked private
- Unifies padding usage and moves padding directly onto the header/footer
- Relocates an extension on `View` to the proper extensions file
- Applies plain button styling on the today/now button in the calendar picker for macCatalyst
- Applies auto-indent to `TextInput.swift`
- Fixes test 6.1 for macCatalyst
> `FeatureFormView` - Various revisions

- Examples/Examples/WorldScaleExampleView.swift
- Sources/ArcGISToolkit/Components/Augmented Reality/Utilities/GeoTrackingSceneView.swift
- Sources/ArcGISToolkit/Components/Augmented Reality/Utilities/WorldTrackingSceneView.swift
This PR changes the safe area from ignoring all edges to only the bottom edge. When the top edge safe area is ignored when the `WorldScaleSceneView` is used with a navigation bar, the navigation bar is transparent and the camera feed is visible:
This safe area change fixes the navigation bar appearance and looks like this when there is no navigation bar present:
> AR: Fix safe area

- Examples/Examples/WorldScaleExampleView.swift
- Sources/ArcGISToolkit/Components/Augmented Reality/WorldScaleSceneView.swift
- Sources/ArcGISToolkit/Documentation.docc/Resources/WorldScaleSceneView/WorldScaleSceneViewStep1.swift
- Sources/ArcGISToolkit/Documentation.docc/Resources/WorldScaleSceneView/WorldScaleSceneViewStep2.swift
- Sources/ArcGISToolkit/Documentation.docc/Resources/WorldScaleSceneView/WorldScaleSceneViewStep3.swift
- Sources/ArcGISToolkit/Documentation.docc/Resources/WorldScaleSceneView/WorldScaleSceneViewStep4.swift
- Sources/ArcGISToolkit/Documentation.docc/Tutorials/WorldScaleSceneViewTutorial.tutorial
- Tests/ArcGISToolkitTests/ARTests.swift
This PR makes `worldTracking` the default tracking mode in the initializer for the `WorldScaleSceneView`.
> AR: default tracking mode

- Sources/ArcGISToolkit/Components/FeatureFormView/FormViewModel.swift
> `FeatureFormView` - Use throwing version of `evaluateExpressions()`

- Examples/Examples/UtilityNetworkTraceExampleView.swift
- Sources/ArcGISToolkit/Components/FeatureFormView/FeatureFormView.swift
- Sources/ArcGISToolkit/Components/FeatureFormView/FormInputs/ComboBoxInput.swift
- Sources/ArcGISToolkit/Components/FeatureFormView/FormInputs/DateTimeInput.swift
- Sources/ArcGISToolkit/Components/FeatureFormView/FormInputs/EditableStateInputWrapper.swift
- Sources/ArcGISToolkit/Components/FeatureFormView/FormInputs/InputFooter.swift
- Sources/ArcGISToolkit/Components/FeatureFormView/FormInputs/InputHeader.swift
- Sources/ArcGISToolkit/Components/FeatureFormView/FormInputs/RadioButtonsInput.swift
- Sources/ArcGISToolkit/Components/FeatureFormView/FormInputs/ReadOnlyInput.swift
- Sources/ArcGISToolkit/Components/FeatureFormView/FormInputs/SwitchInput.swift
- Sources/ArcGISToolkit/Components/FeatureFormView/FormInputs/TextInput.swift
- Sources/ArcGISToolkit/Components/FeatureFormView/FormViewModel.swift
- Sources/ArcGISToolkit/Components/FeatureFormView/GroupView.swift
Additional debt cleanup in preparation of merge:
- Removes an accidental line addition in `UtilityNetworkTraceExampleView`, currently causing a warning
- Fixes a few inconsistencies in where the `accessibilityIdentifier` modifier is placed
- Applies common ordering for property declarations (attributed properties in alphabetical order followed by `let`s in alphabetical order)
- Removes types from property declarations where it is easily inferred from the initial value
- Synchronizes doc for all `element`, `formattedValue`, `isRequired`, and `value` properties
- Removes the since tag on `FormViewModel` which is no longer public
- Remove the 2nd `InputHeader` initializer, resolving a bug where a `DateTimeInput`'s header wouldn't properly update when the field became required
- Removes 3 …
> `FeatureFormView` - Additional revisions pre-merge

- Sources/ArcGISToolkit/Components/FeatureFormView/FeatureFormView.swift
- Sources/ArcGISToolkit/Components/FeatureFormView/FormInputs/ComboBoxInput.swift
- Sources/ArcGISToolkit/Components/FeatureFormView/FormInputs/DateTimeInput.swift
- Sources/ArcGISToolkit/Components/FeatureFormView/FormInputs/InputHeader.swift
- Sources/ArcGISToolkit/Components/FeatureFormView/FormInputs/InputWrapper.swift
- Sources/ArcGISToolkit/Components/FeatureFormView/FormInputs/RadioButtonsInput.swift
- Sources/ArcGISToolkit/Components/FeatureFormView/FormInputs/ReadOnlyInput.swift
- Sources/ArcGISToolkit/Components/FeatureFormView/FormInputs/SwitchInput.swift
- Sources/ArcGISToolkit/Components/FeatureFormView/FormInputs/TextInput.swift
Refactors `EditableStateInputWrapper` into `InputWrapper` which injects the header and footer for each input all from one single location now.
> `FeatureFormView` - Centralize header/footer injection

- Sources/ArcGISToolkit/Components/FeatureFormView/GroupView.swift
- The `element` property doesn't need to be stateful because it never changes
- The initializer is no longer needed
> `FeatureFormView` - `GroupView` revisions

- Sources/ArcGISToolkit/Components/FeatureFormView/FormInputs/SwitchInput.swift
Presently a `SwitchInput` in a form sets itself as the focused element upon initializing causing the form to unexpectedly scroll to the switch upon opening.
> `FeatureFormView` - Fix `SwitchInput` auto focus

- Sources/ArcGISToolkit/Components/FeatureFormView/FormViewModel.swift
Despite `evaluateExpressions` being marked `@discardableResult`, because it's reverted to throwing, the unused warning has resurfaced.
Ref apple/swift#45672
> `FeatureFormView` - Resolve unused warnings

- Examples/Examples/FeatureFormExampleView.swift
Apollo 562
- Makes use of the new non-nullable `FeatureForm` initializer
- Alphabetizes properties to match ordering used in the component
> `FeatureFormView` - Update example

- Sources/ArcGISToolkit/Components/Augmented Reality/WorldScaleSceneView.swift
Closes `swift/5096`.
This view modifier is needed to adjust basemap opacity when the calibration view is shown in the AR world scale samples.
> AR: calibration view visibility modifier

- Test Runner/UI Tests/FormViewTests.swift
- In daily runs the form is failing to open within the allotted 5 seconds. This is not reproducible locally and I suspecting slow layer load times. These failures seem randomized and not specific to any given case so I bumped the opening timeout across all cases.
- In `testCase_2_4` the "Now" button in the calendar is consistently not being found in the element hierarchy. This is also not reproducible locally. I suspect it has something to do with the animation of the calendar opening so I placed a wait there.
> `FeatureFormView` - Test stabilization

- Sources/ArcGISToolkit/Components/Augmented Reality/WorldScaleSceneView.swift
This PR renames a modifier from `onCalibrationViewVisibilityChanged` to `onCalibratingChanged`.
> AR: Rename modifier to `onCalibratingChanged`

- Sources/ArcGISToolkit/Components/FeatureFormView/Subviews/Inputs/Other/InputFooter.swift
Numeric text fields shouldn't get the character count indicator. This is likely a regression from when we merged text area & box or switched to the unified `InputFooter`.
> `FeatureFormView` - Remove character indicator from numeric text fields

- Sources/ArcGISToolkit/Components/Augmented Reality/Utilities/CalibrationView.swift
- Sources/ArcGISToolkit/Components/Augmented Reality/WorldScaleSceneView.swift
The attribute was added because the view model (which has the attribute) was being instantiated in the initializer, but it shouldn't have been. As specified in the doc, `init(initialValue:)` should not be called directly—state and state object properties should not be initialized in the enclosing object's initializer. This solves that problem and removes the `MainActor` attribute.
> Remove `MainActor` restriction on `WorldScaleSceneView` initializer

- Examples/Examples/WorldScaleExampleView.swift
- Sources/ArcGISToolkit/Components/Augmented Reality/WorldScaleSceneView.swift
This fixes a bug I noticed where the camera view did not extend into the safe area.
Before | ![Screenshot 2024-04-01 at 11 46 13](https://github.com/Esri/arcgis-maps-sdk-swift-toolkit/assets/2257493/ec0834f3-a5b2-43c0-817e-e5f159de5773)
--- | ---
After | ![Screenshot 2024-04-01 at 11 48 24](https://github.com/Esri/arcgis-maps-sdk-swift-toolkit/assets/2257493/415cbf52-de79-4c66-af29-70668d01dac7)
> Fix `WorldScaleSceneView` safe area bug

- Sources/ArcGISToolkit/Components/Augmented Reality/Utilities/ARSwiftUIView.swift
`ARSwiftUIView`'s initializer isn't ever called without a proxy object.
> Make `ARSwiftUIView.proxy` non-optional

- Test Runner/UI Tests/FormViewTests.swift
This case has failed twice at this point over the last two days.
Bumping to 10 seconds has worked elsewhere in these tests.
> `FeatureFormView` - Stabilize test case 1.4

- Sources/ArcGISToolkit/Components/FloatingPanel/FloatingPanel.swift
- Sources/ArcGISToolkit/Documentation.docc/FloatingPanel.md
- Sources/ArcGISToolkit/Documentation.docc/Resources/FloatingPanel/FloatingPanelStep4.swift
Responds to [this](https://github.com/Esri/arcgis-maps-sdk-swift-toolkit/pull/392#discussion_r1295054040) and [this](https://github.com/Esri/arcgis-maps-sdk-swift-toolkit/pull/392#discussion_r1294989490) comment.
> `FloatingPanel` Revisions

- Sources/ArcGISToolkit/Components/FloatingPanel/FloatingPanel.swift
- Sources/ArcGISToolkit/Components/FloatingPanel/FloatingPanelModifier.swift
- Sources/ArcGISToolkit/Documentation.docc/FloatingPanel.md
`FloatingPanel.swift` and `FloatingPanelModifier.swift` contain doc redundant to content in `FloatingPanel.md`. I noticed that some of the content in `FloatingPanelModifier.swift` fell out of sync after changes in #682. Therefore this PR: 
- Simplifies and syncs the doc in `FloatingPanel.swift` and `FloatingPanelModifier.swift`, adding a reference back to `FloatingPanel.md`.
- Adds a reference to the modifier in `FloatingPanel.md`, improving discoverability.
> `FloatingPanel` - Followup doc changes

- Tests/ArcGISToolkitTests/CertificatePickerViewModelTests.swift
This test has been failing consistently in daily runs as the runner uses Xcode 15.0.
The test works as expected when using 15.3 so the failure has been marked as non strict.
Related #699
> Add expected failures in `CertificatePickerViewModelTests.testViewModel()`

- Test Runner/UI Tests/FloorFilterTests.swift
This test has been failing often in this location. This change simply builds in a little leniency on timing.
> Address `FloorFilterTests.testFloorFilter` failures

- Tests/ArcGISToolkitTests/ARTests.swift
- Tests/ArcGISToolkitTests/AuthenticationManagerTests.swift
- Tests/ArcGISToolkitTests/AuthenticatorTests.swift
- Tests/ArcGISToolkitTests/BasemapGalleryItemTests.swift
- Tests/ArcGISToolkitTests/BasemapGalleryViewModelTests.swift
- Tests/ArcGISToolkitTests/FloorFilterViewModelTests.swift
- Tests/ArcGISToolkitTests/NetworkChallengeContinuationTests.swift
- Tests/ArcGISToolkitTests/ScalebarTests.swift
- Tests/ArcGISToolkitTests/SearchViewModelTests.swift
- Tests/ArcGISToolkitTests/TokenChallengeContinuationTests.swift
- Tests/ArcGISToolkitTests/TrustHostViewModifierTests.swift
- Tests/ArcGISToolkitTests/UtilityNetworkTraceViewModelTests.swift
- Tests/ArcGISToolkitTests/ValueContinuationTests.swift
Resolves the "Main actor-isolated class has different actor isolation from nonisolated superclass 'XCTestCase'; this is an error in Swift 6" warnings.
See also Swift 5188, 5218
> Address Main actor warnings

- Sources/ArcGISToolkit/Common/AttachmentsFeatureElementView.swift
- Sources/ArcGISToolkit/Components/FeatureFormView/AttachmentHelpers/AttachmentImportMenu.swift
Related: Apollo 408
- Provides a callback to `AttachmentImportMenu` to use when a new attachment has been added.
- `AttachmentsFeatureElementView` uses the callback to update its list of attachment models.
Know issues:
- Attachment naming isn't correct yet
- Thumbnails don't seem to be rendering with correct display scale - appear blurry
> `FeatureFormView` - Refresh attachment display on add

- Sources/ArcGISToolkit/Common/AttachmentModel.swift
- Sources/ArcGISToolkit/Common/AttachmentPreview.swift
- Sources/ArcGISToolkit/Common/AttachmentsFeatureElementView.swift
This moves the calculation and setting of the thumbnail size for attachments to the `AttachmentFeatureElementView` class and adds a `thumbnailSize` argument to the `AttachmentModel` constructor, instead of having it on the `load()` method.
Note this branch is based on the [FeatureFormView - Refresh attachment display on add](https://github.com/Esri/arcgis-maps-sdk-swift-toolkit/pull/704) PR, so that should be merged first.
> Use correct attachment thumbnail size

- Sources/ArcGISToolkit/Components/FeatureFormView/AttachmentHelpers/AttachmentImportMenu.swift
Early feedback indicated it's difficult to hit the new attachment button
Before
After
> `FeatureFormView` - Improve new attachment button

- Sources/ArcGISToolkit/Common/AttachmentsFeatureElementView.swift
- Sources/ArcGISToolkit/Components/FeatureFormView/FeatureFormView.swift
This adds support for `AttachmentFormElement.isEditable`, which is a `@Streamed` property that can change based on an expression evaluation.  This PR:
- Removes `editControlsDisabled` modifier
- Uses `@State isEditable` property to control showing/hiding edit controls
- Adds a new modifier `onAttachmentIsEditableChange` event for watching for `isEditable` changes on `AttachmentFormElement`
- Adds a new `isShowingAttachmentFormElement` property
The `isEditable` bit can be tested by putting the following code at the top of the Group in `AttachmentFeatureElementView`:
```
Toggle(isOn: $isEditable) {}
.toggleStyle(.switch)
```
> Add support for `AttachmentFormElement.isEditable`.

- Sources/ArcGISToolkit/Common/AttachmentsFeatureElementView.swift
- Sources/ArcGISToolkit/Components/FeatureFormView/AttachmentHelpers/AttachmentImportMenu.swift
- Sources/ArcGISToolkit/Components/FeatureFormView/FeatureFormView.swift
- Sources/ArcGISToolkit/Extensions/ArcGIS/AttachmentHelpers/AttachmentsFeatureElement.swift
- Sources/ArcGISToolkit/Extensions/ArcGIS/AttachmentHelpers/AttachmentsFormElement.swift
- Sources/ArcGISToolkit/Extensions/ArcGIS/AttachmentHelpers/AttachmentsPopupElement.swift
- Sources/ArcGISToolkit/Extensions/ArcGIS/AttachmentHelpers/FeatureAttachment.swift
- Sources/ArcGISToolkit/Extensions/ArcGIS/AttachmentHelpers/FormAttachment.swift
This updates the Toolkit to consume the latest set of Attachment API enhancements. It also adds support for the `AnyAttachmentInputType` in `AttachmentImportMenu`, which will form the bases for other attachment input types going forward.
> Rename classes as appropriate and include new API.

- Sources/ArcGISToolkit/Components/FeatureFormView/Subviews/Inputs/TextInput.swift
- Sources/ArcGISToolkit/Utility/RepresentedUITextView.swift
- Test Runner/Test Runner.xcodeproj/project.pbxproj
- Test Runner/Test Runner/TestViews/RepresentedUITextViewTestView.swift
- Test Runner/Test Runner/Tests.swift
- Test Runner/UI Tests/RepresentedUITextViewTests.swift
Ref Apollo 649
This is a follow-up to #722. 
It creates a second initializer for `RepresentedUITextView`, so we now have an initializer that takes a bound string and another that takes two callbacks (text changed and editing ended). Using the callback initializer, we can directly update the element's value, bypassing slow updates to the bound SwiftUI property.
> `FeatureFormView` - More performance improvements for multiline text

- Sources/ArcGISToolkit/Components/FeatureFormView/FeatureFormView.swift
Apollo 688. Instead of including the `AttachmentsFormElement` in the list of feature form elements authored by an environment that doesn't support attachments, the SDK now uses the `defaultAttachmentElement` property.
> Use `FeatureForm.defaultAttachmentElement`.

- Sources/ArcGISToolkit/Components/OfflineMapAreasView/PreplannedListItemView.swift
This is my first round of feedback for [PR](https://github.com/Esri/arcgis-maps-sdk-swift-toolkit/pull/723). I see several issues with the code in `List-Preplanned-Map-Areas`. 
This PR addresses several things, but the main issue I see is that status and download action are combined. That means that with the current code, I don't see a way that a download can fail, we can express that to the user, and they can try again. The status needs to be separate from the download button.
Other things it cleans up:
- don't need to specify label color parameter for foregroundStyle
- renames for clarity
- removes excess HStack
- separate out some subviews for cleaner body
There is more feedback that I have that revolves around ambiguous status states and errors. Also the model needs to contain the …
> pr feedback: list-preplanned-map-areas

- Sources/ArcGISToolkit/Components/OfflineMapAreasView/PreplannedListItemView.swift
- Sources/ArcGISToolkit/Components/OfflineMapAreasView/PreplannedMapModel.swift
That will allow you to write mocks that you can use in integration or unit tests against the view model. For example, the view model can be seeded with different mocks that have different behavior for retryLoad and report different packagingStatus. And with that, you can verify that the resulting model status is what you expect.
We should be writing these tests as we go and not wait until the end.
> Create protocol for allowing us to mock for testing and potentially previews

- Tests/ArcGISToolkitTests/CertificatePickerViewModelTests.swift
Related #699 
The test runner uses Xcode 15.4 / Swift 5.10 now.
> Guard expected failures in `CertificatePickerViewModelTests`

- Examples/Examples/FeatureFormExampleView.swift
- Sources/ArcGISToolkit/Documentation.docc/Resources/FeatureFormView/FeatureFormViewStep10.swift
- Sources/ArcGISToolkit/Documentation.docc/Resources/FeatureFormView/FeatureFormViewStep11.swift
- Sources/ArcGISToolkit/Documentation.docc/Resources/FeatureFormView/FeatureFormViewStep12.swift
- Sources/ArcGISToolkit/Documentation.docc/Resources/FeatureFormView/FeatureFormViewStep13.swift
- Sources/ArcGISToolkit/Documentation.docc/Resources/FeatureFormView/FeatureFormViewStep14.swift
- Sources/ArcGISToolkit/Documentation.docc/Resources/FeatureFormView/FeatureFormViewStep15.swift
- Sources/ArcGISToolkit/Documentation.docc/Resources/FeatureFormView/FeatureFormViewStep16.swift
- Sources/ArcGISToolkit/Documentation.docc/Resources/FeatureFormView/FeatureFormViewStep17.swift
- Sources/ArcGISToolkit/Documentation.docc/Resources/FeatureFormView/FeatureFormViewStep18.swift
- Sources/ArcGISToolkit/Documentation.docc/Resources/FeatureFormView/FeatureFormViewStep6.swift
- Sources/ArcGISToolkit/Documentation.docc/Resources/FeatureFormView/FeatureFormViewStep7.swift
- Sources/ArcGISToolkit/Documentation.docc/Resources/FeatureFormView/FeatureFormViewStep8.swift
- Sources/ArcGISToolkit/Documentation.docc/Resources/FeatureFormView/FeatureFormViewStep9.swift
- Sources/ArcGISToolkit/Documentation.docc/Tutorials/FeatureFormViewTutorial.tutorial
Related Apollo 703
1. `submitChanges()` -> `submitEdits()` to balance with `discardEdits()`
1. `finishEdits()` -> `finishEditing()` to match the function it wraps (`FeatureForm.finishEditing()`)
1. `checkFeatureEditResults()` -> `[FeatureEditResult].errors`
1. `submitEdits()` coordinates the full workflow now (as opposed to the chain pattern of submit calling validation, validation calling finish, finish calling apply)
> `FeatureFormView` - Use `finishEditing`

- Sources/ArcGISToolkit/Components/OfflineMapAreasView/OfflineMapAreasView.swift
- Sources/ArcGISToolkit/Components/OfflineMapAreasView/PreplannedListItemView.swift
- Sources/ArcGISToolkit/Components/OfflineMapAreasView/PreplannedMapModel.swift
Instead of calling `Task.detached { await self.load() }` in the view model's initializer, call it in the task modifier so it is easier to unit test the method.
> Offline: Remove detached task from model and call `load()` in the view

- Tests/ArcGISToolkitTests/PreplannedMapModelTests.swift
See `swift/issues/5414`
This PR adds the unit tests for `PreplannedMapModel`.
Code coverage:
- Omitted unknown default
- Omitted the extended protocol strings for title, description, and thumbnail
- The download related states will be tested in a follow up PR
> Offline: Add unit tests for `PreplannedMapModel`

- Sources/ArcGISToolkit/Documentation.docc/Tutorials/AuthenticatorTutorial.tutorial
- Sources/ArcGISToolkit/Documentation.docc/Tutorials/BasemapGalleryTutorial.tutorial
- Sources/ArcGISToolkit/Documentation.docc/Tutorials/BookmarksTutorial.tutorial
- Sources/ArcGISToolkit/Documentation.docc/Tutorials/CompassTutorial.tutorial
- Sources/ArcGISToolkit/Documentation.docc/Tutorials/FeatureFormViewTutorial.tutorial
- Sources/ArcGISToolkit/Documentation.docc/Tutorials/FloatingPanelTutorial.tutorial
- Sources/ArcGISToolkit/Documentation.docc/Tutorials/FloorFilterTutorial.tutorial
- Sources/ArcGISToolkit/Documentation.docc/Tutorials/FlyoverSceneViewTutorial.tutorial
- Sources/ArcGISToolkit/Documentation.docc/Tutorials/JobManagerTutorial.tutorial
- Sources/ArcGISToolkit/Documentation.docc/Tutorials/OverviewMapTutorial.tutorial
- Sources/ArcGISToolkit/Documentation.docc/Tutorials/PopupViewTutorial.tutorial
- Sources/ArcGISToolkit/Documentation.docc/Tutorials/ScalebarTutorial.tutorial
- Sources/ArcGISToolkit/Documentation.docc/Tutorials/SearchViewTutorial.tutorial
- Sources/ArcGISToolkit/Documentation.docc/Tutorials/TableTopSceneViewTutorial.tutorial
- Sources/ArcGISToolkit/Documentation.docc/Tutorials/UtilityNetworkTraceTutorial.tutorial
- Sources/ArcGISToolkit/Documentation.docc/Tutorials/WorldScaleSceneViewTutorial.tutorial
A while back, @pgruenler noticed that our tutorials didn't have highlighted code steps anymore.
I've tracked this down to us missing the `.swift` file extension as the cause. I think the requirement must've been added silently because I recall highlighting previously working okay.
> Fix tutorial step code highlighting

- Sources/ArcGISToolkit/Components/FeatureFormView/AttachmentHelpers/AttachmentImportMenu.swift
- Sources/ArcGISToolkit/Extensions/ArcGIS/AttachmentHelpers/FeatureAttachment.swift
Build fixes for consuming the final FF Attachments API.
- `AnyAttachmentsFormInput` is now internal.
- The `FormAttachment.attachment` property is now non-nullable, which differs from `PopupAttachment.attachment`. However, the `FeatureForm` protocol's `attachment` property wasn't being used, so it was removed, which eliminated the discrepancy between `FormAttachment` and `PopupAttachment`.
> Small tweaks for new, final, FF Attachments API.

- Sources/ArcGISToolkit/Components/FeatureFormView/FeatureFormView.swift
We're not going to display barcodes in the current release.
> Don't show elements with BarcodeScanner input types

- Sources/ArcGISToolkit/Resources/en.lproj/Localizable.strings
This entry is no longer present in the newly generated strings file and should not be translated.
> Update english localizable strings

- Sources/ArcGISToolkit/Components/FeatureFormView/AttachmentHelpers/AttachmentPhotoPicker.swift
Currently, the selection is not cleared, meaning that if the photo picker is reopened, the previously imported item is still indicated as selected.
> `FeatureFormView` - Clear photo picker selection after dismissal

- Sources/ArcGISToolkit/Components/FeatureFormView/AttachmentHelpers/AttachmentCameraController.swift
This removes the ability to edit captured photos/videos during adding an attachment.
Apollo #696
> Remove captured photo editing

- Sources/ArcGISToolkit/Components/FeatureFormView/AttachmentHelpers/AttachmentCameraController.swift
Apollo #767
This adds a "png" extension to attachments grabbed from the Camera; it also uses ONLY the extension for Video captures, instead of the real long, GUID-like, complete filename.
> Fix attachment file extension for camera captures

- Sources/ArcGISToolkit/Common/AttachmentPreview.swift
- Sources/ArcGISToolkit/Common/AttachmentsFeatureElementView.swift
- Sources/ArcGISToolkit/Extensions/ArcGIS/AttachmentHelpers/AttachmentsFormElement.swift
- Sources/ArcGISToolkit/Extensions/ArcGIS/AttachmentHelpers/AttachmentsPopupElement.swift
- Sources/ArcGISToolkit/Utility/Carousel.swift
Apollo 655
Followup to #782 
| Popups on `v.next` prior to #782 | Popups on this branch |
|---|---|
| <img src="https://github.com/Esri/arcgis-maps-sdk-swift-toolkit/assets/16397058/e685b120-15e2-4948-9aa2-258b28984185"> | <img src="https://github.com/Esri/arcgis-maps-sdk-swift-toolkit/assets/16397058/b03305a9-aafb-471f-97a5-9f7911933697"> |
> Cleanup `AttachmentPreview`, adding `Carousel`

- Sources/ArcGISToolkit/Components/FeatureFormView/AttachmentHelpers/AttachmentImportMenu.swift
- Sources/ArcGISToolkit/Extensions/Swift/String.swift
- Sources/ArcGISToolkit/Resources/en.lproj/Localizable.strings
Apollo 695
Re-prompt for camera access when it's been disabled in system settings.
> `FeatureFormView` - Re-prompt for camera access

- Sources/ArcGISToolkit/Common/AttachmentList.swift
- Sources/ArcGISToolkit/Common/AttachmentModel.swift
- Sources/ArcGISToolkit/Common/AttachmentPreview.swift
- Sources/ArcGISToolkit/Components/FeatureFormView/AttachmentHelpers/AttachmentImportError.swift
- Sources/ArcGISToolkit/Components/FeatureFormView/AttachmentHelpers/AttachmentImportMenu.swift
- Sources/ArcGISToolkit/Extensions/OS/Logger.swift
- Sources/ArcGISToolkit/Extensions/SwiftUI/Text.swift
- Sources/ArcGISToolkit/Resources/en.lproj/Localizable.strings
> `AttachmentsFeatureElementView` - Block empty file upload/download/preview

- Sources/ArcGISToolkit/Common/AttachmentList.swift
- Sources/ArcGISToolkit/Common/AttachmentPreview.swift
- Sources/ArcGISToolkit/Extensions/Swift/String.swift
- Sources/ArcGISToolkit/Extensions/SwiftUI/Text.swift
[Followup](https://github.com/Esri/arcgis-maps-sdk-swift-toolkit/pull/791#discussion_r1669413256) to #791
> `AttachmentsFeatureElementView` - Swap out deprecated alert API

- Sources/ArcGISToolkit/Components/FeatureFormView/AttachmentHelpers/AttachmentCameraController.swift
- Sources/ArcGISToolkit/Components/FeatureFormView/AttachmentHelpers/AttachmentImportMenu.swift
- Sources/ArcGISToolkit/Resources/en.lproj/Localizable.strings
- Test Runner/Test Runner.xcodeproj/project.pbxproj
- Test Runner/Test Runner/TestViews/AttachmentCameraControllerTestView.swift
- Test Runner/Test Runner/Tests.swift
- Test Runner/UI Tests/AttachmentCameraControllerTests.swift
Apollo 695
If microphone access is denied, videos will be recorded without audio, likely without the user knowing/remembering. This allows us to check the microphone access status when the user switches to video and show an alert if access is denied. 
iOS will only automatically prompt for microphone access the first time after the app is installed.
> `AttachmentsFeatureElementView` - Validate microphone access

- Sources/ArcGISToolkit/Common/AttachmentsFeatureElementView.swift
- Sources/ArcGISToolkit/Extensions/ArcGIS/AttachmentHelpers/FeatureAttachment.swift
With the latest change in Core, we now need to reverse the attachment order to display in the correct order. This means that both Popup and FeatureForm attachment arrays get reversed.
Also, a minor doc change.
> Reverse attachment order

- Sources/ArcGISToolkit/Components/FeatureFormView/AttachmentHelpers/AttachmentImportMenu.swift
| Before | After |
|---|---|
| <img width="124" alt="Screenshot 2024-07-11 at 11 56 12 AM" src="https://github.com/Esri/arcgis-maps-sdk-swift-toolkit/assets/16397058/dad19d63-0d7e-4d78-a8a7-8c6a0c4a4f5f"> | <img width="133" alt="Screenshot 2024-07-11 at 11 57 27 AM" src="https://github.com/Esri/arcgis-maps-sdk-swift-toolkit/assets/16397058/6670ac50-9567-4294-abc7-77d7e331f072"> |
> `AttachmentImportMenu` - Adjust padding for Mac Catalyst

- Sources/ArcGISToolkit/Common/AttachmentModel.swift
`isLocal` doc: A value indicating whether “loading” (fetching the data) can be accomplished without using the network.
Thumbnails are shown automatically when a form is re-opened and an attachment was previously loaded.
</p>
> `AttachmentModel` - Auto load local attachments

- Test Runner/Test Runner/TestViews/AttachmentCameraControllerTestView.swift
- Test Runner/UI Tests/AttachmentCameraControllerTests.swift
- Attempts to address the two failures since this test was merged
- Fixes camera view rendering on iPhone in landscape mode
> Stabilize `AttachmentCameraControllerTests.testOnCameraCaptureModeChanged()`

- Sources/ArcGISToolkit/Components/Augmented Reality/Utilities/ARSwiftUIView.swift
- Sources/ArcGISToolkit/Extensions/Swift/MainActor.swift
Addresses the following error:
Note: I do not have a device running iOS 16 to test with. If one of you does, I would appreciate it if you could verify that code pathway.
> Address remaining complete strict concurrency error

- Sources/ArcGISToolkit/Components/Augmented Reality/FlyoverSceneView.swift
- Sources/ArcGISToolkit/Components/Augmented Reality/TableTopSceneView.swift
- Sources/ArcGISToolkit/Components/BasemapGallery/BasemapGallery.swift
- Sources/ArcGISToolkit/Components/Compass/Compass.swift
- Sources/ArcGISToolkit/Components/FeatureFormView/FeatureFormView+ValidationErrorVisibility.swift
- Sources/ArcGISToolkit/Components/FloatingPanel/FloatingPanelDetent.swift
- Sources/ArcGISToolkit/Components/FloorFilter/FloorFilterAutomaticSelectionMode.swift
- Sources/ArcGISToolkit/Components/FloorFilter/FloorFilterSelection.swift
- Sources/ArcGISToolkit/Components/JobManager/JobManager.swift
- Sources/ArcGISToolkit/Components/Scalebar/ScalebarSettings.swift
- Sources/ArcGISToolkit/Components/Scalebar/ScalebarStyle.swift
- Sources/ArcGISToolkit/Components/Scalebar/ScalebarUnits.swift
- Sources/ArcGISToolkit/Components/Search/SearchViewModel.swift
- Sources/ArcGISToolkit/Components/UtilityNetworkTrace/UtilityNetworkTraceStartingPoint.swift
- Sources/ArcGISToolkit/Extensions/ArcGIS/AttachmentHelpers/AttachmentsFeatureElement.swift
- Sources/ArcGISToolkit/Extensions/ArcGIS/AttachmentHelpers/FeatureAttachment.swift
- Sources/ArcGISToolkit/Extensions/OS/Logger.swift
- Sources/ArcGISToolkit/Utility/SearchField.swift
- Tests/ArcGISToolkitTests/CompassTests.swift
This does not include SwiftUI views, which are typically not sendable.
> Make public types sendable

- Sources/ArcGISToolkit/Common/AttachmentPreview.swift
- Sources/ArcGISToolkit/Components/FeatureFormView/AttachmentHelpers/AttachmentImportMenu.swift
- Sources/ArcGISToolkit/Resources/en.lproj/Localizable.strings
Apollo 768 & 786
- Disables the context menu for attachments with size 0 bytes.
- Disables the rename action for attachments over 50 MB.
- Disables downloads of attachments over 50 MB.
> `AttachmentPreview` - Apply size based functionality restrictions

- Examples/Examples/FloorFilterExampleView.swift
- Sources/ArcGISToolkit/Components/FloorFilter/FloorFilter.swift
- Sources/ArcGISToolkit/Components/FloorFilter/SiteAndFacilitySelector.swift
Closes #783
> [!IMPORTANT]  
> Test under `UserInterfaceSizeClass.compact` (e.g. iPhone or iPad in Split View)
How to test:
1. Open the Site and Facility Selector. 
2. **Interactively** dismiss the Site and Facility Selector (e.g. swipe down from the header or empty body area).
3. Pan the map. The Site and Facility Selector does not unexpectedly reappear.
Findings:
The `.constant(!$isSitesAndFacilitiesHidden.wrappedValue)` prevented `isSitesAndFacilitiesHidden` from being set `true` when the sheet was interactively dismissed, causing it to reappear when the view was re-evaluated.
> `FloorFilter` - Fix unintended `SiteAndFacilitySelector` re-open

- Examples/Examples.xcodeproj/project.pbxproj
- Examples/ExamplesApp/Examples.entitlements
- Sources/ArcGISToolkit/Components/FeatureFormView/AttachmentHelpers/AttachmentCameraController.swift
- Sources/ArcGISToolkit/Components/FeatureFormView/AttachmentHelpers/AttachmentImportMenu.swift
Ref Apollo 778
- Adds audio/camera entitlements for Catalyst for the Examples app.
- Xcode enables hardened runtime for `macos` when these entitlements are added
- Marks `AttachmentCameraController.onCameraCaptureModeChanged` unavailable for Catalyst as I could not find a suitable NSNotification to detect the audio/video change.
- Disables the app settings buttons for Catalyst as I couldn't find a suitable alternative to `UIApplication.openSettingsURLString`. Instead, the user must open settings manually:
</p>
>  `AttachmentsFeatureElementView` - Fix Catalyst audio/video capture

- Examples/Examples/PopupExampleView.swift
- Examples/Examples/UtilityNetworkTraceExampleView.swift
Closes #30 
Adds attribution bar height into remaining examples not already using it.
> Use attribution bar height in remaining examples

- Sources/ArcGISToolkit/Components/Authentication/CertificatePickerViewModifier.swift
- Sources/ArcGISToolkit/Resources/en.lproj/Localizable.strings
- Tests/ArcGISToolkitTests/CertificatePickerViewModelTests.swift
> Rename `CertificateError.couldNotAccessCertificateFile` to `failedToAccessCertificateFile`

- Sources/ArcGISToolkit/Utility/Carousel.swift
- Sources/ArcGISToolkit/Utility/CredentialInputView.swift
Strings in SwiftUI previews generate entries in Localizable.strings for translation unless we use `Text(verbatim:)`.
I don't believe we need to translate preview strings, as they're essentially developer tooling and not for end-users. If we do, I can close this PR.
> Fix SwiftUI preview strings generating entries in Localizable.strings

- Sources/ArcGISToolkit/Utility/Carousel.swift
Offsets the scrollbar from covering cell bottoms as requested by @rolson
Before
After
> `Carousel` - Add bottom padding to offset scrollbar

- OfflineMapAreasExample/OfflineMapAreasExample/OfflineMapAreasExampleView.swift
- Sources/ArcGISToolkit/Components/Offline/OfflineMapAreasView.swift
- Sources/ArcGISToolkit/Components/Offline/PreplannedListItemView.swift
- Sources/ArcGISToolkit/Components/Offline/PreplannedMapModel.swift
- Tests/ArcGISToolkitTests/PreplannedMapModelStatusTests.swift
- Tests/ArcGISToolkitTests/PreplannedMapModelTests.swift
Closes `swift/5358`
Adds support to open a downloaded preplanned map area with the "open" button which dismisses the view and returns a `Map` via the `onMapSelectionChanged` view modifier. If the preplanned map area's mobile map package fails to load when opened then the view's status is set to `mmpkLoadFailure`.
> Offline: Open a preplanned map area

- Test Runner/Test Runner.xcodeproj/project.pbxproj
- Test Runner/UI Tests/RepresentedUITextViewTests.swift
https://github.com/Esri/arcgis-maps-sdk-swift-toolkit/pull/844#discussion_r1735088668
> Remove `swift-markdown` as Test Runner dependency

- Sources/ArcGISToolkit/Components/FeatureFormView/FeatureFormView.swift
Apollo 815
Adds information on the `AttachmentsFormElement` and `TextFormElement` to the `FeatureFormView` documentation. It also updates the Group Element description to specify all form elements, not just field form elements.
> Text form element Toolkit doc

- Sources/ArcGISToolkit/Utility/AsyncImageViewModel.swift
Closes #854 
I suspect these were just leftovers from implementation that didn't get pulled out. If not, we can change them to structured log messages instead.
> Remove extraneous print statements

- Sources/ArcGISToolkit/Components/Offline/OfflineMapAreasView.swift
Closes `swift/5939`
- Implements pull to refresh 
- Renames section title from "Preplanned Map Areas" to "Preplanned"
https://github.com/user-attachments/assets/8789a79e-82e0-4788-9a57-fddfb2509350
> Offline: pull to refresh

- OfflineMapAreasExample/OfflineMapAreasExample/OfflineMapAreasExampleView.swift
- Sources/ArcGISToolkit/Components/Offline/OfflineMapAreasView.swift
- Sources/ArcGISToolkit/Components/Offline/PreplannedListItemView.swift
- Sources/ArcGISToolkit/Components/Offline/PreplannedMapModel.swift
- Tests/ArcGISToolkitTests/PreplannedMapModelTests.swift
- Related to https://github.com/Esri/arcgis-maps-sdk-swift-toolkit/pull/843#discussion_r1747486303
- Close swift/issues/5968
For this PR, a few things have been done:
1. Test if the mmpk files are locked and cannot be deleted when a map created from it is being viewed
- The result is that the files can be deleted, while the map being viewed cannot show the tiles beyond current LoD. The features can still be shown
- Upon discussion, this behavior shouldn't be relied upon. Instead, we should disallow deletion when a map is being viewed.
2. How to go back online?
- Upon discussion, it is not the component's responsibility to "unselect" a map area and go back to online webmap.
- Thus, a button is added at the app level to go online to show this workflow.
3. Disallow opening again or deleting …
> Improve selection logics

- Sources/ArcGISToolkit/Components/Authentication/DocumentPickerView.swift
Swift issue #6012
This method is [deprecated](https://developer.apple.com/documentation/uikit/uidocumentpickerdelegate/1618680-documentpicker) on iOS and unavailable on visionOS so we should use the [replacement](https://developer.apple.com/documentation/uikit/uidocumentpickerdelegate/2902364-documentpicker).
> Use replacement document picker method

- Sources/ArcGISToolkit/Components/Offline/PreplannedListItemView.swift
- Sources/ArcGISToolkit/Components/Offline/PreplannedMetadataView.swift
I missed this in the previous PR #843 .
> Offline: Disallow deletion in metadata view when map is selected

- Sources/ArcGISToolkit/Documentation.docc/AugmentedReality.md
Adds documentation links for each AR component in the Augmented Reality DocC article.
> AR: Add component links to DocC

- Sources/ArcGISToolkit/Components/Offline/OfflineMapAreasView.swift
Closes `swift/6039`
- Renames "Offline Maps" title to "Map Areas"
- Removes "Preplanned" section header
- Rewords empty state view
> Offline: Refactor UI

- Sources/ArcGISToolkit/Utility/MarkdownView.swift
- Adds support for Markdown heading levels 5 & 6. We previously only supported levels 1-4.
</p>
> `MarkdownView` - Support all 6 Markdown heading levels

- Package.swift
- Sources/ArcGISToolkit/Components/Augmented Reality/FlyoverSceneView.swift
- Sources/ArcGISToolkit/Components/Augmented Reality/TableTopSceneView.swift
- Sources/ArcGISToolkit/Components/Augmented Reality/Utilities/ARCoachingOverlay.swift
- Sources/ArcGISToolkit/Components/Augmented Reality/Utilities/ARSwiftUIView.swift
- Sources/ArcGISToolkit/Components/Augmented Reality/Utilities/CalibrationView.swift
- Sources/ArcGISToolkit/Components/Augmented Reality/Utilities/GeoTrackingSceneView.swift
- Sources/ArcGISToolkit/Components/Augmented Reality/Utilities/WorldTrackingSceneView.swift
- Sources/ArcGISToolkit/Components/Augmented Reality/WorldScaleSceneView.swift
- Sources/ArcGISToolkit/Components/Compass/Compass.swift
- Sources/ArcGISToolkit/Components/FeatureFormView/AttachmentHelpers/AttachmentCameraController.swift
- Sources/ArcGISToolkit/Components/FeatureFormView/AttachmentHelpers/AttachmentImportMenu.swift
- Sources/ArcGISToolkit/Components/FeatureFormView/FeatureFormView.swift
- Sources/ArcGISToolkit/Components/FeatureFormView/Subviews/Inputs/ComboBoxInput.swift
- Sources/ArcGISToolkit/Components/FeatureFormView/Subviews/Inputs/DateTimeInput.swift
- Sources/ArcGISToolkit/Components/FeatureFormView/Subviews/Inputs/RadioButtonsInput.swift
- Sources/ArcGISToolkit/Components/FeatureFormView/Subviews/Inputs/SwitchInput.swift
- Sources/ArcGISToolkit/Components/FeatureFormView/Subviews/Inputs/TextInput.swift
- Sources/ArcGISToolkit/Components/FloatingPanel/FloatingPanel.swift
- Sources/ArcGISToolkit/Components/FloorFilter/FloorFilter.swift
- Sources/ArcGISToolkit/Components/FloorFilter/LevelSelector.swift
- Sources/ArcGISToolkit/Components/FloorFilter/SiteAndFacilitySelector.swift
- Sources/ArcGISToolkit/Components/OverviewMap.swift
- Sources/ArcGISToolkit/Components/Scalebar/Scalebar.swift
- Sources/ArcGISToolkit/Components/Search/SearchView.swift
- Sources/ArcGISToolkit/Components/UtilityNetworkTrace/UtilityNetworkTrace.swift
- Sources/ArcGISToolkit/Extensions/ArcGIS/SceneViewProxy.swift
- Sources/ArcGISToolkit/Extensions/SwiftUI/View+OnChange.swift
- Sources/ArcGISToolkit/Utility/Carousel.swift
Swift #6012
This PR is adding visionOS as a supported platform so the toolkit can build against visionOS. More work is coming after this to make sure all the components work and look correctly on this platform.
Components that are unavailable for visionOS:
- All AR components. Most of the ARKit API we are using isn't available on visionOS.
- Taking a photo or video for feature forms is not available on visionOS.
Xcode 16 must be used to build successfully.
> Add visionOS as a supported platform

- Sources/ArcGISToolkit/Components/Bookmarks/Bookmarks.swift
- Sources/ArcGISToolkit/Components/Bookmarks/BookmarksHeader.swift
Swift #6015
Before:
After:
Per HIG guidelines on visionOS:
> A visionOS button typically includes a visible background that can help people see it ...
> Bookmark UI edits for visionOS

- Sources/ArcGISToolkit/Components/BasemapGallery/BasemapGalleryCell.swift
> Edit hover effect in `BasemapGalleryCell`

- Sources/ArcGISToolkit/Components/Offline/PreplannedMapModel.swift
Closes `swift/5937`
- Removes contents of the mmpk directory when the download fails.
> Offline: Handle failed mobile map package download

- Sources/ArcGISToolkit/Components/FloatingPanel/FloatingPanel.swift
- Sources/ArcGISToolkit/Components/FloatingPanel/FloatingPanelModifier.swift
Swift #6015
Here are different screenshots of the floating panel being used:
> UI edits for `FloatingPanel`

- Package.swift
- Sources/ArcGISToolkit/Components/Offline/OfflineMapAreasView.swift
- Sources/ArcGISToolkit/Components/Offline/PreplannedListItemView.swift
- Sources/ArcGISToolkit/Components/Offline/PreplannedMapModel.swift
- Tests/ArcGISToolkitTests/PreplannedMapModelTests.swift
Related to `swift/6048`
- Rephrases empty state view text
- Uses `ContentUnavailableView` when map is offline disabled
- Removes HTML tags from map area description
- Animates open button
> Offline: UI improvements

- Sources/ArcGISToolkit/Common/CameraRequester.swift
- Sources/ArcGISToolkit/Common/FlashlightButton.swift
- Sources/ArcGISToolkit/Components/FeatureFormView/AttachmentHelpers/AttachmentImportMenu.swift
- Sources/ArcGISToolkit/Components/FeatureFormView/FeatureFormView.swift
- Sources/ArcGISToolkit/Components/FeatureFormView/Subviews/Inputs/BarcodeScannerInput.swift
- Sources/ArcGISToolkit/Components/FeatureFormView/Subviews/Inputs/Other/InputWrapper.swift
- Sources/ArcGISToolkit/Components/FeatureFormView/Subviews/Inputs/TextInput.swift
- Sources/ArcGISToolkit/Extensions/ArcGIS/FieldFormElement.swift
- Sources/ArcGISToolkit/Extensions/Swift/String.swift
- Sources/ArcGISToolkit/Resources/en.lproj/Localizable.strings
> `FeatureFormView` - `BarcodeScannerFormInput` support

- Sources/ArcGISToolkit/Components/Offline/OfflineMapAreasView.swift
- Sources/ArcGISToolkit/Components/Offline/PreplannedListItemView.swift
- Sources/ArcGISToolkit/Components/Offline/PreplannedMetadataView.swift
Closes `swift/6071`
- Removes the "Delete" swipe action
- Rephrases the delete button in the MetadataView from "Delete Map Area" to "Remove Download"
Discussion:
Is a section footer under the "Remove Download" button with text such as "Removes downloaded map area from device." needed?
> Offline: Remove delete swipe action

- Sources/ArcGISToolkit/Common/CameraRequester.swift
- Sources/ArcGISToolkit/Common/CodeScanner.swift
- Sources/ArcGISToolkit/Components/FeatureFormView/Subviews/Inputs/TextInput.swift
Ref Apollo 898
- Moves `CameraRequester` directly onto `CodeScanner` so camera permission checking is built into `CodeScanner`
- Adds tap to focus/expose on `CodeScanner`
> `BarcodeScannerFormInput` - More refinements

- Tests/ArcGISToolkitTests/ARTests.swift
- Tests/ArcGISToolkitTests/AttachmentsFeatureElementDisplayTypeTests.swift
- Tests/ArcGISToolkitTests/CompassTests.swift
- Tests/ArcGISToolkitTests/FeatureAttachmentKindTests.swift
- Tests/ArcGISToolkitTests/FloorFilterViewModelTests.swift
- Tests/ArcGISToolkitTests/LocatorSearchSourceTests.swift
- Tests/ArcGISToolkitTests/ScalebarTests.swift
- Tests/ArcGISToolkitTests/SearchViewModelTests.swift
- Tests/ArcGISToolkitTests/SmartLocatorSearchSourceTests.swift
- Tests/ArcGISToolkitTests/UtilityNetworkTraceViewModelTests.swift
Since the toolkit package supports visionOS that means I can't stop someone from running the unit tests against visionOS even though most of the tests use components that aren't supported yet for visionOS.
So if someone tries to run the unit tests against visionOS they will see build errors for components that unavailable for visionOS. This fixes those and the tests that can be run I left alone and they succeed.
I wish marking a test class as `@available(visionOS, unavailable)` would prevent that class from being run on visionOS but it does not so I just hide those test classes behind `#if !os(visionOS)`.
> Fix unit tests for visionOS

- Sources/ArcGISToolkit/Components/OverviewMap.swift
No edits needed I tested on a device and sim.
> Make OverviewMap available for visionOS

- Sources/ArcGISToolkit/Components/Scalebar/Scalebar.swift
- Sources/ArcGISToolkit/Components/Scalebar/ScalebarLabel.swift
- Sources/ArcGISToolkit/Components/Scalebar/ScalebarModifiers.swift
- Sources/ArcGISToolkit/Components/Scalebar/ScalebarSettings.swift
- Sources/ArcGISToolkit/Components/Scalebar/ScalebarStyle.swift
- Sources/ArcGISToolkit/Components/Scalebar/ScalebarStyleRenderer.swift
- Sources/ArcGISToolkit/Components/Scalebar/ScalebarUnits.swift
- Sources/ArcGISToolkit/Components/Scalebar/ScalebarViewModel.swift
- Tests/ArcGISToolkitTests/ScalebarTests.swift
No edits needed I tested on a device and sim.
> Make Scalebar available on visionOS

- Sources/ArcGISToolkit/Components/OverviewMap.swift
- Sources/ArcGISToolkit/Components/Scalebar/Scalebar.swift
I rebased visionOS v.next with v.next and I resolved the conflicts but I accidently resolved these conflicts incorrectly. I forgot I recently marked these two components as available for visionOS.
> Fix rebase conflicts

- Package.swift
Ref Swift 6183
@zkline101 discovered:
> Privacy manifests are automatically included as a copied resource for packages with tools version >= 6.0. (111119227)
In the [Xcode 16 Swift Package release notes](https://developer.apple.com/documentation/xcode-release-notes/xcode-16-release-notes#Swift-Packages).
cc @mhdostal
> Stop copying `PrivacyInfo.xcprivacy`

- Sources/ArcGISToolkit/Components/Offline/PreplannedListItemView.swift
Limit the title to 2 lines per Ryan's feedback. I chose 2 lines to match what App Store does.
> Offline: Add line limit to the title

- Sources/ArcGISToolkit/Components/FeatureFormView/FeatureFormView.swift
- Sources/ArcGISToolkit/Components/FeatureFormView/Subviews/GroupView.swift
This adds support for `TextFormElement`s inside a `GroupFormElement`. Previously, only `FieldFormElement`s were supported, as that was the only element type available when the group element was implemented.
It also adds a `Divider` below the text form element.
Apollo/936
> Support `TextFormElement`s inside a `GroupFormElement`

- Sources/ArcGISToolkit/Components/Augmented Reality/TableTopSceneView.swift
- Sources/ArcGISToolkit/Documentation.docc/Resources/TableTopSceneView/TableTopSceneViewStep1.swift
- Sources/ArcGISToolkit/Documentation.docc/Resources/TableTopSceneView/TableTopSceneViewStep2.swift
- Sources/ArcGISToolkit/Documentation.docc/Resources/TableTopSceneView/TableTopSceneViewStep3.swift
- Sources/ArcGISToolkit/Documentation.docc/Tutorials/TableTopSceneViewTutorial.tutorial
This PR updates the `TableTopSceneView.init(anchorPoint:translationFactor:clippingDistance:sceneView:)` doc with more info that can be found in the [Implement tabletop AR](https://developers.arcgis.com/swift/scenes-3d/display-scenes-in-augmented-reality/#implement-tabletop-ar) conceptual doc.
- `swift/issues/6175`
> [Update] Table top `translationFactor` doc

- Sources/ArcGISToolkit/Common/AttachmentList.swift
- Sources/ArcGISToolkit/Common/AttachmentModel.swift
- Sources/ArcGISToolkit/Common/AttachmentPreview.swift
- Sources/ArcGISToolkit/Common/AttachmentsFeatureElementView.swift
- Sources/ArcGISToolkit/Common/ThumbnailView.swift
- Sources/ArcGISToolkit/Components/FeatureFormView/AttachmentHelpers/AttachmentImportMenu.swift
- Sources/ArcGISToolkit/Components/Popups/FieldsPopupElementView.swift
- Sources/ArcGISToolkit/Components/Popups/MediaPopupElementView.swift
- Sources/ArcGISToolkit/Components/Popups/PopupElementHeader.swift
- Sources/ArcGISToolkit/Components/Popups/PopupMedia/Charts/ChartMediaView.swift
- Sources/ArcGISToolkit/Components/Popups/PopupMedia/Images/ImageMediaView.swift
- Sources/ArcGISToolkit/Components/Popups/PopupMedia/MediaDetailView.swift
- Sources/ArcGISToolkit/Components/Popups/PopupView.swift
- Sources/ArcGISToolkit/Extensions/ArcGIS/AttachmentHelpers/AttachmentsFeatureElement.swift
- Sources/ArcGISToolkit/Extensions/ArcGIS/AttachmentHelpers/AttachmentsPopupElement.swift
- Sources/ArcGISToolkit/Extensions/ArcGIS/AttachmentHelpers/FeatureAttachment.swift
- Sources/ArcGISToolkit/Extensions/ArcGIS/AttachmentHelpers/FormAttachment.swift
- Sources/ArcGISToolkit/Extensions/ArcGIS/AttachmentHelpers/PopupAttachment.swift
- Sources/ArcGISToolkit/Extensions/Swift/String.swift
- Sources/ArcGISToolkit/Utility/AsyncImageView.swift
Swift #6156
I tried multiple pop up data sets with these changes to make sure I covered all the bases but I would still recommend looking at these changes yourself. You can test this by adding visionOS as a destination to the Examples app and just comment out the examples that aren't available on visionOS or mark the examples as `@available(visionOS, unavailable)`.
Here are some screenshots:
> Add visionOS support to `PopupView`

- Sources/ArcGISToolkit/Utility/MarkdownView.swift
Stops these unneeded entries from being generated in the localized strings file:
</p>
> Remove unneeded localized string initializers

- Tests/ArcGISToolkitTests/CertificatePickerViewModelTests.swift
Closes #699 
Swift 6.0 is the current minimum
> `CertificatePickerViewModelTests` - Remove outdated expected failure

- Examples/Examples/FlyoverExampleView.swift
- Examples/Examples/TableTopExampleView.swift
- Examples/Examples/WorldScaleExampleView.swift
- Examples/ExamplesApp/Examples.swift
- Sources/ArcGISToolkit/Components/Augmented Reality/FlyoverSceneView.swift
- Sources/ArcGISToolkit/Components/Augmented Reality/TableTopSceneView.swift
- Sources/ArcGISToolkit/Components/Augmented Reality/Utilities/CalibrationView.swift
- Sources/ArcGISToolkit/Components/Augmented Reality/WorldScaleSceneView.swift
Temporarily reverts #946 to allow the Samples app time to prepare.
> Revert "Drop AR components from Catalyst"

- Examples/Examples/FlyoverExampleView.swift
- Examples/Examples/TableTopExampleView.swift
- Examples/Examples/WorldScaleExampleView.swift
- Examples/ExamplesApp/Examples.swift
- Sources/ArcGISToolkit/Components/Augmented Reality/FlyoverSceneView.swift
- Sources/ArcGISToolkit/Components/Augmented Reality/TableTopSceneView.swift
- Sources/ArcGISToolkit/Components/Augmented Reality/Utilities/CalibrationView.swift
- Sources/ArcGISToolkit/Components/Augmented Reality/WorldScaleSceneView.swift
- Tests/ArcGISToolkitTests/ARTests.swift
Closes #889 
Re-removes AR support for Mac Catalyst after it had to be reverted in #955 to allow the Samples app to prepare.
> Drop AR components from Catalyst

- Sources/ArcGISToolkit/Components/FeatureFormView/Subviews/Inputs/DateTimeInput.swift
- Sources/ArcGISToolkit/Components/FeatureFormView/Subviews/Inputs/TextInput.swift
Adjust scan button size and color; remove Clear button for barcode input type:
For Apollo 958
> Barcode UI improvements

- Sources/ArcGISToolkit/Components/FeatureFormView/Subviews/Inputs/TextInput.swift
> Mark `TextInput` extension unavailable for visionOS

- Sources/ArcGISToolkit/Documentation.docc/AugmentedReality.md
Resolves DocC warnings on Mac Catalyst caused by unrecognized symbol links.
> Fix DocC warnings

- Sources/ArcGISToolkit/Documentation.docc/AugmentedReality.md
Reverts Esri/arcgis-maps-sdk-swift-toolkit#968
Adds symbol links for the AR components back to the augmented reality DocC article.
> Revert "Fix DocC warnings"

- Sources/ArcGISToolkit/Utility/Carousel.swift
In #846 we pushed the scrollbar below the Carousel content.
On Mac Catalyst scrolling with a scroll wheel on a mouse (no Trackpad) isn't supported and so the scroll indicator is necessary to support drag based scrolling. This adjusts an internal frame height such that the height increase from the indicator offset is now included in the form's VStack and the scroll indicator is hittable with a mouse.
| Before | After |
|---|---|
| <img src="https://github.com/user-attachments/assets/a2f4253d-f661-43ff-8ddf-885f8eb69249"> | <img src="https://github.com/user-attachments/assets/5fe2fa00-2de1-4030-8978-77fb85a1a400"> |
> `Carousel` - Fix horizontal manual scroll on Catalyst

- Sources/ArcGISToolkit/Components/UtilityNetworkTrace/UtilityNetworkTrace.swift
- Sources/ArcGISToolkit/Resources/en.lproj/Localizable.strings
Closes #918 
| 0 Results Example | Multiple Results Example |
|---|---|
| <img src="https://github.com/user-attachments/assets/ea60ea00-cc58-4c66-8590-7aa7345fb8c7"> | <img src="https://github.com/user-attachments/assets/88019741-2ce2-4824-bcad-a12a5e3b4bdc"> |
> `UtilityNetworkTrace` - Enhance trace result labels

- Examples/Examples/PopupExampleView.swift
- Sources/ArcGISToolkit/Components/FeatureFormView/FeatureFormView+FormHeader.swift
- Sources/ArcGISToolkit/Components/FeatureFormView/FeatureFormView+TitleVisibility.swift
- Sources/ArcGISToolkit/Components/FeatureFormView/FeatureFormView+ValidationErrorVisibility.swift
- Sources/ArcGISToolkit/Components/FeatureFormView/FeatureFormView.swift
- Sources/ArcGISToolkit/Components/Popups/PopupView+PopupHeader.swift
- Sources/ArcGISToolkit/Components/Popups/PopupView+ShowCloseButton.swift
- Sources/ArcGISToolkit/Components/Popups/PopupView.swift
- Sources/ArcGISToolkit/Documentation.docc/Resources/PopupView/PopupViewStep6.swift
Closes #835 
- Adds:
- `PopupView.popupHeader(_:)`
- Controls the visibility of the title and close button (visible by default).
- `FeatureFormView.formHeader(_:)`
- Controls the visibility of the title (visible by default).
- Deprecates:
- `PopupView.showCloseButton(_:)`
> `FeatureFormView` & `PopupView` -  Add ability to hide default headers

- Sources/ArcGISToolkit/Components/FloorFilter/FloorFilter.swift
- Extracts the `ProgressView` from the Floor Filter button. The Floor Filter button isn't now in the view hierarchy until loading is complete, preventing the test from proceeding prematurely.
> Repair `FloorFilterTests.testFloorFilter()`

- Sources/ArcGISToolkit/Components/FloorFilter/FloorFilter.swift
- Sources/ArcGISToolkit/Components/FloorFilter/FloorFilterViewModel.swift
Closes #936 
Fulfills the user request in the linked issue by offering an option to disable the following functionality from the component design spec:
> If there is only 1 site, select it and don't display the sites browser.
Specifically this adds `FloorFilter.automaticSingleSiteSelectionDisabled(_:)` which when used prevents a single site from being automatically selected. If there is more than one site, this modifier has no effect.
> Add `FloorFilter.automaticSingleSiteSelectionDisabled(_:)`

- Sources/ArcGISToolkit/Components/UtilityNetworkTrace/UtilityNetworkTrace.swift
| Before | After |
|---|---|
| <img src="https://github.com/user-attachments/assets/12338c1a-5010-4008-985d-b9d40b50539b"> | <img src="https://github.com/user-attachments/assets/a7fdb1b3-526b-4daa-b4b2-5c3b093a9031"> |
This change has no effect on Mac Catalyst.
> `UtilityNetworkTrace` - Fix button capitalization

- .swiftlint.yml
- Examples/Examples/FeatureFormExampleView.swift
- Sources/ArcGISToolkit/Documentation.docc/Resources/FeatureFormView/FeatureFormViewStep10.swift
- Sources/ArcGISToolkit/Documentation.docc/Resources/FeatureFormView/FeatureFormViewStep11.swift
- Sources/ArcGISToolkit/Documentation.docc/Resources/FeatureFormView/FeatureFormViewStep12.swift
- Sources/ArcGISToolkit/Documentation.docc/Resources/FeatureFormView/FeatureFormViewStep13.swift
- Sources/ArcGISToolkit/Documentation.docc/Resources/FeatureFormView/FeatureFormViewStep14.swift
- Sources/ArcGISToolkit/Documentation.docc/Resources/FeatureFormView/FeatureFormViewStep15.swift
- Sources/ArcGISToolkit/Documentation.docc/Resources/FeatureFormView/FeatureFormViewStep16.swift
- Sources/ArcGISToolkit/Documentation.docc/Resources/FeatureFormView/FeatureFormViewStep17.swift
- Sources/ArcGISToolkit/Documentation.docc/Resources/FeatureFormView/FeatureFormViewStep18.swift
This PR updates the Swift Lint `opt_in_rules` (similar to Esri/arcgis-maps-sdk-swift-samples#556):
- Removes some that are now [default rules](https://realm.github.io/SwiftLint/rule-directory.html).
- Adds some that are present in the Swift API but were missing here.
Ensure the projects build without warnings.
> [Update] Swift Lint opt-in rules

- Examples/Examples/CompassExampleView.swift
- Sources/ArcGISToolkit/Components/Compass/Compass.swift
Closes #990
As part of an app I am building I have added sensory feedback when the MapView rotation/heading snaps to zero. This has been a nice feature. I think it could be useful to build this feature into the Compass component.
@dg0yal thoughts on this?
> add sensory feedback, haptics, to compass

- Sources/ArcGISToolkit/Components/Search/SearchView.swift
- Sources/ArcGISToolkit/Components/Search/SearchViewModel.swift
- Sources/ArcGISToolkit/Extensions/SwiftUI/View.swift
Use built-in selection mechanism. This ensures that rows have the proper highlight and selection colors and that they have a hover effect on visionOS.
  | Before | After
--- | ------ | -----
iOS | ![Screen Recording 2025-01-10 at 9 49 13 PM](https://github.com/user-attachments/assets/a9b0486d-4eae-4a3a-98fc-2a09d3ef91c9) | ![Screen Recording 2025-01-10 at 9 43 09 PM](https://github.com/user-attachments/assets/029078dc-de9e-454c-8da2-7480bf8a01df)
Mac Catalyst | ![Screen Recording 2025-01-10 at 9 50 34 PM](https://github.com/user-attachments/assets/df1351b3-8bc4-4fb8-a13b-3e2860a37ded) | ![Screen Recording 2025-01-10 at 9 38 34 PM](https://github.com/user-attachments/assets/4e7188a1-cd34-421a-bee4-476a72f3e127)
visionOS | ![Screen Recording 2025-01-10 at 10 00 …
> Refactor `SearchView` selection

- AuthenticationExample/AuthenticationExample/UserView.swift
- Examples/Examples/FeatureFormExampleView.swift
- Sources/ArcGISToolkit/Common/AttachmentPreview.swift
- Sources/ArcGISToolkit/Common/FlashlightButton.swift
- Sources/ArcGISToolkit/Common/ThumbnailView.swift
- Sources/ArcGISToolkit/Components/Augmented Reality/Utilities/CalibrationView.swift
- Sources/ArcGISToolkit/Components/Augmented Reality/WorldScaleSceneView.swift
- Sources/ArcGISToolkit/Components/BasemapGallery/BasemapGalleryCell.swift
- Sources/ArcGISToolkit/Components/Bookmarks/Bookmarks.swift
- Sources/ArcGISToolkit/Components/FeatureFormView/Subviews/Inputs/RadioButtonsInput.swift
- Sources/ArcGISToolkit/Components/FloorFilter/LevelSelector.swift
- Sources/ArcGISToolkit/Components/FloorFilter/SiteAndFacilitySelector.swift
- Sources/ArcGISToolkit/Components/Popups/MediaPopupElementView.swift
- Sources/ArcGISToolkit/Components/Popups/PopupMedia/Charts/ChartMediaView.swift
- Sources/ArcGISToolkit/Components/Popups/PopupMedia/Images/ImageMediaView.swift
- Sources/ArcGISToolkit/Components/Popups/PopupMedia/PopupMediaFooter.swift
- Sources/ArcGISToolkit/Components/Search/SearchView.swift
- Sources/ArcGISToolkit/Components/UtilityNetworkTrace/UtilityNetworkTrace.swift
- Sources/ArcGISToolkit/Documentation.docc/Resources/FeatureFormView/FeatureFormViewStep18.swift
While working on visionOS support, we've encountered code like this and updated it. This just does it all in one go.
> Use implicit member expressions for `[Shape]Style`

- Sources/ArcGISToolkit/Components/Offline/PreplannedListItemView.swift
- Sources/ArcGISToolkit/Components/Offline/PreplannedMetadataView.swift
Closes https://github.com/Esri/arcgis-maps-sdk-swift-toolkit/issues/1004.
Adds tap gesture to shows metadata view for all map areas.
- When map area is not downloaded:
- Shows "Download" button
- When map area is downloading:
- "Download" button is disabled
- When map area is downloaded:
- Shows file size
- Shows "Remove Download" button
Screenshots:
> Offline: Add download button to metadata view

- Sources/ArcGISToolkit/Components/FeatureFormView/FormViewModel.swift
No need for this initializer to be public.
> Change `FormViewModel.init(featureForm:)` to internal

- Test Runner/UI Tests/FloorFilterTests.swift
Due to changes for visionOS, some `staticText` items are now `buttons`. Changing to `buttons` fixes the tests.
> FloorFilter - fix tests

- Test Runner/UI Tests/FeatureFormViewTests.swift
- Renames `FormViewTests.swift` to `FeatureFormViewTests.swift` to match the name of the contained class.
- Moves all form title checks to new method `assertFormOpened(titleElement:)` and bumps timeout from 10 to 30 seconds to hopefully stabilize occasional test failures where forms are slower to open.
> `FeatureFormView` - Test revisions

- Test Runner/Test Runner.xcodeproj/project.pbxproj
I couldn't run the `FeatureFormViewTests` then I realized that file name was recently changed and there weren't any changes reflected in the project. This fixes the problem.
@dfeinzimer I'm assuming you changed the file name while in the swift package (and not the Test Runner project) and that is why the file reference changes didn't happen :)
> Fix file references to `FeatureFormViewTests`

- Examples/Examples/FeatureFormExampleView.swift
This class is specific to a particular example, but, by being at the top level as non-private, it was exposed to all examples. This fixes that.
Note: The one declaration that uses the type is already private.
> Make top level `Model` class private

- Sources/ArcGISToolkit/Components/FeatureFormView/Subviews/FeatureFormGroupedContentView.swift
If we proceed with the proposal to integrate `Form` into `FeatureFormView`, this view will not be needed and we can just use `Section { }` instead. 
In the meantime, this allows us to replicate what `Form { Section { } }` provides to match the proposed entry point for navigating associations in `UtilityNetworkAssociationFormElement`.
</p>
> Add `FeatureFormGroupedContentView`

- Sources/ArcGISToolkit/Components/FeatureFormView/FeatureFormView.swift
If the association's `toElement`'s network source table has a Feature Form definition, use the definition's title as the association display name; otherwise, use the [AssetGroup - ObjectID] of `toElement`.
> `UtilityNetworkAssociationsFormElementView` - Adjust association display name

- Sources/ArcGISToolkit/Components/FloatingPanel/FloatingPanel.swift
Closes #1021
The problem here was the background on the floating panel was somehow overriding some default styling on the Utility Network component. If you put the Utility Network component in a sheet you would see it looks as expected but it would look incorrect in a floating panel. This fixes that. This doesn't make a visual difference to the Popup Component example.
Utility Network Before:
Utility Network After:
> Adjust background on floating panel for visionOS

- Sources/ArcGISToolkit/Components/Offline/OnDemand/OnDemandConfigurationView.swift
- Sources/ArcGISToolkit/Components/Offline/OnDemand/OnDemandMapAreaSelectorView.swift
The area selector handle views now add the layout for the rounded corners.
> Offline: Refactor area selector layout

- Sources/ArcGISToolkit/Components/Offline/OnDemand/OnDemandConfigurationView.swift
Fixes a bug where the keyboard presentation causes the map view visible area to change.
> Offline: Ignore keyboard safe area

- Sources/ArcGISToolkit/Components/Offline/Preplanned/PreplannedMapModel.swift
- Tests/ArcGISToolkitTests/PreplannedMapModelTests.swift
- Fail preplanned job on errors in `PreplannedMapModel`
- Set API key and use non-background URL session in `PreplannedMapModelTests`
- Test suite runs in under ~20 seconds
> Offline: Update preplanned map model tests

- Tests/ArcGISToolkitTests/OnDemandMapModelTests.swift
Adds tests for the `OnDemandMapModel`. 
- Test suite runs in ~100 seconds due to test case that downloads mmpk.
> Offline: Add on demand map model tests

- Sources/ArcGISToolkit/Common/NavigationLayer/NavigationLayer+DestinationHeader.swift
- Sources/ArcGISToolkit/Common/NavigationLayer/NavigationLayer.swift
- Sources/ArcGISToolkit/Common/NavigationLayer/NavigationLayerModel.swift
- Sources/ArcGISToolkit/Extensions/SwiftUI/AnyTransition.swift
Proposes `NavigationLayer`, an internal `NavigationStack` alternative to work around the [nested `NavigationStack` limitation](https://developer.apple.com/forums/thread/772650).
</p>
> Add `NavigationLayer`

- Sources/ArcGISToolkit/Components/Augmented Reality/FlyoverSceneView.swift
Sets the atmosphere effect to `.realistic` in `FlyoverSceneView` to fix a bug where the default atmosphere effect of `horizonOnly` caused the top of the view to show the space effect black background with stars. 
Before and after setting atmosphere effect to `.realistic`:
Note: This bug fix should be mentioned in the Toolkit release notes
> AR: Set atmosphere effect for Flyover

- Sources/ArcGISToolkit/Components/Scalebar/Scalebar.swift
fixes https://github.com/Esri/arcgis-maps-sdk-swift-toolkit/issues/1092
This seems to fix the freeze. And it seems that the code was reading the height and then setting the height to what was read.
> fix scalebar freeze

- Sources/ArcGISToolkit/Components/Offline/OnDemand/OnDemandConfigurationView.swift
This changes the UX so that controls are disabled until the map is completely done with initial drawing. This allows us to remove the arbitrary workaround.
> remove arbitrary sleep workaround

- Sources/ArcGISToolkit/Components/Popups/PopupMedia/Charts/BarChart.swift
- Sources/ArcGISToolkit/Components/Popups/PopupMedia/Charts/ChartData.swift
- Sources/ArcGISToolkit/Components/Popups/PopupMedia/Charts/LineChart.swift
- Sources/ArcGISToolkit/Components/Popups/PopupMedia/Charts/PieChartModel.swift
This PR adds #995 , for bar chart, line chart, and pie chart.
Please use the runtimecoretest web map (PopupElement Test Case 1.2) to see specified chart colors (pink, green), or use the current popup example to see the default color ramp (mint, teal, …).
<details><summary>code for authentication</summary>
```swift
.onAppear {
ArcGISEnvironment.authenticationManager.arcGISAuthenticationChallengeHandler = ChallengeHandler()
}
.onDisappear {
ArcGISEnvironment.authenticationManager.arcGISAuthenticationChallengeHandler = nil
}
private struct ChallengeHandler: ArcGISAuthenticationChallengeHandler {
func handleArcGISAuthenticationChallenge(
_ challenge: ArcGISAuthenticationChallenge
) async throws -> ArcGISAuthenticationChallenge.Disposition {
// NOTE: Never hardcode login information in a …
```
> Charts: honor popup color from `PopupMediaValue`

- Sources/ArcGISToolkit/Components/Offline/OfflineMapAreaListItemView.swift
- Sources/ArcGISToolkit/Components/Offline/OfflineMapAreasView.swift
- Sources/ArcGISToolkit/Components/Offline/OnDemand/OnDemandListItemView.swift
- Sources/ArcGISToolkit/Components/Offline/Preplanned/PreplannedListItemView.swift
Adds support to set the visibility of the "Done" button with the `doneButton(Visibility)` view modifier on the `OfflineMapAreasView`. This allows various types of navigation to be supported.
Closes `swift/6471`.
> Offline: Done button visibility

- Sources/ArcGISToolkit/Components/Search/SearchView.swift
- Sources/ArcGISToolkit/Components/Search/SearchViewModel.swift
Related #1109 
Between 4489 and 4490 Swift was upgraded from 6.0 to 6.0.3 (see RTC 30409). I suspect the inclusion of these resources was broken by that upgrade.
> `SearchView` - Resolve crashing condition with `swift-toolkit-daily`

- Tests/ArcGISToolkitTests/OnDemandMapModelTests.swift
- Tests/ArcGISToolkitTests/PreplannedMapModelTests.swift
Related to `swift/6723`
Fixes the following flakey tests:
Increases the timeout for the download to succeed.
- `PreplannedMapModelTests.testLoadMobileMapPackage()`
- `OnDemandMapModelTests.testLoadMobileMapPackage()`
Removes step to download mmpk, and instead removes an empty file.
- `PreplannedMapModelTests.testRemoveDownloadedPreplannedMapArea()`
> Offline: Fix flakey tests

- Sources/ArcGISToolkit/Components/Offline/OnDemand/OnDemandListItemView.swift
- Sources/ArcGISToolkit/Components/Offline/Preplanned/PreplannedListItemView.swift
This Boolean value seems to be unused, as the value is moved to [`OfflineMapAreaListItemView`](https://github.com/Esri/arcgis-maps-sdk-swift-toolkit/blob/v.next/Sources/ArcGISToolkit/Components/Offline/OfflineMapAreaListItemView.swift#L42).
> offline: Remove unused `metadataViewIsPresented`

- Sources/ArcGISToolkit/Components/Offline/Utilities/URL+Offline.swift
Fix docs for example file paths. The base path for map area storage has become `Documents/com.esri.ArcGISToolkit.offlineManager/` so fix that in the docs.
> offline: Update URL+Offline.swift

- Sources/ArcGISToolkit/Components/Popups/FieldsPopupElementView.swift
With the visionOS updates, the "View" button in the `FieldsPopupElementView` changed from borderless to bordered. This just changes it back for non-visionOS builds.
> Field popup element button

- Sources/ArcGISToolkit/Components/Offline/Preplanned/PreplannedMapModel.swift
Add back explicit existential `any` to future-proof new Swift language mode.
Missed it as I prematurely merged the [PR](https://github.com/Esri/arcgis-maps-sdk-swift-toolkit/pull/1136#discussion_r2036148755)
> offline: Update PreplannedMapModel.swift

- Sources/ArcGISToolkit/Components/Offline/OnDemand/OnDemandConfigurationView.swift
- On iOS 17 simulator, with the `RotateGesture`, it would cause the sheet to move when panning the map view. Reordering the priority gestures fixes the problem.
- On iOS 18 simulator, with or without the change, the sheet doesn't move.
This was introduced in #1067. ~~However, I couldn't figure out what the pinching problem was referring to. Let me know if there are other considerations.~~
test map: 3da658f2492f4cfd8494970ef489d2c5
https://github.com/user-attachments/assets/cf94e8e9-b491-4004-a2d9-1f7979127844
> offline: Reorder the rotate gesture priorities on config view

- Sources/ArcGISToolkit/Components/Offline/OnDemand/OnDemandConfigurationView.swift
#1149 fixes a bug that stops the on-demand workflow from downloading an area without moving the extent selector. Please test with an API key and the breweries web map 3da658f2492f4cfd8494970ef489d2c5 .
After these cherry-picked changes are reviewed, I'll figure out what version numbers need to be updated.
- edit: no example app version needs to be bumped as there aren't changes in them. They will pick up the latest toolkit once this patch is tagged.
> hotfix: 200.7.1 Release

- Sources/ArcGISToolkit/Common/CameraRequester.swift
- Sources/ArcGISToolkit/Common/CodeScanner.swift
- Sources/ArcGISToolkit/Components/Authentication/CertificatePickerViewModifier.swift
- Sources/ArcGISToolkit/Components/Authentication/LoginViewModifier.swift
- Sources/ArcGISToolkit/Components/Authentication/TrustHostViewModifier.swift
- Sources/ArcGISToolkit/Components/Bookmarks/BookmarksHeader.swift
- Sources/ArcGISToolkit/Components/FloorFilter/SiteAndFacilitySelector.swift
- Sources/ArcGISToolkit/Components/Offline/OnDemand/OnDemandConfigurationView.swift
- Sources/ArcGISToolkit/Components/Popups/PopupMedia/MediaDetailView.swift
- Sources/ArcGISToolkit/Extensions/Swift/LocalizedStringResource.swift
- Sources/ArcGISToolkit/Extensions/Swift/String.swift
- Sources/ArcGISToolkit/Extensions/SwiftUI/Button.swift
- Sources/ArcGISToolkit/Extensions/SwiftUI/Text.swift
- Sources/ArcGISToolkit/Resources/en.lproj/Localizable.strings
- Sources/ArcGISToolkit/Utility/CredentialInputView.swift
Related to `swift/6790`
- Change some localized strings from type String to type LocalizedStringResource
- Use localized Button.cancel, Button.cancel, Button.ok where applicable
- Remove redundant localized string for "Cancel"
> Fix: Refactor localized strings

- Sources/ArcGISToolkit/Components/FeatureFormView/FeatureFormView.swift
Closes Apollo issue: _Swift Toolkit - Provide customization to hide Save & Discard # 1137_
Adds an `editingButtons(_ visibility: Visibility)` modifier to the `FeatureFormView`, which controls the visibility of the `FormFooter`, showing the "Discard" and "Save" buttons
> Forms: Allow users to control the visibility of the editing buttons

- Test Runner/UI Tests/FeatureFormViewTests.swift
visionOS does not support barcode scanning; this button is not shown.
> `FeatureFormView` - Fix testCase_11_1 for visionOS

- Sources/ArcGISToolkit/Common/AttachmentsFeatureElementView.swift
- Sources/ArcGISToolkit/Components/FeatureFormView/InternalFeatureFormView.Model.swift
- Sources/ArcGISToolkit/Components/FeatureFormView/InternalFeatureFormView.swift
- Sources/ArcGISToolkit/Components/FeatureFormView/Subviews/Inputs/ComboBoxInput.swift
- Sources/ArcGISToolkit/Components/FeatureFormView/Subviews/Inputs/DateTimeInput.swift
- Sources/ArcGISToolkit/Components/FeatureFormView/Subviews/Inputs/Other/InputFooter.swift
- Sources/ArcGISToolkit/Components/FeatureFormView/Subviews/Inputs/RadioButtonsInput.swift
- Sources/ArcGISToolkit/Components/FeatureFormView/Subviews/Inputs/SwitchInput.swift
- Sources/ArcGISToolkit/Components/FeatureFormView/Subviews/Inputs/TextInput.swift
- Sources/ArcGISToolkit/Components/FeatureFormView/Subviews/UtilityAssociationsFormElementView.swift
Related Apollo 1222
In #1161, a new model (`FeatureFormViewModel`) will be added for the top-level public `FeatureFormView` so that form elements deep in the view hierarchy can trigger an overlay presentation over the entire feature form view. I propose this rename to clearly delineate between the two models.
> `FeatureFormView` - Rename `FormViewModel` to `InternalFeatureFormViewModel`

- Sources/ArcGISToolkit/Common/AttachmentsFeatureElementView.swift
- Sources/ArcGISToolkit/Components/FeatureFormView/InternalFeatureFormView.swift
- Sources/ArcGISToolkit/Components/Popups/PopupView.swift
This resolves a crash introduced in #1160 by ensuring that an `InternalFeatureFormViewModel` is present when needed.
Unlike with an `ObservableObject`, if an `@Observable` object is not in the environment, such as is the case when using `AttachmentsFeatureElementView` in a popup, a fatal error is encountered:
> SwiftUICore/Environment+Objects.swift:34: Fatal error: No Observable object of type InternalFeatureFormViewModel found. A View.environmentObject(_:) for InternalFeatureFormViewModel may be missing as an ancestor of this view.
Note that `FormViewModel` was renamed to `InternalFeatureFormViewModel` after #1160 in #1162.
Thank you to @CalebRas for catching this new crash.
> Add new usage specific initializers for AttachmentsFeatureElementView

- Sources/ArcGISToolkit/Components/Offline/Preplanned/PreplannedListItemView.swift
Remove unneeded switch-case as all failure cases are represented with an  ![exclamationmark circle](https://github.com/user-attachments/assets/c6142410-1ba9-44fc-b2f4-9469cacec742)
> Offline: Update PreplannedListItemView to remove unneeded case

- Sources/ArcGISToolkit/Components/Offline/OfflineMapAreasView.swift
- Sources/ArcGISToolkit/Components/Offline/OnDemand/OnDemandConfigurationView.swift
Close #1155. Remove the `Backported` enum introduced in #1145 to support `ContentUnavailableView` on iOS 16.
> Offline: Remove `Backported`

- AuthenticationExample/AuthenticationExample/AuthenticationApp.swift
- AuthenticationExample/AuthenticationExample/ProfileView.swift
- Sources/ArcGISToolkit/Components/Authentication/AuthenticationManager.swift
- Sources/ArcGISToolkit/Components/Authentication/Authenticator.swift
- Sources/ArcGISToolkit/Documentation.docc/Resources/Authenticator/AuthenticatorStep3.swift
- Sources/ArcGISToolkit/Documentation.docc/Resources/Authenticator/AuthenticatorStep4.swift
- Sources/ArcGISToolkit/Documentation.docc/Tutorials/AuthenticatorTutorial.tutorial
- Tests/ArcGISToolkitTests/AuthenticatorTests.swift
- Serenity 2056
- Closes https://github.com/Esri/arcgis-maps-sdk-swift-toolkit/issues/988
- Test `ArcGIS.com` portal with and without OAuth user configuration
- Test portal behind IAP using the OAuth and IAP configurations
- Please reach out to me to get the configurations to test changes in this PR
- Adds support for `ArcGISAuthenticationChallenge.kind`
- Adds support for `Identity-Aware Proxy (IAP)`
- Deprecates the existing Authenticator initializer
- Adds a new Authenticator initializer that takes an array of `IAPConfigurations`, along with `promptForUntrustedHosts` and `OAuthUserConfigurations`
- Adds a read-write `iapConfigurations` property
- Adds a function to invalidate IAP credentials in the `AuthenticationManager` extension
- Updates documentation and the authenticator tutorial …
> Authenticator: Adds challenge type and Identity-Aware Proxy (IAP) support

- Sources/ArcGISToolkit/Components/Offline/OfflineMapAreaListItemView.swift
- Sources/ArcGISToolkit/Components/Offline/OfflineMapAreaMetadataView.swift
- Sources/ArcGISToolkit/Components/Offline/OnDemand/OnDemandListItemView.swift
- Sources/ArcGISToolkit/Components/Offline/Preplanned/PreplannedListItemView.swift
- Sources/ArcGISToolkit/Extensions/Swift/LocalizedStringResource.swift
- Sources/ArcGISToolkit/Resources/en.lproj/Localizable.strings
Related to https://github.com/Esri/arcgis-maps-sdk-swift-toolkit/issues/1166.
Renames the "Delete Map Area" button to "Remove Download" and "Delete Download" for the preplanned and on-demand use-cases respectively.
> Offline: Rename `delete map area` button

- Test Runner/Test Runner.xcodeproj/project.pbxproj
- Test Runner/TestRunner.xcconfig
- Introduced `.xcconfig` file for the `TestRunner` project to enable scoped manual code signing.
- Default the `CODE_SIGN_STYLE = Automatic` in source `.xcconfig` for local development continuity.
- During CI execution, script workflows programmatically updates `CODE_SIGN_STYLE` to `Manual` and injects the following to ensure a clean separation between local development and CI specific behaviors.
- `DEVELOPMENT_TEAM`
- `CODE_SIGN_IDENTITY`
- `PROVISIONING_PROFILE` (platform-specific for iOS/macOS)
*No changes to local developer workflows, Xcode continues using automatic signing when opened manually via IDE*
* Manual CLI testing ✅
> `TestRunner` - Manual code signing updates for TestRunner

- Examples/Examples/PopupExampleView.swift
- Sources/ArcGISToolkit/Components/Popups/EmbeddedPopupView.swift
- Sources/ArcGISToolkit/Components/Popups/PopupView+Deprecated.swift
- Sources/ArcGISToolkit/Components/Popups/PopupView.swift
- Sources/ArcGISToolkit/Components/Popups/PopupViewHeader.swift
- Sources/ArcGISToolkit/Components/Popups/PopupViewToolbar.swift
- Sources/ArcGISToolkit/Documentation.docc/Resources/PopupView/PopupViewStep6.swift
- Test Runner/Test Runner/TestViews/PopupTestView.swift
Similar to the `FeatureFormView` updates made in #1201, this PR:
- Deprecates `PopupView.init(popup:isPresented:)` in favor of `PopupView.init(root:isPresented:)`.
- Removes `PopupView.closeButton(_:)` in favor of displaying the close button when the passed `isPresented` parameter is non-`nil`.
- Maintains the current behavior of `init(popup:isPresented:)`, `header(_:)`, and `showCloseButton(_:)` to allow developers to move to the new initializer at their own pace.
See feature form PR for more details.
- `apollo/issues/1277`
Ensure the initializers and modifiers work as expected
- See "How to Test" in [#1171](https://github.com/Esri/arcgis-maps-sdk-swift-toolkit/pull/1171) for data containing `UtilityAssociationsPopupElement`s. 
- This snippet can be used to test the deprecated init in …
> `PopupView` - Update initializer to match FeatureForm

- Sources/ArcGISToolkit/Components/Popups/EmbeddedPopupView.swift
This PR fixes an issue where the `PopupView` background wouldn't display correctly when shown in a `popover` on Mac Catalyst. The appearance of the view using other presentation modes and platforms looks to be unaffected by these changes.
- Replace the `PopupExampleView` sheet with a popover:
```swift
.popover(isPresented: $showPopup, attachmentAnchor: .point(.top)) { [popup] in
PopupView(root: popup!, isPresented: $showPopup)
.frame(idealWidth: 320, idealHeight: 500)
}
```
- Run on Mac Catalyst and open a popup.
|Before|After|
|:-:|:-:|
|    ![Screenshot 2025-07-09 at 4 43 12 PM](https://github.com/user-attachments/assets/db532e19-d883-450b-a762-819cbd9a0b4b)    |    ![Screenshot 2025-07-09 at 4 44 51 PM](https://github.com/user-attachments/assets/a2601dd2-6615-4c1d-adee-2aaed17f6a75) …
> `PopupView` - Fix popover background on Mac Catalyst

- Sources/ArcGISToolkit/Components/FeatureFormView/FeatureFormView+ValidationErrorVisibility.swift
As reported [here](https://github.com/Esri/arcgis-maps-sdk-swift-toolkit/pull/1176#discussion_r2201473177).
> Doc ref fix in FeatureFormView+ValidationErrorVisibility.swift

- Test Runner/UI Tests/PopupViewTests.swift
This PR removes the expect failures from the `PopupViewTests` now that the issue has been resolved.
- `nautilus/issues/2625`
-  #1204
- Run `PopupViewTests` on device and ensure they pass.
> `PopupView` - Remove test expect failues

- Test Runner/UI Tests/FeatureFormViewTests.swift
Attempts to resolve flakiness in FeatureFormView UNA test cases 12_3, 12_4, and 12_5 in recent daily test runs.
> `FeatureFormView` - Stabilize UNA test cases 12_3, 12_4, 12_5

- Sources/ArcGISToolkit/Components/FeatureFormView/FeatureFormToolbar.swift
I discovered the native NavigationStack back button has a long-press context menu which lets a user jump to an arbitrary item:
</p>
It was Apollo's intention to net yet support navigating to arbitrary items in the navigation path.
This PR changes the system navigation button to be always disabled and replaced by the custom navigation back button.
> `FeatureFormView` - Always use custom nav stack back button

- Sources/ArcGISToolkit/Components/Popups/EmbeddedPopupView.swift
- Sources/ArcGISToolkit/Components/Popups/UtilityAssociationsPopupElementView.swift
This PR fixes a couple of `PopupView` list issues:
1. Removes extra horizontal list row insets added in [#1211](https://github.com/Esri/arcgis-maps-sdk-swift-toolkit/pull/1211) (see [comment](https://github.com/Esri/arcgis-maps-sdk-swift-toolkit/pull/1211#issuecomment-3058388649)).
-  iOS and visionOS remain unaffected by these changes.
2. Fixes a bug where the close button in the toolbar would jump when opening a navigation link.
- This appears to be a SwiftUI bug when an `inset` list is shown with a parent `NavigationSplitView`. As a result, all of the lists in view had to be changed to `plain`.
3. Continues to resolve the issue where the PopupView background wouldn't display correctly when shown in a `popover` on Mac Catalyst. See …
> `PopupView` - Fix list bugs

- Sources/ArcGISToolkit/Components/Offline/OfflineMapAreasView.swift
- Sources/ArcGISToolkit/Components/Offline/OfflineMapViewModel.swift
Close #1210 . 
Currently, if a specific set of steps are followed:
1. While online, open the example app.
2. Without opening the Offline Maps/Areas screen, disconnect from the internet.
3. Then open the Offline Maps screen.
It would show the `onDemandMapAreasView` even if the mode for the offline component is undetermined
https://github.com/Esri/arcgis-maps-sdk-swift-toolkit/blob/472d484b0190ce12aa90f76fef800e73873cb5e8/Sources/ArcGISToolkit/Components/Offline/OfflineMapAreasView.swift#L158-L163
Instead, the user propose to show the `noInternetNoAreasView` when there is no Internet connection.
See some more comment in the code below.
> Offline: Fix offline mode undetermined for no internet

- Sources/ArcGISToolkit/Common/AttachmentPreview.swift
- Sources/ArcGISToolkit/Common/AttachmentsFeatureElementView.swift
- Sources/ArcGISToolkit/Components/FeatureFormView/EmbeddedFeatureFormViewModel.swift
- Sources/ArcGISToolkit/Utility/Carousel.swift
Apollo 1193
- `EmbeddedFeatureFormViewModel`
- Fixes a retain cycle that causes the model to outlive the FFV component.
- `Carousel`
- Revised and simplified to fix a retain cycle that causes `AttachmentModel`s to outlive the FFV component.
> `FeatureFormView` - Various fixes

- Examples/Examples/LocationButtonExampleView.swift
- Sources/ArcGISToolkit/Components/LocationButton/LocationButton.swift
- Tests/ArcGISToolkitTests/LocationButtonTests.swift
This PR fixes the daily build error caused by visionOS not having compass. Related to #1170
> location button: fix build errors on visionOS

- Package.swift
- Sources/ArcGISToolkit/Components/LocationButton/LocationButton.swift
- Sources/ArcGISToolkit/Extensions/Swift/Sequence.swift
There was an issue https://github.com/apple/swift-algorithms/issues/189 with using Swift Algorithms that prevents it from being built when library evolution is enabled. While the issue is being solved by Apple, we need to remove swift-algorithms dependency and add the needed algorithm by hand. The method is adapted from [here](https://github.com/apple/swift-algorithms/blob/main/Sources/Algorithms/Unique.swift#L74).
Currently, the toolkit daily build is broken due to this.
> location button: Remove Swift Algorithms

- Sources/ArcGISToolkit/Components/Offline/OfflineMapAreasView.swift
- Sources/ArcGISToolkit/Components/Offline/OnDemand/OnDemandConfigurationView.swift
Close #1260 . When working on #1186 I didn't test if the localization worked. `ContentUnavailableView` has a bit problem and using `LocalizedStringResource` within a `Label` is the most stable approach at this point.
> Fix usages of LocalizedStringResource.key for localizations

- Sources/ArcGISToolkit/Components/FeatureFormView/Subviews/Inputs/TextInput.swift
Close #853 . Now all the `Button("Done") { // … }` are replaced by `Button.done { // … }` in the toolkit. The examples and tutorials remain unchanged.
> Use done button extension

- Test Runner/Test Runner/TestViews/UtilityNetworkTraceTestView.swift
visionOS doesn't have this parameter in the Floating Panel modifier.
> Repair Test Runner build for visionOS

- Sources/ArcGISToolkit/Components/Offline/OfflineMapAreasView.swift
Close #1233 . Instead of using the clone of the web map, create a new map from the web map's item. This allows the new map to make network request and thus, get the load result be either success or failure.
To test:
Web map item ID: 3da658f2492f4cfd8494970ef489d2c5 ; API key is needed
> offline: Don't use clone as the load status will be cloned

- Sources/ArcGISToolkit/Components/FeatureFormView/EmbeddedFeatureFormViewModel.swift
This PR updates `EmbeddedFeatureFormViewModel` to remove an unused property, `presentedForm`, and the  `featureForm` setter, since it is only ever set in the model's initializer.
Ensure the package still builds.
> `FeatureFormView` - Remove unused `EmbeddedFeatureFormViewModel` properties

- Test Runner/Test Runner/TestViews/FeatureFormTestView.swift
- Test Runner/UI Tests/FeatureFormViewTests.swift
Improves the FeatureFormView UI tests by using launch arguments to select the test case. Replaces the current process of picking the desired case from a list.
Saves a little under 1 minute across the 34 FeatureFormView test cases.
> `FeatureFormView` - Improve UI test case selection

- Test Runner/UI Tests/FeatureFormViewTests.swift
This test started consistently failing on Sept 23. 
I'm not sure exactly why the behavior changed suddenly, but it seems like the text in the rename dialogue is no longer highlighted on presentation and fully-replaced.
> Repair `FeatureFormViewTests.testAttachmentRenaming()`

- Sources/ArcGISToolkit/Components/FeatureFormView/FeatureFormView.swift
- Sources/ArcGISToolkit/Components/FeatureFormView/NavigationPathItem.swift
- Sources/ArcGISToolkit/Components/FeatureFormView/Subviews/FormElements/UtilityAssociationsFormElement/UtilityAssociationAssetTypesView.swift
- Sources/ArcGISToolkit/Components/FeatureFormView/Subviews/FormElements/UtilityAssociationsFormElement/UtilityAssociationCreationView.swift
- Sources/ArcGISToolkit/Components/FeatureFormView/Subviews/FormElements/UtilityAssociationsFormElement/UtilityAssociationDetailsView.swift
- Sources/ArcGISToolkit/Components/FeatureFormView/Subviews/FormElements/UtilityAssociationsFormElement/UtilityAssociationFeatureCandidatesView.swift
- Sources/ArcGISToolkit/Extensions/SwiftUI/Text.swift
- Sources/ArcGISToolkit/Resources/en.lproj/Localizable.strings
Ref Apollo 1443
Follow-up to #1177 to use latest API revisions for utility association creation.
- Adds asset type selection into the workflow.
- Adds terminal selection on the "from" and "to" elements.
> `FeatureFormView` - Support adding utility network associations (Part 2)
